### ISSUE TITLE
How to use BLKSSZGET and BLKDISCARD?

### ISSUE THREAD

**Issue by cecton** [nix-rust/nix#1006]
I'm trying to call the ioctl for BLKSSZGET and BLKDISCARD but I can't figure out how to declare them properly with the macro.

Here is the relevant C code in the kernel sources:
```c
/* the read-only stuff doesn't really belong here, but any other place is
   probably as bad and I don't want to create yet another include file. */
(...)
#define BLKSSZGET  _IO(0x12,104)/* get block device sector size */
(...)
/* A jump here: 108-111 have been used for various private purposes. */
#define BLKBSZGET  _IOR(0x12,112,size_t)
#define BLKBSZSET  _IOW(0x12,113,size_t)
#define BLKGETSIZE64 _IOR(0x12,114,size_t)	/* return device size in bytes (u64 *arg) */
(...)
#define BLKDISCARD _IO(0x12,119)
(...)
```

And the relevant C code (from blkdiscard) I'm trying to reproduce in Rust:

```c
	int c, fd, verbose = 0, secsize;
	uint64_t end, blksize, step, range[2], stats[2];
(...)
	if (ioctl(fd, BLKSSZGET, &secsize))
		err(EXIT_FAILURE, _("%s: BLKSSZGET ioctl failed"), path);
(...)
			if (ioctl(fd, BLKDISCARD, &range))
				err(EXIT_FAILURE, _("%s: BLKDISCARD ioctl failed"), path);
			break;
```

For example I managed to get BLKGETSIZE64 working with `ioctl_read!` easily. But BLKSSZGET and BLKDISCARD seems to take no argument despite the C code is clearly passing an argument somehow.

I tried to use `ioctl_read!` for BLKSSZGET but it fails with the error: `ENOTTY: Not a typewriter`.
I tried to use `ioctl_write_ptr!` for BLKDISCARD but it fails with the same error.

If I do use `ioctl_none!` with BLKSSZGET then it works (returns 0), I just don't have my result back.

This issue might be related to #781

**Comment by asomers** [comment]
This is a bug in Linux.  Those ioctls aren't properly defined.  Notice how `BLKSSZGET` is defined as `_IO` instead of `_IOR`?  That's wrong.  You can't use Nix's `ioctl_read!` for wrongly defined ioctls like that.  Instead, you'll have to use `ioctl_read_bad!`.
https://docs.rs/nix/0.12.0/nix/sys/ioctl/index.html#using-bad-ioctls

**Comment by cecton** [comment]
Thanks for your help!

I thought so but I cannot define it using `ioctl_read_bad!` because it accepts only one of the arguments:

```rust
ioctl_read_bad!(blksszget, 0x12, 104, u64)
```

```
error: no rules expected the token `104`
   --> src/main.rs:197:34
    |
197 | ioctl_read_bad!(blksszget, 0x12, 104, u64);
    |                                  ^^^ no rules expected this token in macro call
```

**Comment by asomers** [comment]
Yep.  The Linux headers combine the 0x12 and the 104 to generate the full ioctl command number.  You'll have to figure out what that is in order to use `ioctl_read_bad`.

**Comment by cecton** [comment]
:scream:

... okay... will start digging

**Comment by cecton** [comment]
I changed the code to add this:
```
    err(EXIT_FAILURE, _("%d: BLKSSZGET ioctl failed"), BLKSSZGET);                                                                                                                                                                                                                                                      
```
And then I recompiled and executed. It outputs this:
```
blkdiscard: 4712: BLKSSZGET ioctl failed: Success
```
Which is 0x1268. Which is simply the concatenation of 0x12 with 104 (0x68).

And it worked \o/ hurray 

Thanks a lot for your help

**Comment by barafael** [comment]
Just for reference, I think BLKDISCARD would be:
`nix::ioctl_write_ptr_bad!(blkdiscard, nix::request_code_none!(0x12, 119), [u64; 2]);`
