### ISSUE TITLE
Could not find `termios` in `sys` when cross compiling for aarch64-apple-ios

### ISSUE THREAD

**Issue by akatasonov** [nix-rust/nix#1021]
I'm cross compiling a project that uses mortal v0.1.5 as a dependency for aarch64-apple-ios and the compilation fails with:

```
23 | use nix::sys::termios::{
   |               ^^^^^^^ could not find `termios` in `sys`
```

As far as I can tell nix does support aarch64. Is this a bug or some misconfiguration on my end?

**Comment by Susurrus** [comment]
While `nix` does support that target, it doesn't mean every subsystem in `nix` is exposed on it. However, I don't see anything excluding `termios` from `aarch64-apple-ios`.

I do see that `mortal` relies on `nix` 0.7, while the current release is 0.13. Probably they'll need to update their dependencies and make a new release and that'll fix this issue. Please open an issue with the `mortal` developer to do so.
