### ISSUE TITLE
`ptrace_other` always returns 0 (in case of success)

### ISSUE THREAD

**Issue by soenkehahn** [nix-rust/nix#1022]
[`ptrace_other`](https://github.com/nix-rust/nix/blob/master/src/sys/ptrace/linux.rs#L243) (and therefore also [`ptrace`](https://github.com/nix-rust/nix/blob/master/src/sys/ptrace/linux.rs#L180)) seem to -- in case of success (`Result::Ok`) -- always return `0`. This is really confusing since `libc::ptrace` does return useful results. Is this just a bug? If not, I wonder why this is better than returning `()`.

**Comment by asomers** [comment]
Well, `ptrace` is deprecated now.  Its replacements like `ptrace_get_data` have more useful return values.
