### ISSUE TITLE
Feature request: Add Linux's IP_RECVORIGDSTADDR socket option and respective IP_ORIGDSTADDR control message.

### ISSUE THREAD

**Issue by vi** [nix-rust/nix#1023]
Make `nix` [TPROXY](https://github.com/ahupowerdns/tproxydoc/blob/master/tproxy.md)-ready.

**Comment by asomers** [comment]
Care to submit a PR for it?

**Comment by vi** [comment]
Maybe later.

**Comment by hunts** [comment]
Bump. Any updates? We'd like to add this support in order to make a Rust app work with [Tubular](https://github.com/cloudflare/tubular) (see [example of required socket options](https://github.com/cloudflare/tubular/tree/main/example)).

**Comment by hunts** [comment]
Looks like this is addressed by #1767 now.

**Comment by asomers** [comment]
Fixed by #1772.
