### ISSUE TITLE
Cannot pass RawFd to function with trait bound T: AsRawFd

### ISSUE THREAD

**Issue by gatoWololo** [nix-rust/nix#1028]
Hello! Thank you for the great library I use Nix for all my projects.

I am trying to call `nix::sys::statvfs::fstatvfs` with signature: `pub fn fstatvfs<T: AsRawFd>(fd: &T) -> Result<Statvfs>`. I have a RawFd:

```rust
let fdref: RawFd = ...;
match nix::sys::statvfs::fstatvfs(& fdref) {
...
}
```

Error:
```
error[E0277]: the trait bound `i32: std::os::unix::io::AsRawFd` is not satisfied
   --> src/detfs.rs:992:15
    |
992 |         match nix::sys::statvfs::fstatvfs(& fdref) {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::os::unix::io::AsRawFd` is not implemented for `i32`
    |
    = note: required by `nix::sys::statvfs::fstatvfs`
```

So it seems I cannot use a RawFd to call a function with T: AsRawFd trait bound?
I ended up wrapping my RawFd in a struct which implemented AsRawFd:
```rust
struct Fd(RawFd);
use std::os::unix::io::AsRawFd;
impl AsRawFd for Fd {
    fn as_raw_fd(&self) -> RawFd {
        self.0
    }
}
```

Which works, but is really weird to have to do. Am I missing something?

**Comment by asomers** [comment]
You aren't missing anything.  The problem is that `RawFd` is defined as a type alias for `i32`, not a struct.  So there's no way to add methods to it without also adding those methods to `i32`.
https://github.com/rust-lang/rust/pull/41035
