### ISSUE TITLE
Shall safety status of `unistd::fork` be the same as std's `Process::pre_exec`?

### ISSUE THREAD

**Issue by vi** [nix-rust/nix#1030]
It is going to be [made unsafe](https://github.com/rust-lang/rust/pull/58059/files), but nix's `fork` seems to be [still safe](https://github.com/nix-rust/nix/pull/695).

**Comment by asomers** [comment]
Yep, we should do the same.

**Comment by RalfJung** [comment]
Indeed, `fork` should be marked unsafe. It even has a "safety" comment, that should never be the case of a safe function.

**Comment by vi** [comment]
Why is it still not marked unsafe?

Is it just missing a pull request that adds `unsafe` to the function and `unsafe { } ` to the tests?

**Comment by asomers** [comment]
Yep.

**Comment by vi** [comment]
@asomers, Make the pull request.
