### ISSUE TITLE
waitpid() returns EINVAL on macos for WaitPidFlag::WSTOPPED 

### ISSUE THREAD

**Issue by rizsotto** [nix-rust/nix#1037]
First of all, thanks for this crate! It's very pleasant to use.

I'm trying to port my code from linux to macos. I use fork-exec-waitpid to spawn and monitor processes. Noticed that passing `WaitPidFlag::WSTOPPED`is needed on linux to achieve what I want, but it produce error on macos. (The error is `Sys(EINVAL)`)

I'm not so familiar with macos, but read through the manual page of `waitpid` it does not mention `WSTOPPED`, so the invalid argument error looks acceptable. My question would be, can you make it _not available_ this enum value for macos? I would prefer to have this as a compile-error, rather than a debug process. :smile:

**Comment by asomers** [comment]
It seems that OSX does use `WSTOPPED`, but only for `waitid` instead of `waitpid`?

https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/wait.h

**Comment by rizsotto** [comment]
I was not dig deep enough. :smile: Thanks to clarify it for me!
