### ISSUE TITLE
Rename project to distinguish from the Nix ecosystem

### ISSUE THREAD

**Issue by Profpatsch** [nix-rust/nix#1038]
> This probably needs a decision before 1.0. My suggestion: Either close this issue and leave the name, or rename the project. Just ignoring the issue doesn't make it go away. :/
>
> _Originally posted by @tbu- in https://github.com/nix-rust/nix/issues/76#issuecomment-93958848_

Now, two years later and before 1.0 of this project, it is time to bring this up again.

The [Nix package manager](https://github.com/NixOS/nix) has 6.5k commits from about 200 contributors and is used as a base of operations by thousands of developers and multiple dozens of companies.

The [Nix packages collection](https://github.com/NixOS/nixpkgs/) has 175k commits from about 2000 contributors, is [on par with APT-based distributions](https://repology.org/repositories/graphs) when it comes to the numbers of packages, and even beats most other distributions when it comes to the numbers of up-to-date packages.

We have seen increased euphoria in the nix community to embrace Rust for new tooling, for example [our CI](https://github.com/NixOS/ofborg) is written in Rust, and main contributors said they would use Rust (instead of C++) for future tooling efforts. This means `crates.io` is going to see an influx of crates containing `nix` in their name, most of them from/for the package manager I assume.

**Comment by asomers** [comment]
Name collisions are unfortunate.  But renaming Nix to avoid conflicts with NixOS is, at the very least, premature because I can't find a single NixOS-related package in crates.io.  Nix, OTOH, is a very popular crate.

It has been suggested to split Nix up into a number of smaller packages.  If we ever do that, then we could discuss renaming Nix at the same time.  But nobody is seriously working on that.
See https://github.com/nix-rust/nix/issues/190 .

**Comment by aszlig** [comment]
@asomers: Just bumped into that again, looking for Nix (**not** `*nix`, the package manager) bindings. Is it at least possible to give it a more distinctive synopsis to make sure it's not about bindings for the Nix package manager?

**Comment by asomers** [comment]
You mean like in the Cargo description?  What would you suggest?
