### ISSUE TITLE
impl CMsgBuffer for Vec<u8> allows underaligned pointer

### ISSUE THREAD

**Issue by nagisa** [nix-rust/nix#1040]
According to the `CMsgSpace` implementation, the buffer is expected to be, at times, aligned to `u32` or `size_t`. The implementation of `impl CMsgBuffer for Vec<u8>` may allow passing in a buffer that is not sufficiently aligned.

**Comment by asomers** [comment]
Yep.  That's why `CmsgSpace` is deprecated in the master branch.

**Comment by nagisa** [comment]
I’m not following. I mean that it is possible, and valid, to construct a `Vec<u8>` that is 1-aligned, which may be less than what is required, making "safe" code like following unsound:

```
let cmsg_buffer = Vec::with_capacity(42); // pointer is only guaranteed to be 1-aligned.
nix::recvmsg(..., cmsg_buffer, ...);
```

**Comment by asomers** [comment]
That's right.  And there's no way to fix the problem using the old API.  That's why `CmsgSpace::new` is deprecated.  It's replacement, `cmsg_space!`, fixes the alignment problem (and other problems, too).

**Comment by nagisa** [comment]
What I think is happening is that we are talking about the alignment requirement in two different directions, and I’m not talking about `CmsgSpace` at all. Lets step back a little and do it step-by-step.

#### Does the `recvmsg(3p)` require the `msg_control` buffer pointer to be aligned and if so to what alignment?

I believe that it is required to be aligned to `std::align_of::<cmsghdr>()`. In C code that is achieved with code along the lines of:

```c
// taken from `cmsg(3)` manpage
union {
    uint8_t buf[CMSG_SPACE(sizeof(myfds))];
    struct cmsghdr align;
} u;
// ...
msg.msg_control = u.buf;
msg.msg_controllen = sizeof(u.buf);
// ...
```

#### Is it possible to provide this pointer aligned to a lower alignment using safe rust code?

I believe that this is true, especially without using the `cmsg_space!` macro with the following code as adapted from [this test](https://github.com/nix-rust/nix/blob/master/test/sys/test_socket.rs#L888):

```rust
        // let mut space = cmsg_space!(libc::in6_pktinfo);
        let mut space = vec![0; 128];
        // `space.as_ptr()` here is not necessarily aligned to `std::align_of::<cmsghdr>()`.
        let msg = recvmsg(
            receive,
            &iovec,
            Some(&mut space),
            MsgFlags::empty(),
        ).expect("recvmsg failed");
```

#### Is it possible to provide this pointer aligned to a lower alignment using `cmsg_space!`?

Given that the expanded output of the above code snippet is an equivalent of:

```rust
        let space = {
            let space = unsafe {
                    CMSG_SPACE(mem::size_of::<libc::in6_pktinfo>() as c_uint)
            } as usize;
            let mut v = Vec::<u8>::with_capacity(space); 
            // `v.as_ptr()` is not necessarily aligned to `std::align_of::<cmsghdr>()`
            unsafe {v.set_len(space)};
            v
        };
        let msg = recvmsg(
            receive,
            &iovec,
            Some(&mut space),
            MsgFlags::empty(),
        ).expect("recvmsg failed");
```

which has the same problem as the example I provided in the section above, the logical conclusion is that it is possible to construct a under-aligned buffer as well.

#### Are there other problems with the `cmsg_space!` macro?

Yes! It allows user to access uninitialized memory without ever writing "unsafe" in their code!

```rust
let mut space = cmsg_space!(libc::in6_pktinfo);
println!("{:?}", space);
```

which is an equivalent amount of UB as

```rust
unsafe {
    let mut x = Vec::with_capacity(128);
    x.set_len(128);
    println!("{:?}", x);
}
```

#### Is any of this discussion related to the old `CmsgSpace`?

Not in this ticket, no.

---

Hopefully I managed to express my concern clearly enough.

**Comment by asomers** [comment]
> #### Does the `recvmsg(3p)` require the `msg_control` buffer pointer to be aligned and if so to what alignment?

recvmsg itself doesn't care about the alignment, but `CMSG_FIRSTHDR` does.

> #### Is it possible to provide this pointer aligned to a lower alignment using safe rust code?

Yes, it's true.  Unfortunately there's no backwards-compatible way to fix the
old Nix API.  That's why it's deprecated but not removed.  In your example, if
you had used `CmsgSpace::new` to size the `space` buffer rather than
hard-coding its size, you would've gotten a deprecation message suggesting to
use `cmsg_space!` instead.  And `CmsgSpace::new` was the only advisable way to
use the old API.  You really shouldn't be guessing the buffer size.

> #### Is it possible to provide this pointer aligned to a lower alignment using `cmsg_space!`?
 
No, because `cmsg_space!` uses a `Vec`, and `Vec` always allocates on heap, and
malloc(3) returns a pointer suitably aligned for any builtin type.  If Rust
someday implements its own allocator that doesn't have that alignment
guarantee, then we might have a problem.

> #### Are there other problems with the `cmsg_space!` macro?
> 
> Yes! It allows user to access uninitialized memory without ever writing "unsafe" in their code!

That's true!  But there's nothing wrong with it.  Uninitialized memory is only
`unsafe` to access if it could be an invalid representation of the type in
question.  In this case, the type is `u8`, so there are no invalid
representations.  Think of it as a very low-quality random number generator.

> #### Is any of this discussion related to the old `CmsgSpace`?

Uh, yes?  It was the fourth word of your OP.

**Comment by nagisa** [comment]
> recvmsg itself doesn't care about the alignment, but CMSG_FIRSTHDR does.

I see. Since `CMSG_FIRSTHDR` is not used, the issues with regards to alignment then are quite less relevant.

> You really shouldn't be guessing the buffer size.

This was done entirely to demonstrate that any arbitrary `Vec` can be used as an input rather than just the output of the `cmsg_space!` macro and that such an arbitrary vector may have an arbitrarily low pointer alignment. Sorry, if that wasn’t clear.

> malloc(3) returns a pointer suitably aligned for any builtin type. If Rust
someday implements its own allocator that doesn't have that alignment
guarantee, then we might have a problem.

[The allocator API](https://doc.rust-lang.org/stable/std/alloc/trait.Alloc.html) does not have a requirement like that. Instead it uses the `Layout` part of the API to give allocators an ability to make an informed choice about what it can and cannot do. Since the allocator crate mechanism allows switching out to any other allocator, people can and do implement and use their own allocators. This guarantee cannot be relied onto when writing code that is intended to be used in Rust.

However, if, as you said, `recvmsg` itself indeed does not care about alignment at all, then the current implementation of `recvmsg` appears to be fine.

>  Uninitialized memory is only unsafe to access if it could be an invalid representation of the type in
question. In this case, the type is u8, so there are no invalid representations. Think of it as a very low-quality random number generator.

Reading uninitialized memory is UB regardless of what type it is, even if it is `u8`. The compiler is allowed to (and LLVM very much will)…  take advantage of the fact if it is made aware that such reads are taking place.

> Uh, yes? It was the fourth word of your OP.

Sorry that it wasn’t clear that `CmsgSpace` was only used as a source of information about the alignment requirement and is otherwise unrelated to the core of the issue.

---

I’m not sure maintaining API compatibility makes sense if there is a soundness issue in the library code related to the old API – in fact I believe that the users should be actively warned against using the unsound versions of the library and new versions should be released that fix the issue by replacing the API with a sound version of it.

Additionally, I think that exposing `Vec<u8>` in the public API will be a maintainability hazard. You may want to take advantage of the [MaybeUninit](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html) in the future which would likely necessitate another breaking change. For now I think the `Vec` should at least be wrapped into an opaque struct to ensure the invariants are upheld and that uninitialized memory is not exposed to arbitrary safe-looking code.
