### ISSUE TITLE
Some ptrace functions don't allow signal injection

### ISSUE THREAD

**Issue by frangio** [nix-rust/nix#1049]
From [`ptrace(2)`](https://linux.die.net/man/2/ptrace):
> After signal-delivery-stop is observed by the tracer, the tracer should restart the tracee with the call `ptrace(PTRACE_restart, pid, 0, sig)` where `PTRACE_restart` is one of the restarting ptrace requests. If `sig` is 0, then a signal is not delivered. Otherwise, the signal `sig` is delivered. This operation is called signal injection

As far as I understand, the restarting requests correspond to `cont`, `detach`, `step`, and `syscall` in the `sys::ptrace` module. `cont` and `step` allow signal injection through an `Option<Signal>` argument. `detach` and `syscall` don't have such an argument so signal injection is not possible. I think they should all have this optional signal argument.

**Comment by frangio** [comment]
Let me know if you'd be interested in a pull request.

**Comment by asomers** [comment]
Yeah, this sounds like a good feature to add.
