### ISSUE TITLE
Cargo build error ... libc imported redundantly 

### ISSUE THREAD

**Issue by jlb6740** [nix-rust/nix#1053]
Hi .. I just checked out a copy but immediately ran into a compilation error:

> jlbirch@jlb6740:~/github/nix$ cargo build
>     Updating crates.io index
>     Updating git repository `https://github.com/rust-lang/libc`
>    Compiling libc v0.2.54 (https://github.com/rust-lang/libc#6bc42d40)
>    Compiling nix v0.13.0 (/home/jlbirch/github/nix)
>    Compiling void v1.0.2
>    Compiling cfg-if v0.1.9
>    Compiling bitflags v1.0.4
> error: the item `libc` is imported redundantly
>   --> src/mount.rs:64:9
>    |
> 2  | use libc;
>    |     ---- the item `libc` is already imported here
> ...
> 64 |     use libc;
>    |         ^^^^
>    |
> note: lint level defined here
>   --> src/lib.rs:13:9
>    |
> 13 | #![deny(unused)]
>    |         ^^^^^^
>    = note: #[deny(unused_imports)] implied by #[deny(unused)]
> 
> error: aborting due to previous error
> 
> error: Could not compile `nix`.
> 
> To learn more, run the command again with --verbose.

I don't see where this use at either line 2 or 64 was added recently so I assume this used to be valid syntax? Any pointers on compiling?

**Comment by asomers** [comment]
I haven't seen that before. What os and toolchain are you using?

**Comment by jlb6740** [comment]
Hi .. I am using:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

My toolchain is:

> Default host: x86_64-unknown-linux-gnu
> 
> installed toolchains
> --------------------
> 
> stable-x86_64-unknown-linux-gnu
> nightly-x86_64-unknown-linux-gnu (default)
> 
> installed targets for active toolchain
> --------------------------------------
> 
> wasm32-unknown-unknown
> wasm32-unknown-wasi
> x86_64-unknown-linux-gnu
> 
> active toolchain
> ----------------
> 
> nightly-x86_64-unknown-linux-gnu (default)
> rustc 1.36.0-nightly (08bfe1612 2019-05-02)

**Comment by asomers** [comment]
I guess this is new behavior in the latest nightly compiler.  I'll fix it.

**Comment by jlb6740** [comment]
Hi .. yes, I think it is new. I see the same error reported recently for other projects:

https://github.com/paritytech/parity-ethereum/issues/10594
https://github.com/rust-lang/rust/issues/60484#issuecomment-489072191

Though I don't see a ton of reports nor the rust change where this would have broken this current code. Was looking for an attribute or compiler flag to ignore this but couldn't find one. For now I just commented out line 64. Thanks for the response.

**Comment by asomers** [comment]
Fixed by PR #1054
