### ISSUE TITLE
Release 0.14.0

### ISSUE THREAD

**Issue by ryankurte** [nix-rust/nix#1060]
hi there, it'd be super useful to have another release (particularly including the libc export fixes #1055) so things work on ARM again.

thanks,

ryan

**Comment by asomers** [comment]
Yep, sure would be nice.

**Comment by ryankurte** [comment]
🤣 is there anything blocking this happening or could i just open a PR with a version bump?

**Comment by asomers** [comment]
In progress as #1061 .

**Comment by asomers** [comment]
Done!

**Comment by ryankurte** [comment]
thanks!
