### ISSUE TITLE
failed to initiate panic within clone child

### ISSUE THREAD

**Issue by aherrmann** [nix-rust/nix#1073]
`panic` is not working correctly within the `child` of `clone`. The following code
```
fn main() {
    let mut stack = [0u8; 1024 * 1024];
    let child = Box::new(|| {
        panic!("child");
    });
    let pid = clone(child, &mut stack, CloneFlags::empty(), Some(Signal::SIGCHLD as i32)).unwrap();
    wait::waitpid(pid, None).unwrap();
    panic!("parent");
}
```
produces the following output
```
thread 'main' panicked at 'child', src/main.rs:191:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
thread 'main' panicked at 'parent', src/main.rs:195:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Note, `fatal runtime error: failed to initiate panic`.

---

```
rustc 1.35.0 (3c235d560 2019-05-20)
libc 0.2.55
nix 0.11.0
```

**Comment by asomers** [comment]
`clone(2)` is notoriously difficult to use correctly.  This isn't a Nix problem.  In order to fix it, you're going to need to grok how Linux processes work, what clone does, and how Rust prints a backtrace.

**Comment by aherrmann** [comment]
> In order to fix it, you're going to need to grok [...] **how Rust prints a backtrace**.

Indeed, I've been digging in that direction already. Though, sadly with little success so far. I found this in the context of a side-project where I can live with broken backtraces. Nonetheless, I thought it would be worth raising an issue. It seems likely that others will encounter this problem as well.

> `clone(2)` is notoriously difficult to use correctly. This isn't a Nix problem.

I'm pretty new to Rust, so please forgive me if I'm misreading. But, quoting this project's README:

> For many system APIs, Nix provides a safe alternative to the unsafe APIs exposed by the libc crate. This is done by wrapping the libc functionality with types/abstractions that enforce legal/safe usage.

`clone` is not marked as `unsafe` and there are no documented caveats. If nothing else, it seems to me that `clone` should be marked as `unsafe`, or at least document the Rust specific caveats. I.e. broken backtraces, possibly other aspects of the runtime.

It could be argued that a *safe* `clone` wrapper should shield users from such difficulties. At least those related to the language runtime.

**Comment by aherrmann** [comment]
I've played with this a bit and `catch_unwind` lead me down an interesting path. I've come up with the following implementation of `clone` (based on that in `nix`) that handles panic better. (No more "failed to initiate panic" and this also removed a segfault I was getting after a panic before). This `clone` is still wildly unsafe, though. With `CLONE_VM` it segfaults, otherwise it leaks parent's memory in the child, and probably lots of other issues that I'm not aware of. Anyway, thought I'd share it in case it's useful to anyone.

```
use libc::{c_int, c_void};
use nix::{errno::Errno, sched, sys::signal::Signal, unistd::Pid, Result as NixResult};
use std::panic;

pub fn clone<F>(
    callback: F,
    stack: &mut [u8],
    flags: sched::CloneFlags,
    signal: Option<Signal>,
) -> NixResult<Pid>
where
    F: FnOnce() -> isize + panic::UnwindSafe,
{
    extern "C" fn c_callback<F>(optf: *mut c_void) -> c_int
    where
        F: FnOnce() -> isize + panic::UnwindSafe,
    {
        let optf = optf as *mut Option<F>;
        let optf = unsafe { &mut *optf };
        // Option::take is used to avoid "cannot move out of borrowed content".
        match optf.take() {
            Some(f) => {
                // catch_unwind will print the panic message and optionally the backtrace.
                let r = panic::catch_unwind(|| f());
                // Return exit code 1 on panic.
                r.unwrap_or(1) as c_int
            }
            None => unreachable!(),
        }
    }
    let combined = flags.bits() | signal.map(|s| s as c_int).unwrap_or(0);
    let res = unsafe {
        let ptr = stack.as_mut_ptr().offset(stack.len() as isize);
        let ptr_aligned = ptr.offset((ptr as usize % 16) as isize * -1);
        libc::clone(
            c_callback::<F>,
            ptr_aligned as *mut c_void,
            combined,
            &mut Some(callback) as *mut _ as *mut c_void,
        )
    };
    Errno::result(res).map(Pid::from_raw)
}
```

**Comment by asomers** [comment]
> `clone` is not marked as `unsafe` and there are no documented caveats. If nothing else, it seems to me that `clone` should be marked as `unsafe`, or at least document the Rust specific caveats. I.e. broken backtraces, possibly other aspects of the runtime.

This is actually a matter of some disagreement within the Rust community.  Rust's safeness isn't a shield from the operating system doing weird things.  For example, on Linux if you open `/dev/mem` and scribble on it, your program will crash.  But that doesn't mean that `open` and `read` should be `unsafe`.  `clone` is in a similar boat.

> 
> It could be argued that a _safe_ `clone` wrapper should shield users from such difficulties. At least those related to the language runtime.

There already are safe wrappers of `clone`.  They're called `fork` and `pthread_create`.  If neither of those satisfies your needs, then you're probably doing something pretty unusual.
