### ISSUE TITLE
Doesn't support x86_64-sun-solaris

### ISSUE THREAD

**Issue by MarcoZanrosso** [nix-rust/nix#1086]
please fix this library as soon as possible for x86_64-sun-solaris.
![Schermata 2019-06-12 alle 17 02 29](https://user-images.githubusercontent.com/51322105/59362521-e5d06880-8d33-11e9-9a20-9efd54340b4c.jpg)

**Comment by asomers** [comment]
Would you be willing to file a PR to add Solaris support?  None of the regular Nix developers use Solaris.

**Comment by MarcoZanrosso** [comment]
sorry, i'm a newbie in rust language.

**Comment by asomers** [comment]
Then I'm afraid that I'm going to have to close the issue.  We're all volunteers here, and porting the crate to a new OS is something that the other maintainers and I are unlikely to do ourselves.  Nix thrives on user contributions, as you can see from our contributors count of 178.  If you do try to port it yourself, feel free to open a PR; I'll gladly review it.
