### ISSUE TITLE
exec family functions take CString instead of &CStr

### ISSUE THREAD

**Issue by canndrew** [nix-rust/nix#1093]
For example, the signature of `execve` is:

    pub fn execve(path: &CString, args: &[CString], env: &[CString]) -> Result<Void>

Surely there's no point in taking a `&CString` as opposed to a `&CStr`, right? And couldn't the slices just contain `&CStr`s since it's not possible to move out of a slice anyway?

**Comment by asomers** [comment]
Yep, there's very rarely a reason for a `&CString`.  Would you care to submit a PR to fix it?
