### ISSUE TITLE
cmsg_space still seems to be unsound

### ISSUE THREAD

**Issue by MikailBag** [nix-rust/nix#1142]
I'm confused by this line: https://docs.rs/nix/0.15.0/src/nix/sys/socket/mod.rs.html#316
You create Vec of u8's, and then set_len to capacity.
This code works on stable, but nightly Miri rejects it: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d86164c2556514deed58418394277481
Note that macro returns vector, so user can e.g. dbg! it, or observe it contents in any other way.

AFAIK, whether primitive types can have uninitialized bits is topic of active discussion, and such usage probably should be avoided

**Comment by asomers** [comment]
Yep, the rules on uninitialized memory keep getting stricter.  The best way to solve this particular problem would probably be to:
1) Remove `CmsgSpace`.  There's already been a full release with it deprecated, so we can remove it now.
2) Remove the `CmsgBuffer` trait, and make `recvmsg`'s `cmsg_buffer` argument be of type `Vec`.
3) Add a `set_len` to `recvmsg`'s ok path.

However, there are other functions that need to be changed to, to work in the world of `MaybeUninit`.  `recvmsg`'s `iov` argument, for one, cannot currently be used that way.
