### ISSUE TITLE
Linux capabilities

### ISSUE THREAD

**Issue by Isawan** [nix-rust/nix#1180]
I'd like to know if there's any existing work on providing a wrapper for linux capabilities? I was about to start work on a patch if there isn't.

**Comment by asomers** [comment]
Do you have a specific function in mind?  Just check the open issues and PRs to see if there's any existing work; we maintainers aren't working on it secretly.

**Comment by asomers** [comment]
Is https://docs.rs/caps/0.3.4/caps/ what you're looking for?

**Comment by Isawan** [comment]
Yes, that's exactly it. Thanks.
