### ISSUE TITLE
Use #[non_exhaustive] after updating MSRV to 1.40.0

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#1182]
The `#[non_exhaustive]` attribute, introduced by Rust 1.40.0, should be used for most enums that come from C, since new values could be added by any release.  This attribute isn't valuable enough to justify a MSRV bump by itself.  But we should still make use of it whenever we update the MSRV for any other reason.

**Comment by lucab** [comment]
For reference, as of nix 0.8.0 the current MSRV is already at 1.41.0 since https://github.com/nix-rust/nix/pull/1440.
