### ISSUE TITLE
Huge page size support in mmap / sys::mman

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [nix-rust/nix#1194]
Since linux 3.8 there are additional flags to mmap (~~and possibly madvise~~ not madvise) that allow specifying what size of huge page should be used.

http://man7.org/linux/man-pages/man2/mmap.2.html

How could support for those be added to nix ?

**Comment by asomers** [comment]
First you'll need to add the new symbols to libc, and make a PR to github.com/rust-lang/libc .  Then you can add them to Nix.

**Comment by GuillaumeDIDIER** [comment]
That mean I probably need to open an issue at libc (or unsolicited PR right away) ?

**Comment by GuillaumeDIDIER** [comment]
The PR got merged at libc. How do I proceed now, should I override the libc version to start working on a PR (and update that back when the next release gets out) ? Or should I wait for the next libc release ?

**Comment by asomers** [comment]
Yes.  You can set Nix's libc version to use a git hash for now.

**Comment by GuillaumeDIDIER** [comment]
Hmm, I need to add a bunch of flags to mmap, but this is an exclusive set of values on several flag bits. (That also only make sense if another flag is set). Is this something where I should declare a third type and add an extra parameter to mmap, or can this be simply added in the bit flag without causing a mess ?
