### ISSUE TITLE
Support for ttyname and ttyname_r

### ISSUE THREAD

**Issue by Artoria2e5** [nix-rust/nix#1204]
POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/functions/ttyname.html

```Rust
pub unsafe fn ttyname(fd: RawFd) -> Result<String>;
pub fn ttyname_r(fd: RawFd) -> Result<String>;
```

`ttyname` and `ttyname_r` are basically `ptsname` that works on any TTY fds, not just those associated with a PTY slave device. The latter is a pretty useful portable alternative to `ptsname_r`.

The functions are found on basically every nix platform; see `libc` crate for details about a macOS compliance fix it has.

**Comment by asomers** [comment]
Nix operates on a "patches welcome" basis.  Us maintainers are basically just curators.  Do you care to submit a patch?
