### ISSUE TITLE
Can't zero-initialize SockType

### ISSUE THREAD

**Issue by srikwit** [nix-rust/nix#1212]
Hi Team,

I have observed the following two tests to fail on my machine:
```
test sys::socket::sockopt::test::is_socket_type_dgram ... FAILED
test sys::socket::sockopt::test::is_socket_type_unix ... FAILED
```

Please let me know how I can help troubleshoot them.

**Comment by asomers** [comment]
Please tell us your operating system, kernel version, and Rust toolchain version.  And paste the complete error message.

**Comment by srikwit** [comment]
OS: Debian GNU/Linux 10 (buster)
Kernel version: 4.19.0-8-amd64
Rust toolchain: rustc 1.44.0-nightly (f509b26a7 2020-03-18)

Error message from `cargo test`:
```
failures:

---- sys::socket::sockopt::test::is_socket_type_dgram stdout ----
thread 'sys::socket::sockopt::test::is_socket_type_dgram' panicked at 'attempted to zero-initialize type `sys::socket::SockType`, which is invalid', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/mem/mod.rs:500:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- sys::socket::sockopt::test::is_socket_type_unix stdout ----
thread 'sys::socket::sockopt::test::is_socket_type_unix' panicked at 'attempted to zero-initialize type `sys::socket::SockType`, which is invalid', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/mem/mod.rs:500:5


failures:
    sys::socket::sockopt::test::is_socket_type_dgram
    sys::socket::sockopt::test::is_socket_type_unix

test result: FAILED. 41 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out

```

**Comment by asomers** [comment]
This is a new error introduced by the latest nightly compiler. It really should just be a warning so as not to break existing code.  But I'm already working on a fix.

**Comment by asomers** [comment]
Also, if this remains an error by the time that 1.44.0 goes stable, then we'll need to backport the fix to all currently used Nix releases.
