### ISSUE TITLE
ptrace::syscall unexpected behavior

### ISSUE THREAD

**Issue by jabedude** [nix-rust/nix#1223]
I am making a small utility for traicing specific syscalls using this crates ptrace wrappers. 

I am doing the following: attaching to a tracee with ptrace::attach, then ptrace::syscall to continue until the tracee executes a syscall,  waitpid(tracee_pid) to wait for the tracee to enter a stopped state, and lastly ptrace::getregs to examine the syscall parameters. According to the man pages, the tracee should be in a stopped state until PTRACE_CONTINUED, PTRACE_SYSCALL again, or another operation that resumes execution. However that is not the behavior I am observing. 

```rust
fn trace(pid: Pid) -> Result<()> {
    ptrace::attach(pid)?;
    eprintln!("pid attached !");

    loop {
        // Enter syscall
        ptrace::syscall(pid, None)?;
        waitpid(pid, None)?;
        let regs = ptrace::getregs(pid)?;
        let syscall_num = regs.orig_rax;
        eprintln!("Intercepted syscall {}!", syscall_num);
        // Tracee should still be paused here, and the subsequent
        // ptrace::syscall should yield the return value of the exiting system call.
    }
    Ok(())
}
```

**Comment by asomers** [comment]
This sounds to me more like a ptrace usage problem than a Nix bug.  You'll probably have more luck asking on a ptrace or OS-focused list.  My best advice is to check your thread count.  Is the target process single- or multi- threaded?  Under Linux, ptrace will only stop a single thread at a time.

**Comment by jabedude** [comment]
Sure thing, I'll close this and ask somewhere else. The target is single threaded.
