### ISSUE TITLE
Socket implementation is incorrect

### ISSUE THREAD

**Issue by alvardes** [nix-rust/nix#1226]
The current socket implementation doesn't account for the protocol parameter needing to be transformed for specific SockTypes to network endianness. (e.g.: ethernet raw sockets need the protocol to be in network endiannes).

More information:
https://stackoverflow.com/questions/38925417/why-use-htons-to-specify-protocol-when-creating-packet-socket

On little endian systems like x86 and such the raw sockets will be incorrect.

**Comment by asomers** [comment]
Could you please be more specific?  If you think you've found a bug, try to clearly describe what it is, with steps to reproduce if possible.  "Socket implementation is incorrect" is hopelessly vague.
