### ISSUE TITLE
PollFd should be repr(transparent)

### ISSUE THREAD

**Issue by eduardosm** [nix-rust/nix#1241]
Given the way `PollFd` is passed to the FFI `poll` function (`.as_mut_ptr() as *mut libc::pollfd`), the struct should be `repr(transparent)`, so Rust will guarantee that `PollFd` has the same layout as `libc::pollfd`.

**Comment by asomers** [comment]
Yep, you're right!  Nix predates `repr(transparent)`, so there probably other places that need to be updated, too.
