### ISSUE TITLE
Implement ptrace PTRACE_SYSEMU request

### ISSUE THREAD

**Issue by jabedude** [nix-rust/nix#1249]
Tracking issue for adding the PTRACE_SYSEMU request to the `ptrace` module. 

Waiting for [this PR](https://github.com/rust-lang/libc/pull/1774) to land in `libc`.

**Comment by asomers** [comment]
Nix operates on a "patches welcome" basis.  Would you care to submit a patch to add this functionality?

**Comment by jabedude** [comment]
Of course! I'm working on it now. I was just creating this issue to remind myself that we needed the libc PR to land first :)
