### ISSUE TITLE
Missing EventFlag bitflags on OpenBSD (EV_DISPATCH, EV_RECEIPT)

### ISSUE THREAD

**Issue by nickpelone** [nix-rust/nix#1251]
Hey there!

[OpenBSD has been excluded from `EV_DISPATCH` and `EV_RECEIPT` for a while now](https://github.com/nix-rust/nix/blob/master/src/sys/event.rs#L93), but they have since landed in OpenBSD (A while ago, pretty sure.)

These being excluded on that platform prevent crates such as `smol` from building (related issue: https://github.com/stjepang/smol/issues/146)

Any way these can be added for `target_os = "openbsd"`?

Thanks for your time.

**Comment by asomers** [comment]
Sure, just submit a PR.  Note that Nix doesn't build for OpenBSD in CI; so we rely on our users to catch even basic build problems.

**Comment by qbit** [comment]
fwiw, sr.ht offers OpenBSD CI - there are even [convenient dispatchers](https://man.sr.ht/dispatch.sr.ht/) for building from Github commits!

**Comment by asomers** [comment]
Yes.  However, sr.ht isn't free, and none of Nix's maintainers are OpenBSD users, so we haven't stumped up for it.

**Comment by nickpelone** [comment]
I have opened https://github.com/nix-rust/nix/pull/1252. Thanks!

**Comment by asomers** [comment]
My interpretation is that it's free for evaluation purposes, but you're kind of a jerk if you abuse the privilege.  Am I wrong?

**Comment by mahkoh** [comment]
I believe you are wrong.
