### ISSUE TITLE
process information from PID (question/maybe-feature)

### ISSUE THREAD

**Issue by xd009642** [nix-rust/nix#1256]
Just wondering if there's a way to get the executable path for a given PID through nix or posix APIs and whether that could be added to this crate? I didn't find anything in docs.rs so sorry if it already exists. I also haven't found anything when googling about OS API calls to achieve the same thing, so getting used to the idea I may just have to parse /proc/${PID} to find it...

**Comment by asomers** [comment]
No, Nix doesn't currently have that capability, and there's no standard way to grt it.  If you're using Linux, procfs is your best bet.  On FreeBSD, use libprocstat(3).  Offhand I don't know about other operating systems.

**Comment by xd009642** [comment]
Okay I'll go down that route then, thanks :+1:
