### ISSUE TITLE
Add support for unistd's rmdir call

### ISSUE THREAD

**Issue by dkder3k** [nix-rust/nix#1269]
At the moment unlink and unlinkat are supported by nix, but I can't find any support for rmdir call to remove dirs.
According to [unlink docs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/unlink.html):
> The path argument shall not name a directory unless the process has appropriate privileges and the implementation supports using unlink() on directories.

So mostly rmdir should be used for directory removal.
I suppose something like this should be added to unistd.rs:
```
pub fn rmdir<P: ?Sized + NixPath>(path: &P) -> nix::Result<()> {
    let res = path.with_nix_path(|cstr| {
        unsafe {
            libc::rmdir(cstr.as_ptr())
        }
    })?;
    Errno::result(res).map(drop)
}
```
I can submit such PR if there are no objections

**Comment by asomers** [comment]
Just one question: what advantage does nix::unistd::rmdir have over https://doc.rust-lang.org/std/fs/fn.remove_dir.html ?  If the standard library suffices, then we don't need to duplicate its functionality in Nix.

**Comment by dkder3k** [comment]
As I can see there is no any advantage, so PR and issue could be closed I suppose.
And if Nix shouldn't duplicate standard library then [unlink](https://github.com/nix-rust/nix/blob/master/src/unistd.rs#L1194) must be removed as well because it duplicates [remove_file](https://doc.rust-lang.org/std/fs/fn.remove_file.html)
