### ISSUE TITLE
v0.17.0 fails to build on MacOS

### ISSUE THREAD

**Issue by keepsimple1** [nix-rust/nix#1273]
Rust version:  1.44.0
OS: macOS Catalina 10.15.5 
nix version: tag v0.17.0
Error: 
```
error: unnecessary parentheses around assigned value
  --> src/sys/ioctl/bsd.rs:17:39
   |
17 |     pub const INOUT: ioctl_num_type = (IN|OUT);
   |                                       ^^^^^^^^ help: remove these parentheses
   |
```
Looks like this error has been fixed in [this commit](https://github.com/nix-rust/nix/commit/5c3fbbbdf129d714c98ce45fb96f96ada1f5522a) after the release v0.17.0.   Can this fix be ported back to v0.17.0 ?  or,  is there a v0.18.0 coming out soon? Thanks.

**Comment by asomers** [comment]
Yeah, we should release v0.18.0 soon.  I'll get working on that.  In the meantime, you can suppress that error by either using an older compiler or doing:
```rust
#[allow(unused_parens)]
```

**Comment by asomers** [comment]
Release 0.18.0 is published.  I suggest you upgrade to that.
