### ISSUE TITLE
Add wrapper for libc::mremap

### ISSUE THREAD

**Issue by sporksmith** [nix-rust/nix#1295]
I need this in https://github.com/shadow/shadow. Happy to take a stab at it :)

**Comment by asomers** [comment]
Go ahead.  Nix lives on the contributions of its users.

**Comment by sporksmith** [comment]
@asomers - Thanks! #1306 is ready for review. CI is still running at the moment but the last commit just reverts it to an earlier state that already passed. (I'd tried enabling the mremap wrapper on Android, which failed CI, and then reverted that change)
