### ISSUE TITLE
Link to kernel documentation of ioctl numbers is broken

### ISSUE THREAD

**Issue by nharward** [nix-rust/nix#1309]
The link to the Linux kernel list of ioctl numbers appears to have moved, at least as of the time this issue was created (_latest_ kernel is `5.8.14`).

Existing (broken) link from `0.18.0` documentation on docs.rs: `https://elixir.bootlin.com/linux/latest/source/Documentation/ioctl/ioctl-number.rst`

New value: `https://elixir.bootlin.com/linux/latest/source/Documentation/userspace-api/ioctl/ioctl-number.rst`

**Comment by ritzk** [comment]
This is resolved - https://github.com/nix-rust/nix/commit/bcb7b4243537b0d98d2ce01e7277c8be4fa01072 .
