### ISSUE TITLE
kill -0 for verifying that a process exists

### ISSUE THREAD

**Issue by enaut** [nix-rust/nix#1326]
I'm reimplementing a file lock for passwd and in the original implementation kill is used with the signal 0 to verify the processes existence without sending any signal with effect. Is something like this possible with this crate?

[source mentioned](https://github.com/shadow-maint/shadow/blob/f8642a1986a44e661cf526505ccca26c37fd10d7/lib/commonio.c#L214-#L223)

**Comment by Kixunil** [comment]
Pid files have tons of footguns when it comes to concurrency and robustness. I highly recommend replacing them with empty file and using file locks on them. The best thing about them is they get automatically cleaned up by OS when the process exits, so those "PID doesn't exist" cases can not happen outside of a small chance that the process dies between another process checking the lock file and acting on the information.

See `man 2 fcnt` - Advisory record locking.

**Comment by enaut** [comment]
Thing is I want to lock the passwd files - and they are locked by pidfile by every other app. I know it is not the optimum but its compatible.

**Comment by Kixunil** [comment]
Ah, this makes sense then. I believe it should be possible to do using `nix`.

**Comment by asomers** [comment]
Yeah, just do `nix::sys::kill(my_pid, None)`.
