### ISSUE TITLE
Build failure on illumos and Solaris due to TCP_KEEPCNT and TCP_KEEPINTVL

### ISSUE THREAD

**Issue by jasonbking** [nix-rust/nix#1328]
The latest nix crate fails to build on illumos based systems (and almost certainly Solaris systems) since both the `TCP_KEEPCNT` and `TCP_KEEPINTVL` TCP options aren't defined in the libc crate.

Both platforms support those two options, and I've created a rust-lang/libc#1964 to address that, but there's a bit of a chicken-and-egg problem. I'm not sure how frequently the libc patch versions are bumped -- so even after the PR is merged, it may be some undetermined amount of time before those new values are reflected in a new libc version (and thus fix the nix nix build for those targets). Would it be worth submitting a small PR to temporarily exclude those two options for the illumos and Solaris targets until an updated new libc crate is released?

Currently illumos distress are having to maintain local patches (for this and some other missing support for those targets I'd like to upstream as well) to work around the problem, so we'd like of course to be able to stop doing that.

**Comment by SteveLauC** [comment]
Thanks for adding them to the libc crate, this issue can be closed now as the libc we are using now has that patch included
