### ISSUE TITLE
Support for `personality(2)`?

### ISSUE THREAD

**Issue by woodruffw** [nix-rust/nix#1330]
Hi there! Thanks a ton for these bindings, they're a pleasure to use.

Would the nix team be interested in support for the (Linux-specific) [`personality(2)`](https://man7.org/linux/man-pages/man2/personality.2.html) syscall? It's currently supported in the `libc` crate but doesn't have higher level bindings to turn the `persona` argument into a `bitflags!` enum or to map the return value into a `Result`.

It's something I'm interested in (and capable of) implementing, if desired.

**Comment by asomers** [comment]
What's the main use?  It seems to me like this should only be done by the ELF loader.

**Comment by woodruffw** [comment]
I don't think the current dynamic linker/loader on Linux actually calls `personality(2)`, although it may have in the past. Here are a few uses that I can think of:

* Implementing a `setarch(8)`-style utility in Rust. 

* Allowing more fine-grained process spawning. This is my current use case: I want to disable ASLR on a few specific child processes for unit testing purposes.

* Exposing an `exec`-safe piece of process state -- [KRF](https://github.com/trailofbits/krf) currently uses `personality(2)` to signal to the kernel that a particular tree of processes should be instrumented. It's useful to be able to do that outside of the dynamic linker.

**Comment by woodruffw** [comment]
:tada:
