### ISSUE TITLE
Support for `getpeereid(3)`

### ISSUE THREAD

**Issue by woodruffw** [nix-rust/nix#1339]
macOS and most of the BSDs have a `getpeereid(3)` library routine, which can be used to retrieve the effective UID and GID for a given Unix domain socket.

This roughly mirrors the functionality provided by `getsockopt(2)` + `SO_PEERCRED` on Linux (minus the PID), which the `nix` crate already supports.

I have the bandwidth and ability to implement this, if desired.

**Comment by myfreeweb** [comment]
We'll need this in [zbus](https://gitlab.freedesktop.org/zeenix/zbus/-/merge_requests/185), so you have a consumer already!

---

Side note, OpenBSD also supports `SO_PEERCRED` with minor differences ([usage example](https://gitlab.freedesktop.org/dbus/dbus/-/blob/2ef39181cfe1443c349500740855bf86f195f540/dbus/dbus-sysdeps-unix.c#L2275-2311)); FreeBSD supports `LOCAL_PEERCRED` but gained the `pid` field very recently; NetBSD has `LOCAL_PEEREID`; Solaris/illumos(?) has `getpeerucred`. Would be nice to also get all these mechanisms in here eventually…

**Comment by woodruffw** [comment]
Fantastic. I have https://github.com/rust-lang/rust/pull/79387 pending on Rust itself to improve the nightly-only `UCred` API, which should eventually handle those minor differences on the BSDs as well. But yeah, it would certainly good to have them exposed independently in `nix` as well.

**Comment by woodruffw** [comment]
Okay, #1342 has the wrapper.
