### ISSUE TITLE
Add AT_FDCWD to AtFlags

### ISSUE THREAD

**Issue by Diegovsky** [nix-rust/nix#1340]
I'm writing a tracer that gets every syscalls and logs them. To do this, I needed to check wheter *at function family's fd argument equals AT_FDCWD. I'm not sure if this behaviour is specific to Linux, but I think it might be a good addition to AtFlags, making it more robust.

**Comment by cemeyer** [comment]
`AT_FDCWD` isn't a flag like `AtFlags` values; it's a sentinel value.  Just use `libc::AT_FDCWD`?

**Comment by Diegovsky** [comment]
Ok, thanks :)
