### ISSUE TITLE
aio_suspend returns EINVAL on OSX in CI

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#1361]
After working fine for years, sys::test_aio::test_aio_suspend has begun to reliably fail in CI, when run on OSX.  The trigger seems to be the recent MSRV upgrade to 1.40.0.  Unfortunately, none of the current Nix maintainers have access to a Mac, so we aren't able to debug this one.  Help wanted.
```
---- sys::test_aio::test_aio_suspend stdout ----
thread 'sys::test_aio::test_aio_suspend' panicked at 'aio_suspend returned Sys(EINVAL)', test/sys/test_aio.rs:170:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by SteveLauC** [comment]
Seems that this issue has been solved, close as completed in https://github.com/nix-rust/nix/pull/2262, but if it still occurs in the future, we can reopen it at any time.
