### ISSUE TITLE
Publish releases on Github as well

### ISSUE THREAD

**Issue by zeenix** [nix-rust/nix#1369]
According to Github the latest release was in 2017, which isn't the case. Apart from the discrepancy with crates.io, it also gives the impression of an unmaintained crate if someone only judges by GH releases. It'd be best if maintainers added changelog/notes to the tags to mark them as releases. Providing release notes is a best practice any way.

Just a suggestion for doing things better. Feel free to ignore. :)

**Comment by asomers** [comment]
We already tag releases.  Why should we publish them on Github?  Does anybody download Rust releases from Github anymore?

**Comment by zeenix** [comment]
> We already tag releases.

Just a tag, doesn't count as a release by Github. On the main page of this repo, you'll find a very old release as the latest release.

> Why should we publish them on Github? Does anybody download Rust releases from Github anymore?

No, it's not about the download/release artifacts but presenting information. AFAIK, there are no release notes on crates.io. I think I provided the reasons you should do this in the description of this MR.

If you don't see the point, feel free to close this issue and ignore me. :)

**Comment by myfreeweb** [comment]
Tags do show up on https://github.com/nix-rust/nix/releases

The problem is that you've done at least one "proper release publish" thing in the past, and it takes priority on the main page. If it's possible to delete, it should be deleted.

**Comment by asomers** [comment]
I deleted the only Github Release.  The tags are still there.

**Comment by zeenix** [comment]
> I deleted the only Github Release. The tags are still there.

Great so there is no confusion at least. :+1:
