### ISSUE TITLE
Build failure on mips64-unknown-linux-muslabi64

### ISSUE THREAD

**Issue by FH0** [nix-rust/nix#1370]
mips/arm/aarch64/x86_64 are ok, but mips64 failed
`cargo build --release --target=mips64-unknown-linux-muslabi64`
![image](https://user-images.githubusercontent.com/32861476/103747702-03fc6880-503e-11eb-9562-77ea6d7b4e2b.png)

**Comment by asomers** [comment]
That symbol actually is defined in musl, so this is a bug for rust-lang/libc.  You should open an issue or PR there.
