### ISSUE TITLE
Possible UB since preadv accepts &[IoVec<&mut [u8]>] 

### ISSUE THREAD

**Issue by 4lDO2** [nix-rust/nix#1371]
In Rust, attempting to obtain a mutable reference from an immutable reference is immediately Undefined Behavior, unless UnsafeCell is used, which includes mutable references behind immutable references (`&&mut [u8]`, or in this case `&[IoVec<&mut [u8]>]`). This has also been extended to regular pointers, that originate from stack variables or regular references, now that Stacked Borrows is about to get integrated into the compiler. While the Rust compiler may not be ever able to detect UB within preadv, as syscalls are opaque and could have other side-effects, it could theoretically optimize subsequent code under the assumption that the iovec is aliased, and hence cannot allow its data to be mutated for the lifetime of the system call. Not only that, but this behavior could also change arbitrarily in future compiler versions.

What I suggest we do to fix this potential issue, is to revert the function signature in `preadv` (changed in https://github.com/nix-rust/nix/pull/914) to take `&mut [IoVec<&mut [u8]>]`, which is something `libstd` already does, as well as the regular `readv` call in `sys::uio`. Additionally, we will need to change the implementations of `readv` and `preadv` to take `as_mut_ptr` rather than `as_ptr`, since Rust allows no mutation from any pointer coming from `as_ptr` (which borrows &self immutably).

**Comment by sporksmith** [comment]
Came here to file the same issue for `process_vm_readv`, which has the same problem. IANA expert, but I started digging into this when I was writing a wrapper for `process_vm_readv`, and found I couldn't have it take `&&mut [u8]` without using unsafe to coerce pointers, and doing so would cause Miri to flag it as UB.

The language docs on interior mutability seem pretty clear that the current implementation is UB. https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#interior-mutability

**Comment by sporksmith** [comment]
Example in the Rust playground that (I think) implements the same behavior as these methods. It works with `unsafe`, but don't pass the Miri checks. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8cb8a4507c42d86f6efd8a81d31f89d6
