### ISSUE TITLE
Add protable wrappers for the block device IOCTLs

### ISSUE THREAD

**Issue by aj-bagwell** [nix-rust/nix#1374]
Add a portable and safe way of getting things like the size of block device (e.g. USB sticks or SD cards).

Other people (#1006 & #573) have had issue using the ioctl directly so it would be nice to have a safe simple wrapper.

It should have:
- a way to get the size of a block (BLKSSZGET)
- a way to get the size of the disc in bytes (BLKGETSIZE64) 
- a way to get the number of block

It would be nice to support the other BLK* ioctls
- re-read partion table (BLKRRPART)
- discard a range of blocks (BLKDISCARD)
- zero a range of block (BLKZEROOUT)
- check if the underlying medai supports something like TRIM that zeros when a block is discarded (BLKDISCARDZEROS)

**Comment by asomers** [comment]
I think this is really beyond the scope of Nix.  We define the ioctl macros, but we shouldn't also wrap every single ioctl.  There are tons.

**Comment by posborne** [comment]
I agree with @asomers.  This is good functionality but it might make sense to have it live in its own crate which in turn depends on Nix.  The scope of nix itself would be quite large and difficult to maintain if we tried to provide more than basic safety over the lower level calls.  In addition, defining a portable API, which is a good goal in general, works against the goals of nix to safely expose the full underlying functionality of supported operating systems.

Hopefully these comments make sense.  I've personally had use of such functionality on block devices, so an abstraction like this is far from useless.  Just might need to find a different home.

**Comment by aj-bagwell** [comment]
Thanks for fast replies, I was not sure if nix was the right place, for it. I'll look into turning it into a stand alone crate.

**Comment by aj-bagwell** [comment]
Finally got round to making a [block-devs](https://docs.rs/block-devs/) crate with this code, just in case any one else is interested.
