### ISSUE TITLE
forkpty() should probably be unsafe

### ISSUE THREAD

**Issue by tavianator** [nix-rust/nix#1388]
`fork()` [is unsafe](https://docs.rs/nix/0.19.1/nix/unistd/fn.fork.html) (for good reason; you're not allowed to do much in the child if the parent was multithreaded).  OTOH, `forkpty()` [is not unsafe](https://docs.rs/nix/0.19.1/nix/pty/fn.forkpty.html) even though the same reasoning should apply.

**Comment by asomers** [comment]
Yep, you're right.  Care to submit a PR to fix it?
