### ISSUE TITLE
Support for openat2()

### ISSUE THREAD

**Issue by Serentty** [nix-rust/nix#1400]
On Linux, the recent ``openat2()`` system call provides a broader API surface than ``openat()``. However, it's not yet wrapped in GLIBC, so it would be necessary to make the system call directly. Would this be a problem in terms of maintainability and portability, or is this something that the Nix crate is already used to dealing with?

**Comment by asomers** [comment]
It's highly annoying, but not a deal-breaker.  Nix already has a few functions that do that.  Just grep Nix's codebase for `libc::syscall`.
