### ISSUE TITLE
fopen(fclose, fseek, fread) binding

### ISSUE THREAD

**Issue by szdytom** [nix-rust/nix#1412]
type: feature request

It will be really nice to have a binding over file control functions, here is a list I find out:
- [ ] fopen
- [ ] fclose
- [ ] fseek
- [ ] fread
- [ ] fwrite
- [ ] fsetpos
- [ ] fsync
- [ ] ftell
- [ ] freopen
- [ ] stdin
- [ ] stdout
- [ ] stderr

**Comment by asomers** [comment]
The standard library does a good job of buffered file I/O.  What extra utility would Nix provide if it bound these lower-level functions?

**Comment by asomers** [comment]
@szdytom do you have a good use case for why Nix needs bindings for these functions, where the standard library won't suffice?
