### ISSUE TITLE
no getregs and setregs support in aarch64

### ISSUE THREAD

**Issue by sunc-cn** [nix-rust/nix#1419]
when to support full setregs/getregs etc in aarch64

**Comment by asomers** [comment]
When somebody submits a patch for it.

**Comment by devnexen** [comment]
will try to push the struct side of things in libc for next release at least.

**Comment by irgstg** [comment]
I have implemented some in a personal project I have.
I will open PR as soon as I can.

**Comment by sgleske-ias** [comment]
@asomers said:
> When somebody submits a patch for it.

Please follow through on your comment with https://github.com/nix-rust/nix/pull/1695 ; two years seems a bit past the period for respecting a contributor's time considering how you replied to this issue.

**Comment by SteveLauC** [comment]
Well, it is unfortunate that PR didn't get reviewed for 2 years, and I am sorry about this, I plan to take a look at that PR this weekend.

> Please follow through on your comment with https://github.com/nix-rust/nix/pull/1695

Please don't blame asomser, it is not easy to maintain a Nix, reviewing a PR can require several hours, and he was experiencing burnout at that time, as you can see from [this comment](https://github.com/nix-rust/nix/issues/2132#issue-1909906440).

**Comment by SteveLauC** [comment]
This issue will be closed by #2044
