### ISSUE TITLE
Add timer_* bindings

### ISSUE THREAD

**Issue by Zapeth** [nix-rust/nix#1424]
Feature request for adding bindings for the following POSIX timer functions to the crate:
* [ ] timer_create
* [ ] timer_delete
* [ ] timer_settime
* [ ] timer_gettime
* [ ] timer_getoverrun

See e.g. https://www.man7.org/linux/man-pages/man2/timer_create.2.html

**Comment by asomers** [comment]
That sounds like a good feature.  Would you be willing to implement it?

**Comment by Zapeth** [comment]
I could try, but considering I only have rather limited experience with Rust I'm pretty sure other people that might be willing/interested to implement this feature would be better suited.

As a sidenote, I just checked if the `libc` crate provides these functions and it seems they have yet to be implemented as well ([a PR draft exists](https://github.com/rust-lang/libc/pull/1900) but seems to be inactive for some time now), so that might be a necessary first step anyway before starting to work on it here.

**Comment by blt** [comment]
While it does appear that libc now has the relevant `timer_*` functions I think https://github.com/rust-lang/libc/issues/2576 is a potential blocker.
