### ISSUE TITLE
sockaddr_storage_to_addr is documented as being more lenient with the size than it is in practice

### ISSUE THREAD

**Issue by khuey** [nix-rust/nix#1479]
The documentation says

```
The len argument should be the number of bytes in the sockaddr_storage that are actually allocated and valid. It must be at least as large as all the useful parts of the structure.
```

This suggests that passing in a size larger than what is actually used (say, `size_of::<sockaddr_storage>()`) should be fine. But in the implementation, both `AF_INET` and `AF_INET6` assert that the size passed is exactly `size_of::<sockaddr_in>()`/`size_of::<sockaddr_in6>()`. Ideally IMO the implementation would match the documented behavior.

**Comment by asomers** [comment]
Yes, I think you're probably right.  Doing it as documented shouldn't lead to a memory leak.  But do you have any examples of something that creates a sockaddr_in or sockaddr_in6 as a sockaddr_storage with too much space?

**Comment by khuey** [comment]
When doing strace-like things it's convenient to grab `size_of::<sockaddr_storage>()` bytes of data and then have the function just work.

**Comment by asomers** [comment]
That makes sense.  Care to submit a patch?

**Comment by khuey** [comment]
When I have a chance, sure.
