### ISSUE TITLE
Unsoundness in UnixPath

### ISSUE THREAD

**Issue by coolreader18** [nix-rust/nix#1494]
```rust
println!("{}", UnixAddr(sockaddr_un { sun_family: AF_UNIX as _, sun_path: [0; 108] }, 10000));
```
Output;
```
"@<\u{0} x 108><9892 bytes of garbage>"
```
Also in the PartialEq and Hash impls and `as_abstract`; anywhere that uses `sun_path()` raw without doing what `path()` does and calling `strnlen` (and even `path()` is stiill unsound, it still calls `sun_path()` and creates a slice with a length longer than it should have)

**Comment by coolreader18** [comment]
I think it'd be best to just not have the fields be public; there's also a thing where because strnlen isn't called on creation of a `UnixPath`, two "different" paths can be `!=` just because one's length is 1 greater than the other and includes the trailing nul.

**Comment by asomers** [comment]
Yep, I agree.  The fields should never have been public.  Are you planning to submit a PR to fix it?

**Comment by coolreader18** [comment]
Sure, I can take a stab at it.
