### ISSUE TITLE
Add mincore binding

### ISSUE THREAD

**Issue by ocadaruma** [nix-rust/nix#1528]
It'd be nice to have `mincore` (https://man7.org/linux/man-pages/man2/mincore.2.html) bindings in this crate, which may be useful when we inspect page cache usage.

If no objection, I would like to send a patch later.

**Comment by asomers** [comment]
Nope, no objection.  Patches welcome.

**Comment by ocadaruma** [comment]
Closing as https://github.com/nix-rust/nix/pull/1530#issuecomment-922711862
