### ISSUE TITLE
Issue with TimeSpec/TimeVal and select

### ISSUE THREAD

**Issue by sebastiaoamaro** [nix-rust/nix#1540]
Hello, I am trying to use nix::select with a timeout however I can't put a timeout into the function.
Code:
let timeout = TimeSpec::seconds(1);
let _ = nixselect(None,&mut readfds, None, None, &timeout); 
Error:
error[E0277]: the trait bound `Option<&mut TimeVal>: From<&TimeSpec>` is not satisfied
   --> src/main.rs:489:17
    |
489 |         let _ = nixselect(None,&mut readfds, None, None, &timeout);  
    |                 ^^^^^^^^^ the trait `From<&TimeSpec>` is not implemented for `Option<&mut TimeVal>`

I am following the example/test given in https://github.com/nix-rust/nix/blob/master/test/sys/test_select.rs

Thanks in Advance.

**Comment by asomers** [comment]
You need to use a `TimeVal`, not a `TimeSpec`.  `select` uses the former, `pselect` the latter.

**Comment by sebastiaoamaro** [comment]
Oh, I understand my mistake!
Thanks for the quick response.
