### ISSUE TITLE
Unexepected EINVAL while using sched::unshare

### ISSUE THREAD

**Issue by IohannesArnold** [nix-rust/nix#1551]
This is more likely my user error than a bug, but I'm at the end of my wits. The following C works fine for me:
```C
int unshare_flags = 0;
unshare_flags |= CLONE_NEWUSER;
unshare(unshare_flags);
```
But when I try to do the same with nix (0.23.0, x86_64 Linux):
```Rust
let flags = CloneFlags::empty().union(CloneFlags::CLONE_NEWUSER);
unshare(flags).unwrap();
```
I get:
```
panicked at 'called `Result::unwrap()` on an `Err` value: EINVAL
```
I don't know, am I using bitflags wrong? Something else? I know it's probably my mistake, but thought I'd raise the issue just in case. Even if it is my fault, the docs could use some more clarity on how to use this (which I'm happy to help with, once I have a clue what's going on).

**Comment by asomers** [comment]
The easiest way to debug a problem like this is probably to use `strace` with both the C and Rust versions of the operation, and compare their argument values as reported by strace.

**Comment by IohannesArnold** [comment]
🤦 I was running into errors because I was building this as a library and running unit tests on it. `strace cargo test &| grep unshare` didn't reveal any calls to `unshare` at all. So I built a small binary to test the function, and the binary works fine. It's only running in a unit test that I run into problems.

I'm new to Rust, is this supposed to be how it works? You can't test syscalls (or *this* syscall) in unit tests?

**Comment by asomers** [comment]
No, that's not how it works.  And Nix doesn't have any _unit tests_ (which live in the src directory) for unshare, it only has _integration tests_ (which live in the test directory).  Run `cargo test --test test-mount` to run just the stuff that uses unshare.  Note, however, that Cargo forks a few child processes, which can make interpreting strace's output difficult.  So it will be easier for you to use strace if you invoke the test executable directly.  It should be named something like target/debug/deps/test_mount-*

**Comment by IohannesArnold** [comment]
Okay, got it. Thanks for the help and sorry for the distraction :)
