### ISSUE TITLE
Why does isatty return Result<bool>

### ISSUE THREAD

**Issue by Morganamilo** [nix-rust/nix#1559]
I'm not sure if this is too late to change but this function returning a Result<bool> seems unnecessary.

The c function returns 1 if the fd is a tty and otherwise 0 and always sets errno.

Looking at the code it treats ENOTTY as Ok(false) and anything else as Err(). This doesn't really make sense to me, it sounds more reasonable to either just return true for ret = 1 and false for ret = 0. Or if losing the errno info is a concern you could just return Result<(), Errno> and .is_ok() would mean it is a tty. You could also use a custom enum to make this more explicit `Enum IsTty { Yes, No(Errno) }`

**Comment by asomers** [comment]
I'm not convinced that the proposed alternative API is better, and changing it certainly wouldn't be worth the backwards-compatibility headache.
