### ISSUE TITLE
Unsoundness in FdSet

### ISSUE THREAD

**Issue by taylordotfish** [nix-rust/nix#1572]
[`FdSet::insert`](https://docs.rs/nix/0.23.0/nix/sys/select/struct.FdSet.html#method.insert), [`FdSet::remove`](https://docs.rs/nix/0.23.0/nix/sys/select/struct.FdSet.html#method.remove), and [`FdSet::contains`](https://docs.rs/nix/0.23.0/nix/sys/select/struct.FdSet.html#method.contains) call `FD_SET()`, `FD_CLR()`, and `FD_ISSET()` without any bounds checking, but those underlying libc functions [cause undefined behavior](https://pubs.opengroup.org/onlinepubs/7908799/xsh/select.html) when provided a file descriptor outside of the range `0..FD_SETSIZE`.

**Comment by asomers** [comment]
Yep, it's true.  Would you be willing to submit a PR to fix it?
