### ISSUE TITLE
Is waitid() system call provided?

### ISSUE THREAD

**Issue by caoruidong** [nix-rust/nix#1578]
Nix has waitpid,but no waitid

**Comment by asomers** [comment]
If there's a good case for it, we can always add it.  Would you care to submit a patch?

**Comment by asomers** [comment]
That syntax is valid, so probably the error is real.  You can use strace or ktrace to check what value was actually passed to the OS.

**Comment by caoruidong** [comment]
Thanks. I found that WEXITED can only be used in watid.
