### ISSUE TITLE
Segfault On Empty Program Compiled for `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by zicklag** [nix-rust/nix#1586]
With this Rust program I'm getting a segfault.

my `uname -a`: `Linux pop-os 5.13.0-7614-generic #14~1631647151~20.04~930e87c-Ubuntu SMP Fri Sep 17 00:26:31 UTC  x86_64 x86_64 x86_64 GNU/Linux`

```rust
extern crate nix;

fn main() {
}
```

Using VSCode LLDB to debug, here is the callstack and the surrounding disassembly:

![image](https://user-images.githubusercontent.com/25393315/139721259-cd19b7df-7e7c-4602-b244-1f746f96d24a.png)

![image](https://user-images.githubusercontent.com/25393315/139721331-697ec190-9883-47e3-8cee-c4301ac01861.png)

Is there anything more I can do to investigate or try to work around?

---

I tried a few other nix versions to see if they had the same error:

- `0.10.0`: no error
- `0.11.0`: error
- `0.15.0`: error
- `0.20.0`: error

**Comment by FedericoPonzi** [comment]
Which rust version are you using?

**Comment by zicklag** [comment]
I've tested the following versions:

- `rustc 1.57.0-nightly (11491938f 2021-09-29)`
- `rustc 1.56.1 (59eed8a2a 2021-11-01)`

**Comment by zicklag** [comment]
Just tested `rustc 1.46.0 (04488afe3 2020-08-24)` and it has the same issue.

**Comment by zicklag** [comment]
Ah, I found it. Apparently it happens when linking with `lld`. So I guess this isn't a problem with `nix`, just a strange occurrence or else a bug in `lld`.
