### ISSUE TITLE
recv and send functions of socket sometimes return wrong size

### ISSUE THREAD

**Issue by raindust** [nix-rust/nix#1600]
Nix version: nix 0.20.0
Test environment: Docker image based on "ubuntu:20.10", running in Ubuntu 20.04/18.04

I use `recv` and `send` functions under "nix::sys::socket" to transfer TCP data, sometimes these two functions return received or sent sizes small than the real data size. 

For example, If I send 1024 bits of data, I printed on both sending and receiving sides, and checked data size is exactly 1024 bits. But return sizes of both `recv` and `send` functions are 424 (424 is the size number most often appears).

**Comment by asomers** [comment]
Nix doesn't do anything fancy to the return values of `libc::send` and `libc::recv`.  Can you run with `strace` to see what the syscall's actual return value is when you think it's wrong?

**Comment by raindust** [comment]
I have ignored this error and it works well
