### ISSUE TITLE
`select` command works but `epoll` does not to monitor file writes

### ISSUE THREAD

**Issue by saleemjaffer** [nix-rust/nix#1612]
Hello, I have a file that has periodic writes up to a certain duration. I am trying to capture the new writes to this file and do further processing. I have tried 2 approaches to monitor the file - using `select` and `epoll`.

- Approach using `select`
```
fn func(read_list: Vec<(String, i32)>) {
    let mut in_buffer: Vec<u8> = Vec::new();
    let mut file_1 = File::open(&read_list[0].0).unwrap();
    let fd_1 = file_1.as_raw_fd();
    let mut fd_set = FdSet::new();

    loop {
        let mut timeout_timeval = nix::sys::time::TimeVal::seconds(2);
        fd_set.insert(fd_1);
        match select(fd_1 + 1, Some(&mut fd_set), None, None, &mut timeout_timeval) {
            Ok(res) => {
                if res == 0 {
                    info!("nothing to read");
                    break;
                } else if  res > 0 {
                    info!("found stuff to read");
                    let fd_collection: Vec<_> = fd_set.fds(None).collect();
                    if fd_collection.contains(&fd_1) {
                        read_stream(&mut file_1, &mut in_buffer);
                    }
                }
            }

            Err(err) => {
                error!("select error {:?}", err);
            }
        }
    }
}
```

This works fine - The `Ok` block of the `match` keeps getting triggered until there are no writes and then I break out of the loop.

- Approach using `epoll`
```
fn func(read_list: Vec<(String, i32)>) {
    let mut in_buffer: Vec<u8> = Vec::new();
    let mut file_1 = File::open(&read_list[0].0).unwrap();
    let fd_1 = file_1.as_raw_fd();

    let epoll_fd = epoll_create().unwrap();
    info!("epoll fd {:?}", epoll_fd);

    let mut epoll_event = EpollEvent::new(EpollFlags::EPOLLIN, fd_1 as u64);
    let epoll_ctl_res = epoll_ctl(epoll_fd, EpollOp::EpollCtlAdd, fd_1, Some(&mut epoll_event)).unwrap();

    let mut epoll_events = Vec::with_capacity(1024);
    loop {
        epoll_events.clear();
        match epoll_wait(epoll_fd, &mut epoll_events, 2000) {
            Ok(res) => {
                if res == 0 {
                    info!("nothing to read");
                    break;
                } else if  res > 0 {
                    info!("found stuff to read");
                    unsafe { epoll_events.set_len(res as usize) };
                    for event in &epoll_events {
                        if event.data() == (fd_1 as u64){
                            read_stream(&mut file_1, &mut in_buffer);
                        }
                    }
                }
            }

            Err(err) => {
                error!("epoll error {:?}", err);
            }
        }
    }
}
```

This does not work - the `Err` block keeps getting triggered all the time with `Sys(EINVAL)`. Any idea how I can get this to run with `epoll`?

Ran this on `Ubuntu 20.04.3` with `rustc 1.47.0`

**Comment by asomers** [comment]
This is a regular file?  You want a way to know when some other process wrote to it?  Select/epoll don't do that.  Regular files will always be considered both readable and writable.  You should take a look at inotify instead.  That does what you want.

**Comment by saleemjaffer** [comment]
@asomers The problem I have with `inotify` (when used in the blocking mode) is how do I stop watching the file once there are no writes? The call would continue to block(since there are no writes) and I cannot perform any further tasks.

With epoll/select we can specify a wait timeout. Once the timeout is breached I assume there are no more writes and perform further tasks.

Also, curious why you mention epoll/select does not do this? I have been using `select` in production and it is working fine on a regular fine apart from some intermittent deadlock issues.

**Comment by asomers** [comment]
Because POSIX requires that select not do what you want.  A regular file is always considered ready for reading.  See https://pubs.opengroup.org/onlinepubs/7908799/xsh/select.html .  On Linux inotify is the API that does what you want.  If you want it to be non-blocking, I believe you can use select to poll the Inotify file descriptor.  Also, inotify has a builtin way to monitor an entire directory.

**Comment by saleemjaffer** [comment]
@asomers The below example uses `epoll` on a `tcpstream` 

```
use std::net::TcpStream;
use nix::sys::epoll::{EpollEvent, EpollFlags, epoll_create, epoll_ctl, epoll_wait, EpollOp, EpollCreateFlags};

fn func() {
    let epoll_fd = epoll_create().unwrap();

    let tcp_stream = TcpStream::connect("google:443").expect("Failed to connect to google");
    let tcp_stream_fd = tcp_stream.as_raw_fd();

    let mut epoll_event = EpollEvent::new(EpollFlags::EPOLLIN, tcp_stream_fd as u64);
    let epoll_ctl_res = epoll_ctl(epoll_fd, EpollOp::EpollCtlAdd, tcp_stream_fd, Some(&mut epoll_event)).unwrap();

    let mut epoll_events: Vec<EpollEvent> = Vec::with_capacity(1024);
    loop {
        epoll_events.clear();
        match epoll_wait(epoll_fd, &mut epoll_events, 2000) {
            Ok(res) => {
                if res == 0 {
                    info!("nothing to read");
                    break;
                } else if  res > 0 {
                    info!("found stuff to read");
                    // process events
                }
            }

            Err(err) => {
                error!("epoll error {:?}", err);
            }
        }
    }
}
```

Even now I only get a `epoll error Sys(EINVAL)` error during `epoll_wait`. Any idea what am I doing wrong here? 😞

**Comment by saleemjaffer** [comment]
@asomers Yeah - It does not seem like I am passing an invalid `epoll` file descriptor, nor am I passing `maxevents` less than or equal to 0 (I have a vector with size 1024). Hence I am clueless about this.

**Comment by saleemjaffer** [comment]
@asomers That makes sense. `Vec::with_capacity(1024)` has a length of 0 and capacity of 1024 - this was causing the issue. Thanks for the help!
