### ISSUE TITLE
Should nix::unistd::read be unsafe?

### ISSUE THREAD

**Issue by alirstm** [nix-rust/nix#1629]
I can spawn multiple threads reading from the same RawFd in safe code, this should not be possible, right?

**Comment by asomers** [comment]
There's nothing wrong with that.  Why do you think it should be unsafe for multiple threads to read from the same file simultaneously?

**Comment by alirstm** [comment]
Because reading from a file changes internal offsets. So if two threads both read from the same file at the same time, both will lose some data. The Read trait in `std::io` takes `&mut self` probably for the same reason.

**Comment by asomers** [comment]
That is not what is meant by Rust's safety guarantee.  Rust only guarantees memory safety, which is much more limited than "prevent all race conditions".  See https://doc.rust-lang.org/nomicon/races.html .
