### ISSUE TITLE
Incorrect calculated disk size

### ISSUE THREAD

**Issue by mihaigalos** [nix-rust/nix#1645]
Hi,

[This](https://github.com/mihaigalos/dusage/issues/2) issue was traced back to a possible misconfiguration or bug in `nix`.

In the OP's case, [this](https://github.com/mihaigalos/dusage/blob/306210068316dd90f519e52da55bc5dc3ebaa526/src/stats.rs#L23) calculation yields an incorrect size of the disk which is different than what `df` reports (at least a factor 10x difference!).
I have tested the calculation on other `x64` and `aarch64` and it is consistent.

Are we doing something horribly wrong - what could be the problem here?

**Comment by mihaigalos** [comment]
So it seems the `statvfs.blocks() as u64 * statvfs.block_size() as u64` does not calculate the correct size of the disk.

**Comment by asomers** [comment]
Can you please write a complete reproduction case?

**Comment by mihaigalos** [comment]
Sorry for the confusion, we just needed a pointer in the right direction.
To compute the size of a disk using `nix` primitives, one needs to multiply `blocks` with `fragment_size`, not with `block_size`.
