### ISSUE TITLE
Making `from_libc_sockaddr` public?

### ISSUE THREAD

**Issue by apanda** [nix-rust/nix#1663]
I was trying to use nix to go from a `libc::sockaddr` to a `std::net::SockAddr`. This is useful when using `recvmsg` to receive data off a UDP socket or when using the equivalent io_uring operations. I notice that `from_libc_sockaddr` (https://github.com/nix-rust/nix/blob/5cd01a1fd7417ee6e16636443965c0a197ff2843/src/sys/socket/addr.rs#L959) implements this functionality, but is marked as crate only. I was wondering if it would acceptable to mark it as public. 

The change is of course trivial to make, I wanted to create an issue just to understand if there were concerns around marking it `pub`. One possible concern I can imagine is that it is marked unsafe at the moment, I imagine this is because of the pointer cast but I have to admit I am not sure how to make it safer because the code already ensures that the passed pointer is not null, so the checks required would need to ensure that the pointer is to a 4-byte allocation, which is non-trivial. On the other hand, maybe unsafe exports are unavoidable from nix and there are already cases, e.g., `ptsname` (https://github.com/nix-rust/nix/blob/83cd1da91f31cf49468e3e290046cf472481e0db/src/pty.rs#L175), where nix exports unsafe code.

The current situation requires that I copy the code into my project (or rewrite a more restricted version), and I want to avoid that if possible. Let me know if this is acceptable and I am happy to submit a PR.

**Comment by rtzoeller** [comment]
I don't have any objections to making this public (other than wanting documentation about what is actually supported by it), but I know @asomers is touching `SockAddr` in changes related to https://github.com/nix-rust/nix/issues/1544. @asomers any issues making this public?

**Comment by asomers** [comment]
Yes, I think the need to make this public will go away once I finish the sockaddr changes.  I know I haven't touched that branch in awhile.  I'll try to get to it this week, after I reach a stopping point on another project.

**Comment by asomers** [comment]
This is public now, as a result of #1684, except it's new name is `SockaddrStorage::from_raw`.
