### ISSUE TITLE
Add `doc(alias)` to functions

### ISSUE THREAD

**Issue by euclio** [nix-rust/nix#1673]
I had some trouble finding `User::from_uid` and `Uid::current` when looking for `getpwuid` and `getuid` replacements. It would be nice to add some [doc aliases](https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search) for the underlying C function names so that a library user can search the C function name and find the corresponding Rust function.

Unfortunately this feature was stabilized in 1.48 so we will have to wait for a MSRV bump to do it.

**Comment by asomers** [comment]
That's a good idea.
