### ISSUE TITLE
Statfs fs MAGIC constants are not available for target_os = "android"

### ISSUE THREAD

**Issue by flxo** [nix-rust/nix#1689]
The fs type constants defined in [src/sys/statfs](https://github.com/nix-rust/nix/blob/4ccc6c6e69fea5005cf6f8c50597e9296dd8dc92/src/sys/statfs.rs#L50-L141) are guard by `#[cfg(all(target_os = "linux", not(target_env = "musl")))]` and therefore not available for `target_os = "android`.  That hit me while patching [cgroups-rs](https://github.com/kata-containers/cgroups-rs) for Android and adding the `target_os = "android"` guard [here](https://github.com/kata-containers/cgroups-rs/blob/1df6e7a26ec30c1d9bb1c4ce9c13189a1d4aa401/src/hierarchies.rs#L300-L312)

Any change to get this updated to `#[cfg(any(all(target_os = "linux", not(target_env = "musl")), target_os = "android"))]`?
If yes I can prepare a PR.

Thanks!

**Comment by asomers** [comment]
It depends.  Are those constants actually defined on Android?  If they are, are they defined in rust's libc?  If the answer to the first question is "no", then there's nothing for you to do.  If yes, but the answer to the second question is no, then you should submit a PR to https://github.com/rust-lang/libc first, and to Nix second.  If the answer to both questions is yes, then feel free to submit a PR.

**Comment by flxo** [comment]
Thanks @asomers. Looks like the constants are enabled in libc for `target_os = "android"` [here](https://github.com/rust-lang/libc/blob/f00ea005769ba76610002b3652a5c6272ddc3633/src/unix/linux_like/mod.rs#L1377-L1430).

I'll send a PR with the updated guards. I will also sync the constants - looks like there are more in `libc` than in `nix`.
