### ISSUE TITLE
Release 0.24?

### ISSUE THREAD

**Issue by SUPERCILEX** [nix-rust/nix#1700]
Is there anything holding it back?

**Comment by SUPERCILEX** [comment]
cc @asomers @rtzoeller

**Comment by rtzoeller** [comment]
@asomers any objections? I can try to publish a release, pending any more unforeseen permissions issues.

**Comment by asomers** [comment]
Go for it.

**Comment by rtzoeller** [comment]
Done.

**Comment by SUPERCILEX** [comment]
Thank you! :tada:

**Comment by asomers** [comment]
@rtzoeller could you please tag the release revision and upload it?

**Comment by rtzoeller** [comment]
@asomers done.
