### ISSUE TITLE
Feature request: add `chflags` syscalls

### ISSUE THREAD

**Issue by musikid** [nix-rust/nix#1705]
Hi!

These syscalls are available only on BSDs and macOS, and are already present in the `libc` crate.
It's just a matter of writing the wrappers. So, I would like to submit a PR, I just need to know if it would be interesting to add them in the project.

https://www.freebsd.org/cgi/man.cgi?query=chflags&sektion=2&apropos=0&manpath=FreeBSD+13.0-RELEASE+and+Ports

**Comment by asomers** [comment]
Yes, I think that would definitely be a worthwhile feature.
