### ISSUE TITLE
InetAddr replacements are not convertible to libstd types?

### ISSUE THREAD

**Issue by khuey** [nix-rust/nix#1710]
Apologies if I've overlooked something here.

The now deprecated `nix::sys::socket::InetAddr` has a `to_std` method on it. The replacement `Sockaddrin`/`Sockaddrin6` don't appear to have any equivalent functionality.

**Comment by asomers** [comment]
You're right.  We could add that back.  Or maybe just `impl Into<std::net::SocketAddrV4> for SockaddrIn`.

**Comment by khuey** [comment]
Yeah the latter was what I was looking for but couldn't find. Would you take a PR?

**Comment by asomers** [comment]
sure.

**Comment by rtzoeller** [comment]
@asomers do you view this regression in functionality (prior to this submission) as a bug? Is it worth making a 0.24.2 for this, or just holding out for a future release?

**Comment by asomers** [comment]
No, I don't think of it as a regression.  If it were, then we should've named the new methods `to_std` just like they were in 0.23.0, rather than the more standard `into`.

**Comment by khuey** [comment]
The old `nix::sys::socket::InetAddr` still exists too so its not technically a regression IMO.
