### ISSUE TITLE
statvfs timeout on fuse.sshfs

### ISSUE THREAD

**Issue by mihaigalos** [nix-rust/nix#1723]
Hi,

Is there any possibility to force a timeout whlie calling `nix::sys::statvfs::statvfs()` on a sshfs network mount which isn't reachable (i.e.: mounted correctly, cable disconnected)?

Current behavior in `nix 0.23.0` is it blocks until a (system?) timeout.

**Comment by asomers** [comment]
Nix doesn't do anything fancy like that, it just wraps the C `statvfs` to make it more Rust-friendly.  If you want to change fuse.sshfs's timeout behavior, you should make that change in the daemon or the kernel, not in Nix.

**Comment by mihaigalos** [comment]
Thanks for the info. Any refs or further pointers?

**Comment by asomers** [comment]
Just look at the sshfs man page, to start.

**Comment by mihaigalos** [comment]
okok! :)
