### ISSUE TITLE
fcntl F_SEAL not available on FreeBSD

### ISSUE THREAD

**Issue by PolyMeilex** [nix-rust/nix#1733]
https://github.com/nix-rust/nix/blob/16471898160b5b1fa27689a26727d1d82ddd5573/src/fcntl.rs#L437-L440

[FreeBSD manual](https://www.freebsd.org/cgi/man.cgi?query=fcntl&sektion=2) lists those as available, but `nix` does not.

**Comment by asomers** [comment]
Yep.  Would you care to submit a PR to add it?
