### ISSUE TITLE
Interest in adding an safe API for spawn and spawn_p?

### ISSUE THREAD

**Issue by VincentWo** [nix-rust/nix#1740]
I am working at a project requiring me to call ’spawn’ and I noticed that there isn't a safe API for it.

I am going to develop a safe API for my private usage anyway and was wondering whether there would be an Interest for it to be contributed here :)

**Comment by asomers** [comment]
Do you mean `posix_spawn`?  Yes, that would make sense.  We already wrap `fork`, after all.
