### ISSUE TITLE
 SigSet Incorrect implementation of Eq and PartialEq

### ISSUE THREAD

**Issue by germag** [nix-rust/nix#1749]
`signal::SigSet` derives `Eq` and `PartialEq`, I assume because `libc::sigset_t` does it too, but in linux, `sigfillset(3)` only initializes the first 64 bits, leaving the rest uninitialized, so two `signal::SigSets` can be different even though both have the same set of signals

**Comment by germag** [comment]
I can work on fixing this, I assume it is preferable to manually implement `PartialEq` rather than simply eliminating the `derive (Eq, PartialEq)` since it's a breaking change, right?

**Comment by asomers** [comment]
Yes, I think it would be preferable to implement PartialEq rather than not to.

**Comment by magicant** [comment]
FYI: I previously reported this to libc
https://github.com/rust-lang/libc/issues/2700

**Comment by asomers** [comment]
@germag are you still planning to fix this?
