### ISSUE TITLE
convert sockaddr_storage to std::net::SocketAddr

### ISSUE THREAD

**Issue by behzadnouri** [nix-rust/nix#1754]
Is there any way to convert either of
```rust
libc::sockaddr_storage
nix::sys::socket::sockaddr_storage
```
to `std::net::ScoketAddr`?

I have looked into `nix::sys::socket::SockaddrStorage` but can't find what I am looking for.

**Comment by asomers** [comment]
No, not directly.  You have to pull it apart into pieces and then create a new `std::net::SocketAddr` using the standard constructors.

**Comment by asomers** [comment]
I'm going to close this, assuming that I've answered your question.  But feel free to reopen if not.
