### ISSUE TITLE
Add document for `OFlag` and its `from_bits` under 64 bits linux

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#1765]
> This is not an issue of nix, it is more related to the 64 bits Linux kernel. But maybe we can do something in `nix` to avoid this from happening:)

The following code snippet will panic, which is very counterintuitive:

```rust
use nix::fcntl::{fcntl, FcntlArg, OFlag};
use std::{
    fs::{File, OpenOptions},
    os::unix::{
        fs::OpenOptionsExt,
        io::{AsRawFd, RawFd},
    },
};

fn main() {
    let file: File = OpenOptions::new()
        .create(true)
        .write(true)
        .mode(0o666)
        .open("tmp")
        .expect("open");

    let fd: RawFd = file.as_raw_fd();

    let numeric_flag: i32 = fcntl(fd, FcntlArg::F_GETFL).unwrap();
    let flag: OFlag = OFlag::from_bits(numeric_flag).unwrap();  // LINE 21 is here
}
```

```shell
$ cargo r -q
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:21:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We fetch the status flag using `fcntl(fd, F_GETFL)` and wanna convert it to the corresponding `nix` type `OFlag`. And it just panics. This should not happen cause `numeric_flag` is a *valid* status flag.

Then I use `from_bits_truncated()` to truncate this "invalid" flag to find out where is that **wrong** bit?

```rust
use nix::fcntl::{fcntl, FcntlArg, OFlag};
use std::{
    fs::{File, OpenOptions},
    os::unix::{
        fs::OpenOptionsExt,
        io::{AsRawFd, RawFd},
    },
};

fn main() {
    let file: File = OpenOptions::new()
        .create(true)
        .write(true)
        .mode(0o666)
        .open("tmp")
        .expect("open");

    let fd: RawFd = file.as_raw_fd();

    let numeric_flag: i32 = fcntl(fd, FcntlArg::F_GETFL).unwrap();
    println!("numeric_flag: {} {:032b}", numeric_flag, numeric_flag);
    // 32769 00000000 00000000 10000000 00000001
    // (2^15 + 2^0) (O_LARGEFILE|O_WRONLY)

    let truncated_flag: OFlag = OFlag::from_bits_truncate(numeric_flag);
    println!(
        "truncated_flag: {} {:032b}",
        truncated_flag.bits(),
        truncated_flag.bits()
    );
    // 1 000000000 00000000 00000000 0000001
    // (2^0) (O_WRONLY)
}
```

As you can see, `numeric_flag` has an extra flag `O_LARGEFILE` enabled. And this is the root of our previous panic.

`O_LARGEFILE`, a flag used to perform large file I/O operation on 32-bit platforms, is definitely obsolete on 64 bits systems. But `fcntl` still returns it. 

And as it is obsolete on 64 bits platforms, `libc` defines [it](https://docs.rs/libc/latest/libc/constant.O_LARGEFILE.html) as `0`, which makes `nix` think it is `0` too. That's the reason why `from_bits()` think  `2^15` is a wrong bit.

I know `OFlag` is constructed using [this macro](https://docs.rs/bitflags/1.3.2/bitflags/macro.bitflags.html), but perhaps there is some approach to add some documents to remind the user and prevent them from encountering this.

#### Environment
```shell
$ uname -a
Linux pop-os 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux
$ rustc --version
rustc 1.62.0 (a8314ef7d 2022-06-27)
$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
$ cat Cargo.toml|grep nix
nix = "0.24.2"
```

**Comment by asomers** [comment]
Yeah, this sounds like a bug in Linux to me.  I'm not sure there's anything good that Nix can do about it.  BTW, in situations like this you should use `from_bits_truncate` anyway, for forwards-compatibility with newly introduced flags that Nix doesn't know about.

**Comment by SteveLauC** [comment]
Makes sense to me:)
