### ISSUE TITLE
add brk() and sbrk()

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#1781]
It would be great if we have these two syscalls:

#### brk

* Linux/NetBSD/OpenBSD

  ```c
  int brk(void*);
  ```

* macOS

  ```c
  void* brk(void*);
  ```

* freeBSD

  ```c
  int brk(const void*); // can be merged with `Linux/NetBSD/OpenBSD`
  ```

#### sbrk

* Linux/freeBSD/NetBSD

  ```c
  void* sbrk(intptr_t);
  ```

* macOS/OpenBSD

  ```c
  void* sbrk(int);
  ```

### Implementation:
```rust
#[cfg(any(
    target_os = "linux",
    target_os = "netbsd",
    target_os = "openbsd",
    target_os = "freebsd"
))]
pub fn brk(addr: *mut c_void) -> Result<()> {
    let res: i32 = unsafe { libc::brk(addr) };

    Errno::result(res).map(drop)
}

#[cfg(target_os = "macos")]
pub fn brk(addr: *mut c_void) -> Result<*mut c_void> {
    let res: *mut c_void = unsafe { libc::brk(addr) };

    Errno::result(res)
}

#[cfg(any(target_os = "linux", target_os = "netbsd", target_os = "freebsd"))]
pub fn sbrk(increment: libc::intptr_t) -> Result<*mut c_void> {
    let res: *mut c_void = unsafe { libc::sbrk(increment) };

    Errno::result(res)
}

#[cfg(any(target_os = "macos", target_os = "openbsd"))]
pub fn sbrk(increment: c_int) -> Result<*mut c_void> {
    let res: *mut c_void = unsafe { libc::sbrk(increment) };

    Errno::result(res)
}
```

**Comment by asomers** [comment]
On all five operating systems the man page describes these functions as some kind of deprecated.  Why do you want them?

**Comment by SteveLauC** [comment]
> On all five operating systems the man page describes these functions as some kind of deprecated.  Why do you want them?

One should not allocate memory using these syscalls. But if they wanna implement their own malloc or check out the value of program beak, perhaps these functions are still useful?

**Comment by asomers** [comment]
Perhaps.  But only for use by very specialty crates.  I'm not sure they warrant inclusion in Nix.

**Comment by SteveLauC** [comment]
> Perhaps.  But only for use by very specialty crates.  I'm not sure they warrant inclusion in Nix.

Makes senses to me
