### ISSUE TITLE
Termios `c_line` field

### ISSUE THREAD

**Issue by tertsdiepraam** [nix-rust/nix#1802]
Hi! I've been working on an `stty` implementation in Rust for uutils using `nix` and I noticed that the `nix::Termios` struct does not have a `c_line` field, even though the `libc::termios` does on Linux. Would it be possible to add it for Linux only?

I could give this a go if this is something you want to include.

**Comment by rtzoeller** [comment]
I think adding this makes sense; it looks like Haiku and possibly a few other platforms also support it (at least it's present in rust-lang/libc). 

> I could give this a go if this is something you want to include.

Please do! Don't forget to add an entry to the CHANGELOG.md as part of that commit.
