### ISSUE TITLE
Should maybe clarify that RLIM_INFINITY comes from libc

### ISSUE THREAD

**Issue by hlavaatch** [nix-rust/nix#1803]
Doc for `getrlimit` and `setrlimit` mentions RLIM_INFINITY constant but doesn't mention it comes from the libc crate.
Maybe it should, or the constant could be re-exported in the `nix::sys::resource` namespace.
As it is now, search for RLIM_INFINITY in nix doc yields nothing, leaving user scratching his head :)

**Comment by asomers** [comment]
Good point.  Reexporting it makes sense, I think.  Would you care to submit a PR for that?
