### ISSUE TITLE
Expose `domainname` field of `utsname` struct

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#1814]
`libc` [exposes](https://rust-lang.github.io/libc/x86_64-unknown-linux-gnu/doc/libc/struct.utsname.html) this, but nix does [not](https://docs.rs/nix/latest/nix/sys/utsname/struct.UtsName.html#impl-UtsName), any reason why it is not exposed?

**Comment by asomers** [comment]
Sure, that makes sense.  Patches welcome.
