### ISSUE TITLE
Syscall -> string name map?

### ISSUE THREAD

**Issue by xplorld** [nix-rust/nix#1832]
Hi nix,

I'm trying to write a strace-like tool, and I want to convert a syscall number to a human readable name (e.g. `16` -> `ioctl`). I didn't find such a mapping in the `nix` crate and wonder if it's possible to have one.

Thanks.

**Comment by SteveLauC** [comment]
`strace(1)` maintains their their own mapping (e.g., on x86_64, [linux/x86_64/syscallent.h](https://github.com/strace/strace/blob/master/src/linux/x86_64/syscallent.h )). 

IMHO, `nix` is not the right place to add such a mapping, perhaps this deserves a dedicated crate? If you don't mind the overhead of forking a child process, call [`ausyscall`](https://github.com/linux-audit/audit-userspace/tree/master/tools/ausyscall) in your process is also an option.

**Comment by asomers** [comment]
Yeah, I agree.  This sn't the type of functionality that Nix is intended to provide.
