### ISSUE TITLE
Change the interface of `openat(dirfd: RawFd, ...)` to `openat(dirfd: Option<RawFd>, ...)`

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#1850]
Almost every `xxxat()` function takes an optional `dirfd`, except [`fcntl::openat(2)`](https://docs.rs/nix/latest/nix/fcntl/fn.openat.html) and [`Dir::openat()`](https://docs.rs/nix/latest/nix/dir/struct.Dir.html#method.openat)

```rust
pub fn openat<P: ?Sized + NixPath>(
    dirfd: RawFd,
    path: &P,
    oflag: OFlag,
    mode: Mode,
) -> Result<RawFd> 
```
```rust
pub fn openat<P: ?Sized + NixPath>(dirfd: RawFd, path: &P, oflag: OFlag, mode: sys::stat::Mode) -> Result<Self> {
    let fd = fcntl::openat(dirfd, path, oflag, mode)?;
    Dir::from_fd(fd)
}
```

Any reason why it does not take an `Option<RawFd>`?

**Comment by SUPERCILEX** [comment]
We should just do something similar to https://docs.rs/rustix/latest/src/rustix/fs/cwd.rs.html#26-32 (but as a const) while implementing https://github.com/nix-rust/nix/issues/1750.

**Comment by asomers** [comment]
Git archaeology doesn't show any good reason why the functions take a `RawFd`.  I agree that an Option would be better.

**Comment by SteveLauC** [comment]
Close as completed in #2139
