### ISSUE TITLE
expose AT_EMPTY_PATH flag with linkat / LinkatFlags 

### ISSUE THREAD

**Issue by xaverdh** [nix-rust/nix#1884]
Currently you can't set this flag..

This is useful in the following situation:
You create a temporary file with `O_TMPFILE` and without `O_EXCL`, then you want to link it somewhere, but have no old file path you could give `linkat`.

**Comment by asomers** [comment]
Yeah, that would be good.  Care to submit a PR?

**Comment by xaverdh** [comment]
Ok, I will give it a try

**Comment by xaverdh** [comment]
What is the policy regarding api breakage? I am tempted to just make the `oldpath` argument an `Option`..
I can only think of two ways to preserve the api:
* introduce a new function with the new api
*  make the argument polymorphic via a trait that the old `LinkatFlags` then implements

**Comment by xaverdh** [comment]
Ok, so the linked pr now just swaps `LinkatFlags` for a `bitflags` based implementation. That will cause breakage of course..
