### ISSUE TITLE
Update nix::sys::signal::Signal Enum to include missing Signals

### ISSUE THREAD

**Issue by viglia** [nix-rust/nix#1924]
Hi,

I've noticed that some signals such as `SIGRTMIN` and `SIGRTMAX` are missing from the [Signal](https://docs.rs/nix/0.26.1/nix/sys/signal/enum.Signal.html) enum.

Right now I'm overcoming such limitation by using `libc` functions, struct and constants but it'd be nice to have those in the `nix` crate so that I could use the `sighandler` and `sigaction` from `nix` instead.

**Comment by SteveLauC** [comment]
`Nix` uses [`libc_enum!()`](https://github.com/nix-rust/nix/blob/a2356abe578dc822dbaf4386fbc17a63385ba0f8/src/macros.rs#L99) to handle these C-like enums:

```rust
// First code snippet

libc_enum! {
    #[repr(i32)]
    pub enum SignalWithMacro {
        /// Hangup
        SIGHUP,
    }
}
```

is converted into something like this:

```rust
// Second code snippet

#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SignalWithoutMacro {
    /// Hangup
    SIGHUP = libc::SIGHUP,
}
```

And this macro needs a **constant** value with the same name as the variant exists in `rust-lang/libc`.

`SIGRTMIN` and `SIGRTMAX`, are not constants but functions.

If we abandon the use of `libc_enum!` and specify the value of the variants manually like I did in the `Second code snippet`, then the functions used need to be **const**:

```rust
// Third code snippet

#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SignalWithoutMacro {
    /// Hangup
    SIGHUP = libc::SIGHUP,

    SIGRTMIN = libc::SIGRTMIN(),
}
```

```shell
$ cargo r -q
error[E0015]: cannot call non-const fn `SIGRTMIN` in constants
  --> src/main.rs:16:16
   |
16 |     SIGRTMIN = libc::SIGRTMIN(),
   |                ^^^^^^^^^^^^^^^^
   |
   = note: calls in constants are limited to constant functions, tuple structs and tuple variants
```

However, [`SIGRTMIN()`](https://docs.rs/libc/latest/libc/fn.SIGRTMIN.html) and [`SIGRTMAX()`](https://docs.rs/libc/latest/libc/fn.SIGRTMAX.html) are not const functions...

**Comment by viglia** [comment]
I see.

Thanks for the thorough explanation :)

It's a bummer but it is what it is.

Feel free to close this issue then.

**Comment by SteveLauC** [comment]
> Feel free to close this issue then.

Then I will close this issue:)
