### ISSUE TITLE
Shared memory objects are leaked

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [nix-rust/nix#1957]
Shared memory objects are not unlinked when their file descriptor is dropped.

The 1st time you run `cargo test test_shm_open` with:
```rust
#[test]
fn test_shm_open() {
    use nix::{
        sys::{mman::shm_open, stat::Mode},
        fcntl::OFlag
    };
    let res = shm_open(
        "/abcde",
        OFlag::O_RDWR | OFlag::O_CREAT | OFlag::O_EXCL,
        Mode::all(),
    );
    assert!(res.is_ok());
}
```
It passes, the 2nd time you run it, it fails with the error `EEXIST`, this illustrate that the shared memory object is not being cleaned up.

This is a serious memory leak, which requires manual intervention or in the case of a casual user, restarting their system to clean up.

By returning `OwnedFd` and not marking the function `unsafe` this may give the illusion it cleans up, when it doesn't.

It should be marked `unsafe`.

If there is to be a safe variant of the function it should return a wrapper which ensures the shared memory is unlinked when the last processes linked to it ends.

**Comment by RomainChaumontet** [comment]
I disagree with you, unlink should be done manually, not when the file descriptor is dropped. And actually, there is a function to unlink it (line 600).

The issue here is on the test, which should unlink the shared memory.

**Comment by asomers** [comment]
I agree with @RomainChaumontet .  This is not a bug.  That's how shared memory objects are supposed to work.  They're a lot like files.  They're intended to persist for longer than the lifetime of a process.  If you want them to drop automatically, you'll have to wrap them in a newtype yourself, and implement `Drop` for it.
