### ISSUE TITLE
Endianness is being swapped incorrectly

### ISSUE THREAD

**Issue by aarond10** [nix-rust/nix#1963]
The byte swap of flowinfo and scope_id [here](https://github.com/nix-rust/nix/blob/master/src/sys/socket/addr.rs#L1185-L1186) seems wrong and appears to have broken my project. 

Pull request forthcoming with a fix.

**Comment by aarond10** [comment]
@khuey, can you take a look at this one? It looks like you added this code back in May.

**Comment by khuey** [comment]
Yeah, the existing code is wrong and the fix is correct, these extra fields are in host byte order.

**Comment by aarond10** [comment]
Thanks for merging the fix. How often are releases cut? I see the last one was November.

Is it possible to request a new minor release be pushed to cargo?
I'm working on a project that uses vendored crates and without a cargo release I'll have to maintain a fork until the next release in order to keep on working.

**Comment by aarond10** [comment]
@asomers, could a new release be cut and pushed to crates.io?

**Comment by asomers** [comment]
Yes, this bug warrants a patch release.  See https://github.com/nix-rust/nix/pull/1974 .

**Comment by asomers** [comment]
0.26.2 released.

**Comment by aarond10** [comment]
Thanks! BTW, is there some back integration system? The master branch doesn't seem to have the #1974 change, only the r0.26 branch.

**Comment by asomers** [comment]
Yes, and the "system" is that we cherry-pick stuff manually.  That way release 0.26.2 contains only bug fixes, not the new features that are in the master branch.
