### ISSUE TITLE
Measured time inconsistent with txtime delay in socket example

### ISSUE THREAD

**Issue by fabracht** [nix-rust/nix#1970]
When running the test named `test_txtime()` on line 2484 in the `test/sys/test_socket.rs` file, the delay doesn't seem to apply.
The test sets the delay to be 1 second from MONOTONIC now. But when I measure the time with `tcpdump`, the message seems to be processed immediately.
Is there something wrong with the code or did I misinterpret the delay part?

**Comment by vkrasnov** [comment]
You should run `tc qdisc add dev eth0 root fq` to enable this feature on localhost first

**Comment by fabracht** [comment]
Ah, yes. Indeed that solves it. 
For localhost I had to specify the loopback device, but it works as intended. 
Thanks
