### ISSUE TITLE
Make it a safety requirement for sockets to use CLOEXEC

### ISSUE THREAD

**Issue by notgull** [nix-rust/nix#1984]
Rust may soon require sockets to be `CLOEXEC` as a safety requirement, see [here](https://github.com/rust-lang/rust/pull/107338) for more information. This would mean that `nix` should make it so functions that can return file descriptors, like `socket` or `recvmsg` would need to make sure all sockets implement `CLOEXEC`.

**Comment by VorpalBlade** [comment]
Looks like they decided not to do this in the current form upstream.
