### ISSUE TITLE
hints for adding sigsuspend().

### ISSUE THREAD

**Issue by castilma** [nix-rust/nix#1994]
I'm a rust beginner and I'd like to practice a bit by adding sigsuspend. But I need some hints.

I thought adding it to SigSet right after wait. Regarding the name I'd choose `suspend`, since `wait` had the prefix `sig` stripped, too.

If sigsuspend returns, it always returns the same value. Is it necessary to return that value to the caller?

Do I have to add some special documentation because it may not return?

**Comment by asomers** [comment]
> I'm a rust beginner and I'd like to practice a bit by adding sigsuspend. But I need some hints.
> 
> I thought adding it to SigSet right after wait. Regarding the name I'd choose `suspend`, since `wait` had the prefix `sig` stripped, too.

Makes sense.

> 
> If sigsuspend returns, it always returns the same value. Is it necessary to return that value to the caller?

Not in the success case.  But it might also fail with EFAULT.

> 
> Do I have to add some special documentation because it may not return?

No.

**Comment by castilma** [comment]
> Not in the success case. But it might also fail with EFAULT.
There is no 'success' case. It never returns with a success. It's always an 'error' case, where errno is set to distinguish between the errors. And since errno is global, I don't have to return it explicitly, right?
