### ISSUE TITLE
EPERM: Operation not permitted.

### ISSUE THREAD

**Issue by Ruoye-W** [nix-rust/nix#2001]
I tried to deploy sccache distribute compilation in Ubuntu 20.04 docker container, nix version is 0.26.2, kernel version is 4.14.81.bm.29-amd64, and build server was running as root. when client send distributed compilation request, build server got error from invoking nix:
	nix::sched::unshare(nix::sched::CloneFlags::CLONE_NEWNS)

 I got EPERM error as follow:
[2023-02-15T08:07:01Z WARN  sccache::dist::http::server] Res 1 error: run build failed, caused by: Compilation execution failed, caused by: Failed to enter a new Linux namespace, caused by: EPERM: Operation not permitted.

**Comment by asomers** [comment]
This looks like your docker container lacked some capability that it needs.  It doesn't look like a Nix bug.

**Comment by asomers** [comment]
Since there's been no actiivty, I'm closing this issue on the assumption that the OP figured it out.
