### ISSUE TITLE
Invalid transmute from `std::net::Ipv4Addr` to `libc::in_addr`

### ISSUE THREAD

**Issue by stevenengler** [nix-rust/nix#2053]
The functions `ipv4addr_to_libc` and `ipv6addr_to_libc` transmute from `std::net::Ipv4Addr` to `libc::in_addr`, but this is unsound.

https://github.com/nix-rust/nix/blob/89b4976fddf713ca54834612e351ae35d86c430a/src/sys/socket/addr.rs#L39-L54

The rust socket address types do not have the same layouts as their corresponding libc types, even if their size is the same.

See https://github.com/rust-lang/rust/pull/78802 for details.

> This release changes the memory layout of `Ipv4Addr`, `Ipv6Addr`, `SocketAddrV4` and `SocketAddrV6`. The standard library no longer implements these as the corresponding libc structs (`sockaddr_in`, `sockaddr_in6` etc.). This internal representation was never exposed, but some crates relied on it anyway by unsafely transmuting. This change will cause those crates to make invalid memory accesses.

> This change obviously changes the memory layout of the types. And it turns out some libraries invalidly assumes the memory layout and does very dangerous pointer casts to convert them. These libraries will have undefined behaviour and perform invalid memory access until patched.

**Comment by WhyNotHugo** [comment]
Looks like these functions will have to be rewritten to perform a more expensive conversion rather than simply transmuting.

**Comment by stevenengler** [comment]
> Do you know of any real platforms where it isn't?

I don't know of any. Rust is free to do whatever it wants for the layout (and the layout isn't guaranteed to be the same even across builds), but it's probably unlikely that a the rust representation of `struct Ipv4Addr { octets: [u8; 4] }` would ever be different from if the struct was `repr(C)`. The `Ipv6Addr` and `in6_addr` have different alignments, but that shouldn't matter when transmuting the value rather than a reference.

But on the other hand, I would expect

```rust
libc::in_addr {
    s_addr: u32::from_be_bytes(addr.octets()).to_be()
}
```

to get optimized to essentially a no-op anyway. For example on godbolt:

```rust
pub fn convert(addr: std::net::Ipv4Addr) -> u32 {
    u32::from_be_bytes(addr.octets()).to_be()
}
```

gets compiled to just

```
example::convert:
        mov     eax, edi
        ret
```
