### ISSUE TITLE
Documentation lacks modules that depend on compile-time features.

### ISSUE THREAD

**Issue by anachrome** [nix-rust/nix#206]
The documentation linked from the readme does not include the modules `sys::signalfd` or `sys::eventfd`, both of which are present in the source (with `#[cfd(feature = "...")]` flags).

**Comment by kamalmarhubi** [comment]
I think this is blocked on rustdoc issues. See also:
- https://github.com/rust-lang/rust/issues/1998
- https://github.com/rust-lang/rust/issues/24658

I'd like an answer though!
