### ISSUE TITLE
ci: `personality` doc test is failing

### ISSUE THREAD

**Issue by tammela** [nix-rust/nix#2060]
The documentation for `personality(2)` seems to be failing the CI test:
https://cirrus-ci.com/task/4888482292695040

I don't think it's related to https://github.com/nix-rust/nix/pull/2036.
Other PRs seems to be having the same issue.

I ran it multiple times over the last two weeks, thinking it was possibly a bad image/emulator but it has been persistent (returns EPERM).
Either some CI security sandbox is blocking it or a newer kernel added more security checks...

**Comment by asomers** [comment]
Might be seccomp.  If I don't get a good answer here, I'll disable that doc test.  Thanks for reporting.
https://github.com/cirruslabs/cirrus-ci-docs/discussions/1182

**Comment by asomers** [comment]
Disabling seccomp didn't work (see PR #2063).  I'm just going to leave that doc test as no_run instead.  The effort to work around seccomp outweighs the benefit in test coverage from testing such a trivial function.
