### ISSUE TITLE
Wrong underlying type for `sockopt::IpMulticastTtl`?

### ISSUE THREAD

**Issue by sgasse** [nix-rust/nix#2073]
Hi! I was trying to set the [`sockopt`][https://docs.rs/nix/latest/nix/sys/socket/sockopt/index.html] [IpMulticastTtl](https://docs.rs/nix/latest/nix/sys/socket/sockopt/struct.IpMulticastTtl.html) on my Linux machine with kernel `5.15.0-76-generic`. However it always failed with `Error: EINVAL: Invalid argument`. Discussing with a colleague, he told me that he used `i32` on Java for the same option. And with `i32`, it works at least on my machine.

I made a PR in #2072 including tests that fail before changing the type. However the new tests seem to fail on FreeBSD. Could this be a difference between Linux and FreeBSD? :thinking: I don't have a FreeBSD ready to test.

**Comment by saeebm** [comment]
let _ = socket::setsockopt(&s, sockopt::IpMulticastTtl, &0);

(from strace)
setsockopt(3, SOL_IP, IP_MULTICAST_TTL, [768], 4) = -1 EINVAL (Invalid argument)

appears that 768 is being set as the default value - not sure why though, couldn't really spot anything

**Comment by SteveLauC** [comment]
Close as completed in #2072
