### ISSUE TITLE
recvmsg: incorrect lifetime returned

### ISSUE THREAD

**Issue by yuval-k** [nix-rust/nix#2083]
the current signature of recvmsg is:
```rust
pub fn recvmsg<'a, 'outer, 'inner, S>(fd: RawFd, iov: &'outer mut [IoSliceMut<'inner>],
                   mut cmsg_buffer: Option<&'a mut Vec<u8>>,
                   flags: MsgFlags) -> Result<RecvMsg<'a, 'inner, S>>
```

note the iov param:  `iov: &'outer mut [IoSliceMut<'inner>]`

now in the resulting `RecvMsg` we can access the iovs using a method named `iovs()`. This method iterates the iov array provided. But the lifetime of the iov array is `'outer` and not `'inner`.

So the signature of the result should be changed to `Result<RecvMsg<'a, 'outer, S>>`.

If all sounds correct, i can open a PR to fix this.

example fail scenario with tokio (note the move closure):

```rust
            let tokio_stream = /* get a stream somehow... */;
            let mut buffer = vec![0u8; 10];

            let mut iov = [IoSliceMut::new(&mut buffer)];
            
            let res: Result<nix::sys::socket::RecvMsg<'_, '_, ()>, std::io::Error> =
                tokio_stream.try_io(tokio::io::Interest::READABLE, move || {
                    recvmsg::<()>(
                        raw_fd,
                        &mut iov,
                        None,
                        MsgFlags::empty(),
                    )
                    .map_err(|e| std::io::Error::from_raw_os_error(e as i32))
                });
            match res {
                Ok(res) => {
// BUG HAPPENS HERE
// NOTE: here res.iovs() uses the iov array that was moved in the try_io closure
// res.iovs() may point to invalid memory, as iov may have been destroyed already.
                }
                Err(e) => { /* ... */  }
            };
    }

```

**Comment by asomers** [comment]
Yes, I think your analysis is correct.  Would you submit a PR?

**Comment by cgwalters** [comment]
Good catch on this! Looks like one of my projects was affected https://github.com/containers/containers-image-proxy-rs/pull/52

I guess any potentially problematic code will now fail to compile, which is good.  I wonder if this could use a bit more visibility though with e.g. a rustsec advisory?

**Comment by cgwalters** [comment]
Using a [GH code search](https://github.com/search?q=lang%3Arust+%22recvmsg%3A%3A%22+IoSliceMut+-is%3Afork&type=code) I'm seeing a few other repositories likely affected too.

- [stratis](https://github.com/stratis-storage/stratisd/blob/2a220e59af664a5053970e18c0bffea48d4950ba/src/jsonrpc/server/server.rs#L350)
- [runa](https://github.com/yshui/runa/blob/1285951863bf4c39798758ebeda0216588184182/runa-io/src/lib.rs#L277)
- [breadx](https://github.com/bread-graphics/breadx/blob/3a0041025e91cc8e34fd02f067a81e9e7304d11c/breadx/src/connection/sendmsg.rs#L100)
- [clipper](https://github.com/lf-/clipper/blob/dd1caf13191e0fa58afbc3680fb83782c20e63d2/crates/wire_blahaj/src/unprivileged.rs#L540)
- [garage](https://github.com/clchiou/garage/blob/1d72863d3a5f5d620b170f4dd36f605e6b72054f/rust/g1/tokio/src/net/icmp.rs#L86)
- [adrastea](https://github.com/eiz/adrastea/blob/e6c80cce32b91aef2a623ab91f725bf2b01c7897/adrastea_core/src/net.rs#L81)
-
