### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dead10ck** [nix-rust/nix#2084]
The last release 0.26.2 was on Jan 17. There have been lots of commits since then. Could you please cut a new release so that others can benefit from the code changes without having to use a git dependency?

In particular, I'm running into a SIGSEGV on Android that appears to have been fixed by 09a85e2.

**Comment by dreiss** [comment]
I'm interested in this as well for https://github.com/nix-rust/nix/pull/1928 and other commits that add OwnedFd return values.

**Comment by asomers** [comment]
Yes, I agree.  I'll try to wrap up a few outstanding PRs and publish one.  I might do a 0.26.2 bugfix release, too.

**Comment by asomers** [comment]
I was hoping to do a release this weekend.  But then I caught the flu, and now my brain is too foggy.  So I'll push it off for another week.

**Comment by dead10ck** [comment]
Hope you get well soon! I appreciate your work on this crate!

**Comment by asomers** [comment]
v0.26.3 and v0.27.0 just released.

**Comment by dead10ck** [comment]
@asomers you and the rest of the contributors are awesome, thank you!
