### ISSUE TITLE
Enable features when building for docs.rs

### ISSUE THREAD

**Issue by alex** [nix-rust/nix#2110]
https://docs.rs/about/builds#cross-compiling

The latest release moves everything behind features (cool!). Unfortunately, a side-effect is that the docs on docs.rs are kind of useless (sad :-()).

You can use the metadata from the link above to enable all the optional features for that build, which will make the docs useful again (yay!).

**Comment by asomers** [comment]
Oops, thanks for pointing that out.  Care to review the linked PR?  I'll publish a patch release after that just to get the docs rebuilt.  Oh, and BTW Nix adopted fine-grained feature flags back in 0.24.0.  What changed in 0.27.0 is the default setting: now no features are enabled by default.
