### ISSUE TITLE
Support eventfd on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [nix-rust/nix#2123]
`eventfd` is available on [FreeBSD >= 13.0](https://github.com/freebsd/freebsd-src/commit/7a202823aa54), [exposed](https://github.com/rust-lang/libc/commit/57492ef9939f) by `libc` crate and made available [for all FreeBSD versions](https://github.com/rust-lang/libc/commit/a4fd9d32c854).

Alternative to #2037.

**Comment by jbeich** [comment]
Note, `eventfd` on NetBSD (and also `timerfd` on FreeBSD) are blocked by libc crate. I've removed NetBSD reference from the issue description to avoid confusion.

**Comment by SteveLauC** [comment]
Since this has been natively supported in FreeBSD, I think we should probably add it

**Comment by SteveLauC** [comment]
Close as completed in #2259
