### ISSUE TITLE
Introduce `mmap_nofd` to work around `<F: AsFd>`?

### ISSUE THREAD

**Issue by newpavlov** [nix-rust/nix#2126]
Today when I use nix's `mmap` for creating anonymous mappings I have to use `mmap::<BorrowedFd>(...)`, which feels... quite awkward. It would be nice to have a variant of `mmap` with the following signature:
```rust
pub unsafe fn mmap_nofd(
    addr: Option<NonZeroUsize>,
    length: NonZeroUsize,
    prot: ProtFlags,
    flags: MapFlags,
) -> Result<*mut c_void>
```
The `offset` argument has meaning only for file-backed mappings, so we can remove it as well.

**Comment by newpavlov** [comment]
Alternatively, it can be named as [`mmap_anonymous`](https://docs.rs/rustix/latest/rustix/mm/fn.mmap_anonymous.html).

**Comment by asomers** [comment]
For that matter, is `F: AsFd` the best argument type for non-anonymous mappings?  Would anybody ever want to supply an OwnedFd?  If not, then maybe the argument type should be `Option<BorrowedFd>`.

**Comment by SteveLauC** [comment]
### For anonymous `mmap`

> Today when I use nix's `mmap` for creating anonymous mappings I have to use `mmap::<BorrowedFd>(...)`, which feels quite awkward

It is indeed awkward to have to specify the generic argument even though we don't use it at all, so perhaps a dedicated anonymous function would be great here?

BTW, if we are gonna add this function, `mmap_anonymous` seems to be a better name than `mmap_nofd`.

------

### For file-backed (non-anonymous) `mmap`

> Is `F: AsFd` the best argument type for non-anonymous mappings? Would anybody ever want to supply an `OwnedFd`? If not, then maybe the argument type should be `Option<BorrowedFd>`.

From the [Linux man page](https://www.man7.org/linux/man-pages/man2/mmap.2.html):
> After the mmap() call has returned, the file descriptor, fd, can be closed immediately without invalidating the mapping.

It seems to be ok to close that fd after calling `mmap(..., fd, ...)`

**Comment by JonathanWoollett-Light** [comment]
`mmap_anonymous` makes the most sense to me.
