### ISSUE TITLE
Cargo test fails

### ISSUE THREAD

**Issue by carlosb1** [nix-rust/nix#2148]
I suppose It is something that I am doing wrong, but I don't see any doc related to configure the `cargo test` (rust 1.72.0)

It throws a lot of different errors (I suppose architecture errors)

```
  Compiling nix v0.27.1 (/home/carlosb/rust-workspace/nix)
error[E0432]: unresolved import `nix::sys::aio`
  --> test/sys/test_aio_drop.rs:18:19
   |
18 |     use nix::sys::aio::*;
   |                   ^^^ could not find `aio` in `sys`

error[E0432]: unresolved import `nix::mount`
  --> test/test_mount.rs:19:14
   |
19 |     use nix::mount::{mount, umount, MsFlags};
   |              ^^^^^ could not find `mount` in `nix`

error[E0432]: unresolved import `nix::sched`
  --> test/test_mount.rs:20:14
   |
20 |     use nix::sched::{unshare, CloneFlags};
   |              ^^^^^ could not find `sched` in `nix`

error[E0432]: unresolved imports `nix::sys::stat`, `nix::sys::stat`
   --> test/test_mount.rs:21:19
    |
21  |     use nix::sys::stat::{self, Mode};
    |                   ^^^^   ^^^^ no `stat` in `sys`
    |                   |
    |                   could not find `stat` in `sys`
    |
....
..
```

**Comment by SteveLauC** [comment]
Try:

```sh
$ cargo t --all-features
```

to enable things that are feature-gated

**Comment by carlosb1** [comment]
Thanks!, it works, I got in the first execution a flaky test (Others worked well)
```
test test_fcntl::linux_android::test_ofd_write_lock ... FAILED
```
we can include some issue about this if it happens again...

Do you think it can be useful to add a small description about how to test it in the README.md? I can do the PR myself. 

Thanks for your help

**Comment by SteveLauC** [comment]
> test test_fcntl::linux_android::test_ofd_write_lock ... FAILED

This test passed on my Linux host, kinda weird

-----

> we can include some issue about this if it happens again...
>
> Do you think it can be useful to add a small description about how to test it in the README.md?

It would be nice if we document this under the [`testing` section in `CONTRIBUTING.md`](https://github.com/nix-rust/nix/blob/master/CONTRIBUTING.md#testing)
