### ISSUE TITLE
Question about how the code is formatted

### ISSUE THREAD

**Issue by carlosb1** [nix-rust/nix#2154]
I use VIM and it runs rust fmt every time that I save a file... It reformat all the code.. I am not sure which format we are using, it seems manual.

**Comment by SteveLauC** [comment]
I am actually not sure about this, will `cargo fmt` behave differently even for the same code?

I tried `cargo fmt` on the latest master branch and it changed nothing:

```sh
$ git clone https://github.com/nix-rust/nix.git
$ cd nix
$ cargo fmt
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by carlosb1** [comment]
I close this.. it seems something related with my configuration.

**Comment by SteveLauC** [comment]
> I think cargo fmt and rustfmt are working different.. I saw that we have a rustfmt.toml, I don't know it cargo fmt uses this configuration.

Weird, `cargo fmt` will use that `rustfmt.toml` file IIRC
