### ISSUE TITLE
Should we add a `rust-toolchain.toml` to pin the toolchain to the MSRV

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#2160]
[This](https://github.com/nix-rust/nix/pull/2142#issuecomment-1742228414)

> You'll have to raise MSRV to 1.69.0 to use CStr::from_byte_with_nul.

makes me realize that our contributors are probably not using the same toolchain as our CI environment, which may confuse them a little bit when encountering CI failures that didn't happen on their local machine.

If we pin Nix's toolchain to the MSRC and keep it in sync with our CI,  our contributors can find the issue early and fix it, which would make our contributing experience better

**Comment by asomers** [comment]
I'm inclined against it.  We ought to work with every rust version, and the rust-toolchain.toml file might end up locking us down.  Plus, the Redox build won't even work on MSRV.

**Comment by SteveLauC** [comment]
> We ought to work with every rust version, and the rust-toolchain.toml file might end up locking us down. Plus, the Redox build won't even work on MSRV.

Get it, makes sense to me, close this issue
