### ISSUE TITLE
Consider enabling the `unsafe_op_in_unsafe_fn` lint

### ISSUE THREAD

**Issue by Jan561** [nix-rust/nix#2165]
This lint forces the user to use `unsafe` blocks even inside `unasfe` functions.

This lint makes it easier for maintainers to spot the operations that are causing unsafety, and provide an opportunity for contributors to explain why this operation is safe, given the additional guarantees the caller has to uphold.

This lint is currently allowed by default, but [this will change in edition 2024](https://github.com/rust-lang/rust/pull/112038).

References:

- Lint docs: https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-op-in-unsafe-fn
- Beta lint docs: https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint/builtin/static.UNSAFE_OP_IN_UNSAFE_FN.html
- RFC: https://github.com/rust-lang/rfcs/blob/master/text/2585-unsafe-block-in-unsafe-fn.md
- Tracking Issue: https://github.com/rust-lang/rust/issues/71668

**Comment by SteveLauC** [comment]
Seems to be a reasonable change to me
