### ISSUE TITLE
FreeBSD  nix::sys::event::Kqueue access to inner type

### ISSUE THREAD

**Issue by eesekaj** [nix-rust/nix#2183]
An important functionality is missing in 0.27 for Kqueue.

1) **"field `0` of `Kqueue` is private"** 
There is no way it is possible to close the fd of the kqueue (OwnedFd should do it but in some cases it a raw fd is needed). as_raw_fd() is needed.
2) An access to the inner type (a raw fd) is needed otherwise it breaks functionality of programs which depends on this functionality. Some programs uses fd number to identify the instance when there are multiple sources.

`pub struct Kqueue(OwnedFd);
pub struct Epoll(pub OwnedFd);`
It would be great to have the same for KQueue.

**Comment by SteveLauC** [comment]
Kinda similar to #1998 

Would implementing `AsFd` for `Kqueue` solve the problem for your use case?

```rs
impl std::os::fd::AsFd for Kqueue {
    fn as_fd(&self) -> BorrowedFd<'_> {
        self.0.as_fd()
    }
}
```

> Some programs use fd number to identify the instance when there are multiple sources.

`BorrowedFd` itself is not `PartialEq`, but we can call `as_raw_fd()` on it

-----

Maybe we should also do this to `Epoll`, cc @JonathanWoollett-Light

**Comment by asomers** [comment]
Why is there ever a problem for close?  Are you trying to close the underlying file descriptor without dropping the struct?  I don't know of any good reasons to do that.

**Comment by SteveLauC** [comment]
I believe `impl From<Kqueue> for OwnedFd` would fix this issue, and why this? To be consistent with the std:

```rs
impl From<ChildStderr> for OwnedFd
impl From<ChildStdin> for OwnedFd
impl From<ChildStdout> for OwnedFd
impl From<File> for OwnedFd
impl From<PidFd> for OwnedFd
impl From<TcpListener> for OwnedFd
```

**Comment by eesekaj** [comment]
I was away for a while due to some problems.

The developers (including me) decided to stop using nix crate in our projects and use libc crate only, to avoid abstractions like libc -> nix -> own abstraction. Also taking into account that the some implementations in nix crate not what is required.

Thank you.
