### ISSUE TITLE
Enable most macos functions on all of apple_targets

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#2238]
A quick search through libc shows that there's only one function we use that's defined on macos but isn't defined on tvos, watchos, and ios as well: `clock_settime`.  Even that, I suspect, is a mistake, given that `clock_gettime` is defined for all of them.
We should replace `#[cfg(target_os = macos)]` with `#[cfg(apple_targets)]` everywhere.
Honestly, I don't know why Apple needs so many different Rust targets.

**Comment by SteveLauC** [comment]
From this PR [Add tvOS and watchOS support, identical to iOS support](https://github.com/rust-random/getrandom/pull/317), iOS, tvOS, and watchOS are the same thing, though I have no idea how can we test whether `clock_settime` is available on iOS, libc does not have a CI for it

**Comment by SteveLauC** [comment]
Well, it seems that this symbol is not available on iOS/tvOS/watchTV, from the [PR](https://github.com/rust-lang/libc/pull/2496) that added it for macOS:

> Looking at [time.h for macOS 11.5](https://opensource.apple.com/source/Libc/Libc-1439.141.1/include/time.h.auto.html) clock_settime still doesn't seem to be exported for iOS. Declaring it only for macOS (using https://github.com/rust-lang/libc/pull/2208 as an example of how).

And I checked the apple's latest libc(Libc-1534.40.2), still, [no support for iOS/tvOS/watchOS](https://github.com/apple-oss-distributions/Libc/blob/c5a3293354e22262702a3add5b2dfc9bb0b93b85/include/time.h#L241-L244)
