### ISSUE TITLE
listen does not allow specifying a negative backlog

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#2264]
The `listen` function, in C, takes a "backlog" argument as an `int`.  It normally must be positive.  However, it may be ngative:
* On FreeBSD, since version 2.2, to use the maximum value
* On Linux, as an undocumented feature, to use a default value, at least according to @devnexen .

But when `listen` was added to Nix in change f85e9bfbe5bfef4d8ce5985d29d9a173aa4d5fb0 , the backlog argument's type was specified as `usize`, which precludes negative values.  It also will rollover at `i32::MAX_VALUE` with unpredictable consequences.

**Comment by asomers** [comment]
See https://github.com/rust-lang/rust/pull/97963 for a discussion of the behavior on Linux.

**Comment by SteveLauC** [comment]
So we know that on FreeBSD, [a negative backlog or a value bigger than the max one means the default value](https://github.com/freebsd/freebsd-src/blob/e7d02be19d40063783d6b8f1ff2bc4c7170fd434/sys/kern/uipc_socket.c#L1069). And from that PR, Linux will see `-1` as the default value, what about other negative values, will they also be seen the default value?

Maybe we should use a wrapper type, just like the one introduced in #1876

**Comment by SteveLauC** [comment]
Ok, from the Linux source code, they [directly cast the `backlog` argument from `int` to `unsigned int`](https://github.com/torvalds/linux/blob/c7402612e2e61b76177f22e6e7f705adcbecc6fe/net/socket.c#L1874-L1875), for a `somaxconn` of value 4096, all the negative values will be bigger than it and then set to it:

> This behavior depends on the value of `somaxconn`, so it is different from the FreeBSD one, we should probably not use other negative value

```
int __sys_listen(int fd, int backlog)
{
	struct socket *sock;
	int err, fput_needed;
	int somaxconn;

	sock = sockfd_lookup_light(fd, &err, &fput_needed);
	if (sock) {
		somaxconn = READ_ONCE(sock_net(sock->sk)->core.sysctl_somaxconn);
		if ((unsigned int)backlog > somaxconn)
			backlog = somaxconn;

		err = security_socket_listen(sock, backlog);
		if (!err)
			err = READ_ONCE(sock->ops)->listen(sock, backlog);

		fput_light(sock->file, fput_needed);
	}
	return err;
}
```

**Comment by devnexen** [comment]
Note: [openbsd](https://github.com/rust-lang/rust/commit/ce5af1c9bc5e5010d214be7f02794aadc5b2c6a1) could eventually be added in some months or later.
