### ISSUE TITLE
mkdev

### ISSUE THREAD

**Issue by arcnmx** [nix-rust/nix#227]
Is this meant to be an implementation of `makedev(3)`? glibc's makedev on my machine works something like:

``` rust
fn gnu_makedev(major: u64, minor: u64) -> u64 {
    (minor & 0xff) | ((major & 0xfff) << 8) |
        ((minor & !0xff) << 12) | ((major & !0xfff) << 32)
}
```

... which is required in order to create a `dev_t` for `nix::sys::stat::mknod`

**Comment by carllerche** [comment]
I'm not really following the question :). Could you explain more what you mean?

**Comment by arcnmx** [comment]
Um, I guess the question is... What is `mkdev` and how is it meant to be used? My assumption is that it's meant to be an implementation of `makedev(3)`, but if so it's wrong on Linux/glibc.

**Comment by carllerche** [comment]
Ah yes... you are correct :) It is most likely wrong on linux/glibc then :( Yuck. It is defined in a header vs. an FFI function on linux as well?

**Comment by carllerche** [comment]
This highlights the need for having some sort of testing strategy to ensure cross platform correctness as well...

**Comment by kamalmarhubi** [comment]
> This highlights the need for having some sort of testing strategy to ensure cross platform correctness as well...
:+1:

**Comment by Susurrus** [comment]
`mkdev` no longer exists and there is just `makedev` now.
