### ISSUE TITLE
Consider using a command runner to wrap the commonly used commands

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#2271]
Since most commands Nix uses are not standard `cargo` commands, I suggest we use a command runner like [just](https://github.com/casey/just) or [make](https://www.gnu.org/software/make/manual/make.html) to wrap them to avoid typing them over and over again.

> "are not standard `cargo` commands"
>
> By this, I mean they need some extra arguments

Currently and personally, the most helpful use case would be to check if an item is gated with the correct feature, to do this, you have to open a Nix doc with the following command:

```sh
$ RUSTDOCFLAGS='--cfg docsrs' cargo +nightly doc --all-features --no-deps --open
```

It would be really nice if we could do it with:

```sh
$ just doc --open
```

Other use cases can be:

```
# run tests
$ just test    # cargo test --all-features

# run checkds
$ just check   # run the commands that our CI involves to check the code
```

**Comment by YJDoc2** [comment]
Hey, do you have any specific requirements for this? I'd like to work on this if it fine.
Also a suggestion : from personal experience, just is more easy-to-use and maintain compared to makefile ; with the slight drawback of users need to install it separately.

**Comment by SteveLauC** [comment]
> I'd like to work on this if it fine.

Thanks for your interest!

This is just a proposal, I would like to hear @asomers's thought before adding it to Nix:)

**Comment by asomers** [comment]
I've never gotten into the habit of using any of those.  But I'd be willing to give it a try for Nix.
