### ISSUE TITLE
Group::from_name misaligned pointer dereference 

### ISSUE THREAD

**Issue by anonkey** [nix-rust/nix#2304]
Hello,
I'm on MacOS Sonoma on M1 processor

I've a panic only happening in dev not in release on this function call :

```rust
 let group = Group::from_name(group)?;
```

Result:
```
thread 'main' panicked at /Users/key/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.27.1/src/unistd.rs:3794:16:
misaligned pointer dereference: address must be a multiple of 0x8 but is 0x14f809a09  
```

I tried some flags : -C overflow-checks -C debug-assertions=on

But nothing change i can't figure out what's happening

Have any clue ?

Thanks

**Comment by SteveLauC** [comment]
If this is a known bug and we know how to fix it, why not file a PR to get it resolved?

**Comment by anonkey** [comment]
> If this is a known bug and we know how to fix it, why not file a PR to get it resolved?

I was wondering why too.

I tried to apply the fix but since i have some crates who uses another version it seems to not be compatible, i'll dig further asap

**Comment by SteveLauC** [comment]
We do have a test for this function, but it is [only enabled on Linux](https://github.com/nix-rust/nix/blob/0dfcf3228489a5060a53e69783a1eea6f43b11a9/src/unistd.rs#L3572).

I am thinking about adding a test for `Group::from_gid()` and `Group::from_name()` through the `wheel` group on macOS and possibly other BSDs? (As this group came from BSD)

```rs
    use nix::unistd::Group;

    let wheel = Group::from_name("wheel").unwrap().unwrap();
    assert_eq!(wheel.name, "wheel");
    let wheel_id = wheel.gid;

    let wheel = Group::from_gid(wheel_id).unwrap().unwrap();
    assert_eq!(wheel.gid, wheel_id);
    assert_eq!(wheel.name, "wheel");
```

Unless it is removed deliberately, this group should exist.

**Comment by asomers** [comment]
> If this is a known bug and we know how to fix it, why not file a PR to get it resolved?

I mean that it's a known bug now, now that @anonkey reported it.

**Comment by SteveLauC** [comment]
> I mean that it's a known bug now, now that @anonkey reported it.

Ohh, I am sorry that I misunderstood it
