### ISSUE TITLE
`PtyMaster` missing `AsFd` implementation

### ISSUE THREAD

**Issue by yshui** [nix-rust/nix#2354]
Many nix functions take `impl AsFd` now, but there is no way to get a `AsFd` from `PtyMaster` without going through unsafe.

Is this an intentional design decision?

**Comment by SteveLauC** [comment]
> but there is no way to get a AsFd from PtyMaster without going through unsafe.
>
> Is this an intentional design decision?

It is not done on purpose, and it is indeed something we should do, so PR welcomes (considering it is easy to fix) :)

**Comment by SteveLauC** [comment]
Close as completed in #2355
