### ISSUE TITLE
O_PATH exists on freebsd 14 - could we add it?

### ISSUE THREAD

**Issue by TheJonny** [nix-rust/nix#2361]
According to the manpages, FreeBSD now has O_PATH:
https://man.freebsd.org/cgi/man.cgi?query=open&apropos=0&sektion=0&manpath=FreeBSD+14.0-STABLE&arch=default&format=html
 
probably only adding freebsd in the `[cfg]` breaks to much on older releases?

https://github.com/nix-rust/nix/blob/391a3647926e5aa9a199cc0af591ca1cf8d5544f/src/fcntl.rs#L154

**Comment by asomers** [comment]
It shouldn't break the build for anybody who doesn't actually use that symbol even on older versions of freebsd. We can certainly add this and we'll do it on a patches welcome basis. You will probably need to add the symbol to the libc crate first.
