### ISSUE TITLE
linkat doesn't support AT_EMPTY_PATH, making it incompatible with O_TMPFILE

### ISSUE THREAD

**Issue by vlovich** [nix-rust/nix#2362]
If you want to linkat a file created with O_TMPFILE and without O_EXCL, then you need to pass an empty path for oldpath, the O_TMPFILE fd, and `AT_EMPTY_PATH`. However, the linkat flags are an enum and don't support AT_EMPTY_PATH to be provided.

The alternate workaround is to blindly assume that the proc filesystem is mounted (& mounted at /proc) & construct a path to the O_TMPFILE fd with follow symlinks set to true.

**Comment by SteveLauC** [comment]
> However, the linkat flags are an enum and don't support AT_EMPTY_PATH to be provided.

Try bump your Nix dependency to 0.28.0, you can specify `AT_EMPTY_PATH` now

**Comment by SteveLauC** [comment]
Close this issue but feel free to reopen it if you think it is still not resolved
