### ISSUE TITLE
RecvMsg.cmsg() should check MSG_CTRUNC

### ISSUE THREAD

**Issue by agrover** [nix-rust/nix#2400]
If the cmsg buffer is too small, MSG_CTRUNC will be set in the header flags. This should be checked before returning `CmsgIterator`, or else the iterator might return invalid data.

**Comment by SteveLauC** [comment]
Hi, that indeed should be checked, do you have a good interface for this change in mind?

**Comment by agrover** [comment]
> Hi, that indeed should be checked, do you have a good interface for this change in mind?

I think the simplest thing, although an API change, would be to change `RecvMsg::cmsgs()` to return a `Result<CmsgIterator>` instead of a `CmsgIterator`, and return an error if `MSG_CTRUNC` was set.
