### ISSUE TITLE
Test `statfs_call()` fails on macOS because `statfs()` and `statvfs()` report different number of i-nodes

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#2411]
Sometimes, test `statfs_call()` fails in our macOS CI, e.g., [this one](https://github.com/nix-rust/nix/actions/runs/9143853411/job/25141049909):

```
failures:

---- sys::test_statfs::statfs_call stdout ----
thread 'sys::test_statfs::statfs_call' panicked at 'assertion failed: `(left == right)`
  left: `1609964262`,
 right: `1609964300`', test/sys/test_statfs.rs:47:5
```

It failed in [this line](https://github.com/nix-rust/nix/blob/ec4beb5a2229159021298d56af16e18a9151fb4e/test/sys/test_statfs.rs#L47), where `statfs()` and `statvfs()` were reporting different number of i-nodes.

**Comment by asomers** [comment]
That's weird.  That line checks the total number of inodes on the file system.  That should never change, at least on a traditional file system like UFS.  But apparently it can change here.  I wonder if it was /dev or one of the real file systems?

**Comment by SteveLauC** [comment]
That test checks 4 paths, according to the output of `mount` on my mac, they refer to:

```rs
#[test]
fn statfs_call() {
    check_statfs("/tmp"); // refers to the file system mounted at `/`
    check_statfs("/dev"); // refers to the file system mounted at `/dev`
    check_statfs("/run"); // will be skipped since this directory does not exist
    check_statfs("/");    // refers to the file system mounted at `/`
}
```

> I wonder if it was /dev or one of the real file systems?

So yes, it indeed checks `/dev` though I am not sure if it is the one that is causing the failure since they all run in 1 test.

**Comment by asomers** [comment]
I think we should just remove the check for number of inodes.  After all, our goal isn't to test statvfs itself, just to test that our bindings to it are doing the right thing.

**Comment by SteveLauC** [comment]
> I think we should just remove the check for number of inodes. After all, our goal isn't to test statvfs itself, just to test that our bindings to it are doing the right thing.

Yeah, let me remove it.
