### ISSUE TITLE
warn that nix::sys::signalfd::siginfo is not siginfo_t

### ISSUE THREAD

**Issue by lolbinarycat** [nix-rust/nix#2426]
doing C ffi (expecially with signals) often involves a lot of type punning.  i used `signalfd::siginfo` in the type signature of a signal handler, since it seemed to have the fields missing from `libc::siginfo_t`.  at first it seems to work, since the first few fields are the same, but the rest of the fields aren't right.  for example, on my system, ssi_tid was getting filled in with the value of si_fd.

just a single line of documentation should do it:
> this corrosponds to the [signalfd_siginfo](https://linux.die.net/man/2/signalfd) type in C. note that this is different from the [siginfo_t](https://linux.die.net/man/2/sigaction) type.  the fields have similar meanings, but they may have different layouts.

**Comment by SteveLauC** [comment]
Hi, would you like to elaborate a bit on what the problem is? I don't quite get it, because in my understanding they are 2 different types used in 2 different things, `signal_siginfo` for `signalfd()`, `siginto_t` for `sigaction()`, why passing one type to the other interface?

**Comment by SteveLauC** [comment]
> warn that nix::sys::signalfd::siginfo is not siginfo_t

Are you saying that we should warns users that they have a similar name but are 2 different types in the documentation?
