### ISSUE TITLE
SOCK_NONBLOCK should re-export libc::SOCK_NONBLOCK

### ISSUE THREAD

**Issue by jamperry** [nix-rust/nix#244]
I believe there is a bug for SOCK_NONBLOCK as the value is not the same for all architectures so will break if it's used on a non-x86 architecture - like MIPS. For example the flag value is 128 on MIPS.

**Comment by jamperry** [comment]
I just noticed that you have a dependency to `libc`. I submitted a PR to add SOCK_NONBLOCK and SOCK_CLOEXEC flags to `libc`  so you can potentially reference them and don't have to split your code into different architectures.

**Comment by kamalmarhubi** [comment]
Thanks for taking a look. Bringing in the value from `libc` is probably the right thing to do.

**Comment by jamperry** [comment]
Alex has already merged the change into `libc` so I can submit a PR to you - hopefully tonight if I get time.

**Comment by kamalmarhubi** [comment]
There's no release out with it yet, from what I could see.

**Comment by kamalmarhubi** [comment]
@jamperry I just checked, both your commits made it into libc 0.2.6 which is out.

**Comment by Susurrus** [comment]
@jamperry Any interest in filing a PR for this? Seems pretty straightforward since the constant is properly defined in libc.

**Comment by Susurrus** [comment]
I believe this is resolved as of f067e73.

**Comment by kristate** [comment]
@kamalmarhubi @Susurrus
My apologies, it seems that `SOCK_NONBLOCK` does not exist in darwin.
I will stick to using `fcntl()` and friends, thanks.

**Comment by kristate** [comment]
@kamalmarhubi @Susurrus
Now I'm curious: `nix::sys::socket::socket` provides a fourth parameter that calls `fcntl()` but seemingly does not support macos. Opened an Issue (#861) for clarification. thanks.
