### ISSUE TITLE
can we use this library to do fuse(file systems in user space)?

### ISSUE THREAD

**Issue by vrn21** [nix-rust/nix#2455]

**Comment by SteveLauC** [comment]
Nix does not provide bindings or further Rusty interfaces of libfuse, you should use something like [fuser](https://github.com/cberner/fuser/tree/master) instead.

**Comment by asomers** [comment]
Or if you want an `async` fuse server, use [fuse3](https://docs.rs/fuse3/latest/fuse3/)

**Comment by SteveLauC** [comment]
Close as the question has been answered, feel free to reopen it if you think it is not resolved yet.
