### ISSUE TITLE
`recvmsg` should take `&mut [u8]` instead of `&mut Vec<u8>` for cmsg_buffer

### ISSUE THREAD

**Issue by erenon** [nix-rust/nix#2523]
Currently, `recvmsg` takes a `mut cmsg_buffer: Option<&'a mut Vec<u8>>` argument. This potentially forces the caller to allocate a right-sized Vec (or keep one around), though `recvmsg` implementation immediately produces a slice of the vector, and never uses it as a vector.

What's the reason for having Vec on the interface? Could we have a `&mut [u8]` instead? That'd allow the called to put the buffer onto the stack.

**Comment by asomers** [comment]
If you look at the commit that introduced the `&mut Vec` argument, 2643afc22f0d76c01b28f12da6195047b2db35de, you'll see that it _did_ use `cmsg_buffer` as a Vec, to set its len.  It was a later commit, 482a6b10460aa8121c440b01a83511d29b132412, that removed the `set_len` operation.  So probably the signature can be changed now.  Would you care to prepare a PR and test it?

**Comment by erenon** [comment]
Possible fix prepared: https://github.com/nix-rust/nix/pull/2524
