### ISSUE TITLE
Run tests in processes rather than threads with `cargo nextest`

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#2527]
Some tests modify process-wide stuff like signal handler, so we use these locks

https://github.com/nix-rust/nix/blob/70f8fe084a21047278beaaae1ddd0c372d05dfee/test/test.rs#L63-L80

to sequentialize them, TIL that [`cargo nextest` will run tests in processes](https://github.com/rust-lang/rust/issues/47506#issuecomment-1655503393) rather than threads, perhaps this can help us get rid of these locks and potentially fixes [some weird test failures](https://github.com/nix-rust/nix/issues/2438).

**Comment by asomers** [comment]
cargo-nextest is cool, but I don't think that we should rely on it.  Even if we use it during CI, we should also ensure that "cargo test" works too.

**Comment by SteveLauC** [comment]
> we should also ensure that "cargo test" works too.

Makes sense, closing the issue.
