### ISSUE TITLE
Use enums for enumeration constants

### ISSUE THREAD

**Issue by fiveop** [nix-rust/nix#254]
Just like we use bitflags! for flags, we could use enums for enumeration constants. They would provide a zero cost, type safe abstraction over the current primitive type constants.

A (partial) list of places to use enums:
- [ ]  `sys::mman::MADV_*`
- [ ]  `sys::quota::Q_*`
- [ ]  `sys::signal::SIG*`

**Comment by kamalmarhubi** [comment]
:+1:

**Comment by kamalmarhubi** [comment]
Added a task list.

**Comment by kamalmarhubi** [comment]
Synonyms will not be allowed as variants. This results in [`E0081`](https://doc.rust-lang.org/error-index.html#E0081):

```rust
enum Foo {
    Bar = 0,
    Baz = 0,
    Quux = 1,
}
```
―[playground](http://is.gd/WeOZbd)

**Comment by kamalmarhubi** [comment]
We may be able to do something like this:

```rust
pub enum Foo {
    BAR = 0,
    QUUX = 1,
}
use Foo::*;

pub const BAZ: Foo = BAR;
```
―[playground](http://is.gd/2cbXJD)

(Note ability to pattern match using `BAZ`!)
