### ISSUE TITLE
EventFd has no conversion from OwnedFd

### ISSUE THREAD

**Issue by chadaustin** [nix-rust/nix#2561]
We pass raw fds into a Rust program via FFI, unix domain sockets, and inheritance. There's no way to use `EventFd` in those situations because I don't see even an unsafe API to convert `OwnedFd` into `EventFd`.

Since it's unsafe, maybe a `From` instance is not appropriate, but perhaps `EventFd::from_fd`?

What do you think?

**Comment by SteveLauC** [comment]
[Std implements `From<OwnedFd>` for almost all the owned fd types](https://doc.rust-lang.org/stable/std/net/struct.TcpListener.html#impl-From%3COwnedFd%3E-for-TcpListener), which indeed confuses me. Perhaps we can define a trait like:

```rust
pub trait FromOwnedFd {
    unsafe fn from_owned_fd(fd: OwnedFd) -> Self;
}
```

Just like the [`FromRawFd`](https://doc.rust-lang.org/stable/std/os/fd/trait.FromRawFd.html) trait, does this sound good?
