### ISSUE TITLE
Add CI for ARM and make it pass

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#258]
This could be done similarly to libc using QEMU: https://github.com/rust-lang-nursery/libc/blob/master/ci/README.md#qemu

**Comment by posborne** [comment]
I have started working on this by taking the ci contents from libc and modifying to work with nix.  Hopefully have a PR up soon -- I'll probably wrap in fixes in the PR as well so the build is green (seperate commits).

**Comment by kamalmarhubi** [comment]
@posborne that's awesome! Did you see [rust-everywhere](https://github.com/japaric/rust-everywhere)? I saw it go by on /r/rust yesterday. It sets up the ARM QEMU stuff on travis.

**Comment by posborne** [comment]
Hmm, I'll have to look at rust-everywhere a bit more -- Seems like the main qemu bit is here which is not really revelatory: https://github.com/japaric/rust-everywhere/blob/master/ci/script.sh#L24.  Made it pretty far last night but bumped into some issues discovering tests: https://github.com/rust-lang/cargo/issues/1924.  I can probably hack around that in the short term.

With nix, we are using unittests in the source itself whereas libc has a separate binary that is executed that performs most testing.  I think what we do with nix is reasonable, it just means that we need to do a little more work to figure out which cross-compiled executables need to be executed in various environments.

The alternative would be to setup a working rust/cargo in the target environment, but that would take quite a bit more time and isn't really worth it IMO.

**Comment by kamalmarhubi** [comment]
> With nix, we are using unittests in the source itself whereas libc has a separate binary that is executed that performs most testing. I think what we do with nix is reasonable

Ah that's an interesting difference. I haven't looked too much into what libc does in CI, other than knowing that it's a little annoying to run the tests.

**Comment by posborne** [comment]
Complete! :tada:
