### ISSUE TITLE
Redesign `TimeVal` and `TimeSpec`

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#277]
(`TimeSpec` is being added in #276)

These types aim to provide a nice Rust struct abstraction over the libc types. However, they could be revisited. Some issues I noticed:
- all the `ops` trait impls lose range on the values by calling `num_microseconds()` (`num_nanoseconds()`) for implementation convenience. This reduces the usable range of `TimeVal` to +/- ~300k years (probably ok) and `TimeSpec` to +/- ~300 years (not really ok).
- [`std::Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html) has been stable since 1.3.0, and we should provide interconversions, and probably deprecate all the `hours()` and such methods in favour of converting from a `Duration`. (This brings up version support policy #238.)

**Comment by Susurrus** [comment]
Closing this in favor of #516 which has some more discussion in it.
