### ISSUE TITLE
SaFlag and SigFlag types should be called SaFlags and SigFlags

### ISSUE THREAD

**Issue by fiveop** [nix-rust/nix#290]
However, that would be a breaking change again. Are we doing 0.5.1 or 0.6.0 next? How frequently can we release?

**Comment by kamalmarhubi** [comment]
I just saw that too, annoying! I kind of like to treat 0.x.y versions such that a breaking change moves to 0.x+1.0, but we don't have a policy yet.

**Comment by fiveop** [comment]
Since we are already adding breakings changes again. I would like to fix this now as well. We can release 0.6.0 in a week to get out a new version.

As long as we do not have a fully clean up version, I do not really want to support old 0.x versions. I'd rather release a new 0.x version every other week or so (with breaking changes, which the 0 in front allows).
