### ISSUE TITLE
Build fails with execvpe feature enabled

### ISSUE THREAD

**Issue by alex-gulyas** [nix-rust/nix#306]
Build errors:
- missing `ffi` module in `unistd`
- use of undeclared type `Error::Sys` at `src/unistd.rs:396`

**Comment by felippemr** [comment]
Hi!
I'd like to help you with this issue, how can I get started?

**Comment by fiveop** [comment]
This is already being tackled by #349 at the moment. Though, it is not clear whether that change will get into the tree in its current form. I'd still suggest starting with another bug. In particular the two other issues marked as good-first-bug provide lots of work.

**Comment by kamalmarhubi** [comment]
Removed the labels for now.

**Comment by Susurrus** [comment]
This is still a problem with the current release:
```
   Compiling nix v0.9.0-pre (file:///home/susurrus/Projects/nix)
error[E0433]: failed to resolve. Could not find `ffi` in `super`
    --> src/unistd.rs:1626:13
     |
1626 |             super::ffi::execvpe(filename.as_ptr(), args_p.as_ptr(), env_p.as_ptr())
     |             ^^^^^^^^^^^^^^^^^^^ Could not find `ffi` in `super`

error[E0433]: failed to resolve. Use of undeclared type or module `Error`
    --> src/unistd.rs:1629:13
     |
1629 |         Err(Error::Sys(Errno::last()))
     |             ^^^^^^^^^^ Use of undeclared type or module `Error`

error: aborting due to 2 previous errors

error: Could not compile `nix`.

To learn more, run the command again with --verbose.
```

I just tested all of the other features, and they all work fine at least.
