### ISSUE TITLE
Optional features are not build tested

### ISSUE THREAD

**Issue by alex-gulyas** [nix-rust/nix#308]
Currently none of the available optional features are built by Travis, therefore:
- patches for the optional parts are not tested by Travis (or Homu)
- patches for other parts can silently break the optional parts (see #306, #307)

**Comment by kamalmarhubi** [comment]
Thanks for bringing this up!

I think the right direction will be to break out the optional parts into separate crates. Eg, for signalfd we would want the function in nix-core but the iterator in nix-signalfd (or something like that).

This is still a little undecided. #190 is related.

**Comment by Susurrus** [comment]
Why don't we just enable the features in testing? I don't think this is a good rationale for splitting `nix` into several separate crates.
