### ISSUE TITLE
Add some constants to libc

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#316]
**NB** This issue describes making changes to the [libc](https://github.com/rust-lang/libc) crate, not to nix. The issue is here because these are constants we'd like to use from libc as part of work on #264, but are not yet available in the libc crate.

I've been going through bitflags as part of #315, and taking note of some places where we need to get constants upstreamed.
- [x] `sys::memfd::MFD_*` (rust-lang/libc#836)
- [x] `sys::socket::consts::MSG_*`
- [x]  `sys:socket::consts::SOL_*` (https://github.com/rust-lang/libc/pull/228)

**Comment by posborne** [comment]
I have a PR open for `sys:socket::consts::SOL_*`: https://github.com/rust-lang/libc/pull/228 although those are not flags.

**Comment by kamalmarhubi** [comment]
Definitely add any non-flags up above too. I'm just looking at flags quite closely because of #315.
