### ISSUE TITLE
musl: use of undeclared type name `libc::ucontext_t`

### ISSUE THREAD

**Issue by posborne** [nix-rust/nix#325]
x86_64-unknown-linux-musl should be added to CI.  It is included in the `posborne/rust-cross:x86` docker image.  Discovered this while working on some fixup for the CI stuff.  May be a libc issue.

```
=======================================================
TESTING VERSION: 1.7.0, TARGET: x86_64-unknown-linux-musl
=======================================================
/source/src/ucontext.rs:7:14: 7:30 error: use of undeclared type name `libc::ucontext_t` [E0412]
/source/src/ucontext.rs:7     context: libc::ucontext_t,
                                       ^~~~~~~~~~~~~~~~
/source/src/ucontext.rs:7:14: 7:30 help: run `rustc --explain E0412` to see a detailed explanation
```

**Comment by posborne** [comment]
@kamalmarhubi Can you please label this as appropriate.  I don't seem to have the ability to create new labels.

**Comment by kamalmarhubi** [comment]
@posborne I think you should be able to do this now. I created a "team" and gave it admin access on the repo. Added some labels though!

**Comment by posborne** [comment]
I started looking at things a bit -- there are some legit test problems in ioctl and a few other places.  I started looking more at using [ctest]() to do the types of checks we are doing in some places (some of this need goes away with moving contants to `libc`, but some will likely need to remain).

I ended up bumping into https://github.com/rust-lang/cargo/issues/1430 and decided to take a break.

**Comment by fiveop** [comment]
I made a patch for libc, that adds ucontext for linux-musl ( rust-lang/libc#255 ). That should resolve this.

**Comment by fiveop** [comment]
musl does not implement the functions working on ucontext structs (http://wiki.musl-libc.org/wiki/Open_Issues#ucontext.h), so let's see how far the struct gets us.
