### ISSUE TITLE
nix::sys::socket::InetAddr::from_std ignores sin6_flowinfo and sin6_scope_id

### ISSUE THREAD

**Issue by misuzu** [nix-rust/nix#329]
sin6_flowinfo and sin6_scope_id is essential for link-local addresses.
Related: carllerche/mio#376

**Comment by kamalmarhubi** [comment]
Hi @misuzu! Could you explain a bit more clearly what the issue is about? Is it adding APIs?

**Comment by misuzu** [comment]
@kamalmarhubi 
SocketAddrV6 have flowinfo and scope_id: https://doc.rust-lang.org/std/net/struct.SocketAddrV6.html
InetAddr::from_std only uses address and port so flowinfo and scope_id is lost after conversion: https://github.com/nix-rust/nix/blob/master/src/sys/socket/addr.rs#L44
There is also no way to manually create InetAddr with flowinfo and scope_id.

**Comment by kamalmarhubi** [comment]
Thanks for the clarification! I just opened #335 to fix it.

**Comment by fiveop** [comment]
I suggest @misuzu review's the fixing PR.

**Comment by kamalmarhubi** [comment]
Great idea!
