### ISSUE TITLE
Remove or revamp sys::syscall module

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#341]
This came up in [a comment from @pnkfelix on #339](https://github.com/nix-rust/nix/issues/339#issuecomment-205407123).

This module appears to be Linux specific. It declares

``` rust
extern {
    pub fn syscall(num: Syscall, ...) -> c_int;
}
```

for all architectures, with `Syscall` being architecture dependent alias that is `c_long` on all listed architectures.

On Linux, [`syscall(2)`][syscall] should return a `long`, so this declaration is incorrect. We should switch to using definitions from `libc` and tidy up or remove this module.

Related: #264

**Comment by kamalmarhubi** [comment]
This PR is related: https://github.com/rust-lang/libc/pull/374

**Comment by Susurrus** [comment]
Closed by #747
