### ISSUE TITLE
Sigaction doesn't set the mask

### ISSUE THREAD

**Issue by mkollaro** [nix-rust/nix#355]
This code fails on the assertion, the mask isn't set. The signal handler seems to work fine though.

    let mut mask = signal::SigSet::empty();
    mask.add(signal::SIGCHLD).unwrap();
    let action = signal::SigAction::new(signal::SigHandler::Handler(signal_handler),
                                        signal::SaFlags::empty(),
                                        mask);
    unsafe {
        signal::sigaction(signal::SIGCHLD, &action).unwrap()
    };
    assert!(signal::SigSet::thread_get_mask().unwrap().contains(signal::SIGCHLD).unwrap());

**Comment by fiveop** [comment]
Quoting the man page:

> Additional set of signals to be blocked during execution of signal-catching function.

So you would need to run your assert in the handler.

**Comment by mkollaro** [comment]
Oh, sorry...I misunderstood the manual.
