### ISSUE TITLE
pipe2 doesn't set flags atomically?

### ISSUE THREAD

**Issue by oconnor663** [nix-rust/nix#414]
It looks like the `pipe2` function is implemented as a call to regular `pipe` followed by separate calls to `fcntl` (for compatibility with systems that don't support `pipe2`?). I think that's fine for O_NONBLOCK, but not for O_CLOEXEC. If a multithreaded program forks in between the creation of a pipe and when O_CLOEXEC is set, the child will inherit pipes that it isn't supposed to.

Is it possible to call the real `pipe2` libc function where it's supported, and to fall back to `pipe` only when necessary? I think this is what libstd does.

**Comment by posborne** [comment]
> Is it possible to call the real pipe2 libc function where it's supported, and to fall back to pipe only when necessary? I think this is what libstd does.

I have no objection to this.  Mind opening up a PR?

**Comment by oconnor663** [comment]
I'd love to put it together, but I could use your advice about the right way to do it. Rust's [libstd uses](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/pipe.rs#L33) some kind of [weak binding](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/weak.rs#L78) backed by function called `dlsym`. I'm don't know much about what that function's doing under the covers, but if you think that's the right way to go I'll read more about it. Are there any examples in nix already of doing this kind of capability detection?

**Comment by posborne** [comment]
Personally, at least for the first pass, I am OK only supporting linux 2.6.27+ in nix as long as we make a note that further work would be required to support older kernels.  Alternatively, borrowing that macro/logic from libstd might also be an acceptable solution.

`dlsym` in this context is just seeing if the libc in used contains specific symbols at runtime.

**Comment by oconnor663** [comment]
Interesting, it looks like musl already implements a similar fallback: http://git.musl-libc.org/cgit/musl/tree/src/unistd/pipe2.c

**Comment by fiveop** [comment]
If I understand it, the situation cannot be improved, from where your PR got us. Can we close this now?

**Comment by oconnor663** [comment]
Yep. Closing.

Does `libc` have any plans to support pipe2 on BSD platforms? What's the broader future of detecting this sort of thing dynamically?
