### ISSUE TITLE
Cut Release 0.6.1/0.7.0 (based on semver)

### ISSUE THREAD

**Issue by posborne** [nix-rust/nix#417]
There have been several requests for this in a few places, so I think it's time (or past time).  I can take the lead on cutting this release (probably later tonight).

Any objections?  CC @nix-rust/nix-maintainers

**Comment by fiveop** [comment]
Yes please. If you could document the procedure in RELEASE_PROCEDURE.md, it would be even better.

One think that comes to mind is, that we should ask for a fresh libc release, which we then refer to in Cargo.toml in the release version.

**Comment by kamalmarhubi** [comment]
No objections here. I'll write  up a quick draft of what I did for 0.6.

**Comment by posborne** [comment]
Sounds good.  Didn't get to it last night, but hopefully soon.

**Comment by kamalmarhubi** [comment]
Just checked, and latest libc is missing a couple of definitions. Filed https://github.com/rust-lang/libc/issues/385 to get a new release.

**Comment by posborne** [comment]
Thanks @kamalmarhubi

**Comment by fiveop** [comment]
Now is a good time to do it! I can do it this evening (UTC+2), if it hasn't happend by then.

**Comment by fiveop** [comment]
And we have a release.

**Comment by posborne** [comment]
Thanks for taking the lead on this release @fiveop.  I had good intentions to do some more work on that Nix but it wasn't in the cards.
