### ISSUE TITLE
Build failure in i686 beta

### ISSUE THREAD

**Issue by fiveop** [nix-rust/nix#435]
In recent builds for i686 and rust beta, there have been build failures do to linking problems. See for example:

https://travis-ci.org/nix-rust/nix/builds/165124003
https://travis-ci.org/nix-rust/nix/builds/164470698
https://travis-ci.org/nix-rust/nix/builds/164422919

**Comment by fiveop** [comment]
I tried to recreate the issue on my machine by installing beta-i686-linux-unknown-gnu and running the build. However, the build runs through. This makes investigating the failure difficult.

@posborne, as the (usually) knowledgeable when it comes to builds, do you have any ideas?

**Comment by posborne** [comment]
Hmm, interesting.  Looks like it is failing to link basically everything provided by `std`.  I am suspicious of whether something might have changed with TravisCI but will need to do some more digging to say anything for certain.

**Comment by fiveop** [comment]
For reference: The build has the same problem, if I use the same scripts and environment as libc: https://travis-ci.org/fiveop/nix-rust/jobs/167885171

**Comment by fiveop** [comment]
The build problem occurs since beta went from 1.12.0-beta.6 to 1.13.0-beta.1. The prerelease version was bumped less than a day ago (https://github.com/rust-lang/rust/commit/3ebfbdb3e50bf2d5d9bfe2bfaad6ece86067cd46), so I am suggest waiting for 1.13.0-beta.2, since someone mentioned that there were linker problems in beta and nightly.

**Comment by TimNN** [comment]
This is probably rust-lang/rust#36793, I think.

(This has been fixed by rust-lang/rust#36866 on nightly, however the fix does not seem to have been include in 1.13.0-beta.2)

**Comment by fiveop** [comment]
I suggest ignoring the beta build failure until 1.13.0-beta.3 (or newer) is released, so that work can continue.

**Comment by fiveop** [comment]
The build features do not occur anymore, so we can revert the changes.
