### ISSUE TITLE
Not possible to call kill(pid, 0)

### ISSUE THREAD

**Issue by mkollaro** [nix-rust/nix#441]
According to the man page:

_If sig is 0, then no signal is sent, but error checking is still performed; this can be used to check for the existence of  a process ID or process group ID._

The current signature is `pub fn kill(pid: pid_t, signal: Signal)`, and I think it should use `Option<Signal>`.

**Comment by kamalmarhubi** [comment]
Thanks for the report. This is being handled in #445, which is close to done.
