### ISSUE TITLE
Add tcsetpgrp function

### ISSUE THREAD

**Issue by zethra** [nix-rust/nix#447]
Could the `tcsetpgrp` function please be added?  Thank you.

**Comment by posborne** [comment]
Certainly, would you mind taking a shot at implementing?  I believe this one would be added to [unistd.rs](https://github.com/nix-rust/nix/blob/master/src/unistd.rs).  Probably would want to have `tcgetpgrp` added as well.

Doing this would require two changes:
1. Add the raw FFI definitions to the [libc crate](https://github.com/rust-lang/libc).  This would expose and unsafe interface.
2. Add functions that use these definitions to nix (with a safe interface).

If not, somebody here can probably get to it in time as well.

**Comment by zethra** [comment]
Okay, I'm on it

**Comment by posborne** [comment]
> Okay, I'm on it. Step 1 done.

Excellent, thanks for the update @zethra

**Comment by kamalmarhubi** [comment]
@zethra are you interested in adding it to nix as well? We can walk you through the process!

**Comment by zethra** [comment]
I've added them to my fork of nix. I'm just working on the documentation. But I'll happily except any help you're willing to give!

**Comment by kamalmarhubi** [comment]
Excellent! Feel free to open a PR from your fork and we'll take a look :-)

**Comment by kamalmarhubi** [comment]
I'm doing so poorly at keeping track. You already opened #451. Taking a look.

**Comment by Susurrus** [comment]
This was resolved by #451.
