### ISSUE TITLE
signal::SigFlags should be enum instead of bitflags.

### ISSUE THREAD

**Issue by chaosagent** [nix-rust/nix#459]
http://man7.org/linux/man-pages/man3/pthread_sigmask.3.html

`SigFlags` represents the `how` parameter of pthread_sigmask, which takes 3 mutually exclusive options, which should be represented by an enum. The `SigFlags` name is pretty confusing too, as the underlying value is an option, not a flag.

**Comment by chaosagent** [comment]
Fixing this would require some breaking changes, but I don't know what the policy on that is.

**Comment by kamalmarhubi** [comment]
> Fixing this would require some breaking changes, but I don't know what the policy on that is.

A big part of the motivation for a changelog is to at least make it possible to see what has changed. Pre-1.0 we're fairly happy to make changes for API improvements. This is fixing the semantics of an API and should certainly be allowed, IMO.

**Comment by kamalmarhubi** [comment]
For more on this parameter: http://man7.org/linux/man-pages/man2/sigprocmask.2.html#DESCRIPTION

Certainly agree this should be an enum.

**Comment by fiveop** [comment]
#460 is merged, so this issue can be closed.
