### ISSUE TITLE
No libc::signal

### ISSUE THREAD

**Issue by zethra** [nix-rust/nix#476]
There doesn't seem to be any function in nix that calls `libc::signal` but there is a signal module.  Is this deliberate or has it just not been added yet.  If the latter than should I add it to `nix::sys::signal` ?

**Comment by fiveop** [comment]
It is in all likelihood the latter; probably, because no one needed it yet. If you do, feel free to add it.

**Comment by zethra** [comment]
Okay I will, Thanks.

**Comment by fiveop** [comment]
great

**Comment by Susurrus** [comment]
@zethra I don't believe this was ever implemented, are you still interested in implementing this?

**Comment by zethra** [comment]
Maybe eventually but I've not the time at the moment.
