### ISSUE TITLE
no `EpollFlags` in `nix::sys::epoll`

### ISSUE THREAD

**Issue by hicqu** [nix-rust/nix#479]
I am working on a epoll program. But after I try to import EpollFlags from nix, error reported like this:
error[E0432]: unresolved import `nix::sys::epoll::EpollFlags`
  --> src/task/mod.rs:12:44
   |
12 | use nix::sys::epoll::{EpollOp, EpollEvent, EpollFlags};
   |                                            ^^^^^^^^^^ no `EpollFlags` in `nix::sys::epoll`

how to deal with that?

**Comment by hicqu** [comment]
I checked nix source code in my $HOME/.cargo/.../nix-0.7.0.
I found that there is no EpollFlags but EpollEventKind instead!
So could you offer  a online document of latest released version instead of master branch?
It's very friendly for new comers!

Thanks a lot!

**Comment by fiveop** [comment]
Closed in favour of #482.
