### ISSUE TITLE
How to pass a null ptr to some functions?

### ISSUE THREAD

**Issue by hicqu** [nix-rust/nix#480]
look at this function:

`fn epoll_ctl(epfd: RawFd, op: EpollOp, fd: RawFd, event: &mut EpollEvent)`

if EpollOp == EpollDel, the event could be a NULL in C. But how to pass a NULL ptr to epoll_ctl in rust?

**Comment by fiveop** [comment]
This is a missing feature of our interface. We had a similar problem with `kill` (see #445). Feel free to create a PR to fix this. We will incorporate it, even if it is a breaking change. We should probably check in the new implementation of `epoll_ctl`, whether `event` may be `None` (or `NULL` in C) depending on the other arguments.

**Comment by hicqu** [comment]
OK, I think we can define these two functions in mio. Here is a simple test:

```
/// maybe we could accept these two functions into mio?
fn null_as_mut<T>() -> &'static mut T {
    unsafe { &mut *::std::ptr::null_mut::<T>() }
}

fn null_as_ref<T>() -> &'static T {
    unsafe { & *::std::ptr::null::<T>() }
}

/// simple test below

#[derive(Debug)]
struct T { f: i32, }

fn ref_t(t: &T) {
    // if pass nullptr, segment fault as expected.
    println!("{:?}", *t);   
}

fn mut_t(t: &mut T) {
    // if pass nullptr, segment fault as expected.
    println!("{:?}", *t);   
}

fn main() {
    let mut t: T = T { f: 100 };
    ref_t(&t);  // it's OK.

    mut_t(null_as_mut::<T>());  // segment fault.
    ref_t(null_as_ref::<T>());  // segment fault.
}
```

What do you think?
