### ISSUE TITLE
document EINTR handling for functions like waitpid

### ISSUE THREAD

**Issue by oconnor663** [nix-rust/nix#502]
The standard library wraps calls to `libc::waitpid` so that they automatically retry if it returns EINTR. Should `nix` do the same? This question might apply to a bunch of other system calls too; `waitpid` is just the first one I looked at.

**Comment by posborne** [comment]
Hi @oconnor663, I believe the answer for nix is no.

One of the primary goals for nix providing a more thin wrapping of libc is to not significantly limit where it can be used and not exposing `EINTR` would hide a potential case that some users might want to use.  I also think this retry behavior would be hard to make gel with flags like `WNOHANG` where we definitely would not want the retry behavior.

**Comment by oconnor663** [comment]
Cool, let me know if there's a discussion that's already happened somewhere else, so that I don't clutter things up here.

The man page for `waitpid` say that it returns `EINTR` if "`WNOHANG` was not set and an unblocked signal or a SIGCHLD was caught." So it might be that the `WNOHANG` question is moot. But if we assumed that it could happen, then I think almost all no-hang callers actually _should_ be retying on `EINTR`. The intent of `WNOHANG` is to prevent a long block, but the caller probably doesn't care about the difference between one system call and a few retries, and probably cares a lot about getting the correct result. If the caller doesn't retry, then there's an obscure failure condition on the wait that's almost never going to be tested. (Hopefully there aren't cases where `EINTR` cases more than a few retries? Some sort of local signal DOS attack maybe?)

Though maybe that's totally wrong if it was possible that `EINTR` could mean "your process actually _was_ waited and cleaned up, and retries will either fail or accidentally wait for the wrong child"? I know that file closing has that rule, where either interrupts can't happen at all, or if they do happen the call might nonetheless have succeeded, so you're not supposed to retry.  I'm afraid I don't understand this part of the issue very well.

Would it make sense for `nix` to provide a high level retry wrapper? And maybe for the documentation to call out functions where the majority of callers should be using the wrapper?

**Comment by fiveop** [comment]
I agree with @posborne, and want to clearify that the intent is to provide a idiomatic wrapper that is as thin as possible while providing safe interfaces (if that is possible at all).

We could provide a macro that retries a given function call on `EINTR`. I like the idea.

**Comment by oconnor663** [comment]
After reading http://250bpm.com/blog:12 I have a better idea of the kind of callers who actually need to handle EINTR instead of always retrying it. Good to know.

**Comment by fiveop** [comment]
@oconnor663 Can we close this issue?

**Comment by oconnor663** [comment]
I've retitled this as a docs issue, though my original question is certainly answered, and if you'd prefer to close it out that's fine with me.

**Comment by Susurrus** [comment]
@oconnor663 What kind of documentation is needed that would wrap up this issue? Seems like this is reliant on external docs.

**Comment by oconnor663** [comment]
I guess I was imagining that functions that could return EINTR could be documented as doing that, but maybe that's too platform specific?

**Comment by Susurrus** [comment]
I don't see that as a role `nix` should be doing, as `nix` generally provides thin wrappers around `libc` functionality and defers most documentation to manpages. I think the manpages should be sufficient for consumers of `nix` to understand the necessary error handling. `EINTR` isn't any different than other possible errors so I don't see why it needs to be explicitly called out when the low-level functions make it clear that it occurs in their documentation.

**Comment by oconnor663** [comment]
Makes sense. I'll close this one out.
