### ISSUE TITLE
kill does not allow 0 as a signal

### ISSUE THREAD

**Issue by gcp** [nix-rust/nix#504]
"If sig is 0, then no signal is sent, but error checking is still performed; this can be used to  check
       for the existence of a process ID or process group ID."

signal.rs seems to explicitly disallow the signal value to be 0, i.e.:

```rust
    pub fn from_c_int(signum: libc::c_int) -> Result<Signal> {
        match 0 < signum && signum < NSIG {
```

**Comment by fiveop** [comment]
We have not released it yet, but in the next version you can pass None to `kill` in order to pass no signal. (see #441 and #445).
