### ISSUE TITLE
Provide baud constants for cfsetispeed and family

### ISSUE THREAD

**Issue by berkowski** [nix-rust/nix#514]
`cfgetospeed`, `cfgetispeed`, `cfsetospeed`, and `cfsetispeed` all work with the type `speed_t`, which is aliased to `c_uint`.

However the baud speeds are not their numerical value but system-defined constants.  For example, 9600 on linux is defined as `B9600 = 15`. 

Knowing what these constants are defined as on the target system is required to use these functions, but `nix` provides none and renders these functions unusable without knowledge from outside the crate.

`nix` should either provide aptly named `speed_t` constants that can be used with the baud related functions or an enum type that maps to valid values of `size_t`.

**Comment by posborne** [comment]
Hey @berkowski.  We would definitely prefer to have an enum that matches to the right constants.  Would you be willing to put together a PR for this?

**Comment by berkowski** [comment]
Sure, no problem.
