### ISSUE TITLE
Add support for ppoll()

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#517]
`poll()` is already included, but `ppoll()` would be nice too. Since there's a PR for `pselect()` I figured `ppoll()` would be suitable for inclusion as well.

**Comment by kamalmarhubi** [comment]
@Susurrus it'd certainly be welcome! Any chance you'd be interested in adding it? I could walk you through it if so.

**Comment by Susurrus** [comment]
Yeah, I'd like to get this added, but it looks like I'll first need to add `ppoll()` to libc.

Also, what should the function definition be? Given the consensus in #516 I would like to do:
`fn ppoll(fds: &mut [PollFd], timeout: Duration) -> Result<libc::c_int>`. Does that work?

**Comment by Susurrus** [comment]
I can file an addition PR for #516 that will synchronize everything on using Duration, but I'm assuming the API discrepency will be acceptable in the short term?

**Comment by Susurrus** [comment]
Just filed a PR for this for libc, but it'll probably take a couple of revisions nailing down what platforms actually support this (rust-lang/libc#537).

**Comment by Susurrus** [comment]
Closed by 5d4967ee9af8b2feeffd18534eef433066ad36c5
