### ISSUE TITLE
Any plans for 0.8.0?

### ISSUE THREAD

**Issue by steveklabnik** [nix-rust/nix#519]
It's been five months and almost 200 commits since 0.7.0, just curious if/when 0.8.0 would get cut. Thanks!

**Comment by posborne** [comment]
Yeah, it is overdue.  I think we just go ahead and cut one now.  Thought @kamalmarhubi @fiveop @nix-rust/nix-maintainers ?

**Comment by kamalmarhubi** [comment]
I'm tempted to ask for a libc release, and then there's a tiny improvement we can get to one recently merged PR that I can't find right now :/

**Comment by kamalmarhubi** [comment]
@posborne let's wrap up a few outstanding PRs that are really close, then release? And no later than Friday...

**Comment by kamalmarhubi** [comment]
Ok, I propose we let the following PRs get merged then cut 0.8:
- #518 (`BaudRate` enum), waiting on https://github.com/rust-lang/libc/pull/530 which also looks close
- #520 (`ppoll(2)`), waiting on https://github.com/rust-lang/libc/pull/537 which looks close to done
- #522 (README mentions Rust version requirement)

**Comment by kamalmarhubi** [comment]
Those libc PRs are merged. Asked for a release in https://github.com/rust-lang/libc/issues/539

**Comment by fiveop** [comment]
In the future, anyone of us should feel free to bump the version whenever a few changes have accumulated. Given how we seem to work on this project in spurts, this will not happen more often than once a month anyway :)

**Comment by asomers** [comment]
Can we please wait for the release until after PR #506 finishes?  That PR changes an API that was introduced after 0.7.0.

**Comment by kamalmarhubi** [comment]
Quick status update: libc release is blocked on https://github.com/rust-lang/libc/pull/538 (unrelated but soon-to-be-merged).

**Comment by kamalmarhubi** [comment]
Selfishly going to add #540 and #541 to the blocking list.

**Comment by Susurrus** [comment]
I'd also like to nominate #527 which is done and just waiting on CI to finish.

**Comment by kamalmarhubi** [comment]
@Susurrus I think you'll get your chance: yesterdays' S3 outage delayed https://github.com/rust-lang/libc/pull/538... :-)

**Comment by kamalmarhubi** [comment]
@Susurrus I'm going to push a PR to bump to v0.8.0 now. We'll get your changes in soon. There's no reason we went five months between releases; it's certainly not a policy!

**Comment by Susurrus** [comment]
@kamalmarhubi Ack.

**Comment by kamalmarhubi** [comment]
This is now [tagged](https://github.com/nix-rust/nix/releases/tag/v0.8.0) and [published](https://crates.io/crates/nix/0.8.0). Need to figure out how to get the changelog in the github release page some time.
