### ISSUE TITLE
Remove revents argument from PollFd::new

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#521]
The `revents` field for the `PollFd` struct is an output-only field. Given that it a) isn't public and b) is written to by functions that consume it, it doesn't make sense to have it as an argument for `new()`. That argument will (should?) always be `EventFlags::empty()`.

**Comment by fiveop** [comment]
I don't see a problem with that. Feel free to send a PR.

**Comment by Susurrus** [comment]
Along this same line, why is `PollFd::revents()` return an `Option` type? Since `EventFlags` contains the idea of `None` (as `empty()`), isn't this redundant?

**Comment by fiveop** [comment]
It returns None if revents has a flag set that is not defined (see from_bits method in the bigflags! macro documentation). That should probably not be possible. But this way we are safe.

**Comment by Susurrus** [comment]
Closed by 80453b9139d5a035efaac2e963838676dcd04c37
