### ISSUE TITLE
TRUST CI: x86_64-unknown-freebsd compilation error - Baud Rates

### ISSUE THREAD

**Issue by posborne** [nix-rust/nix#531]
https://travis-ci.org/berkowski/nix/jobs/205534682

CC @berkowski

**Comment by berkowski** [comment]
Looking into this there are a lot of constants defined in `sys/termios.rs` that should use their "upstream" versions from `libc`.  For example we shouldn't be defining

```
const BRKINT  = 0x00000002
```
but instead

```
const BRKINT = libc::BRKINT
```

**Comment by posborne** [comment]
Agreed.  We have been working on updating these, but there are clearly some that have not yet been updated.

**Comment by Susurrus** [comment]
This issue should be resolved with #527 which switches to using clib for all constants.

**Comment by Susurrus** [comment]
This has also been fixed in #536.
