### ISSUE TITLE
TRUST CI: mips(el)-unknown-linux-gnu Multiple Tests Failing

### ISSUE THREAD

**Issue by posborne** [nix-rust/nix#533]
https://travis-ci.org/berkowski/nix/jobs/205534694

**Comment by berkowski** [comment]
Started on a PR but ran into lots of incorrectly defined constants (same with #534).  Instead of throwing `#cfg` blocks everywhere I started a rust-lang/libc#543 to fill in some of the constants missing from `libc`.  If that lands it should ease things here.

**Comment by Susurrus** [comment]
This has been resolved for a while now I think as these are now Tier 1 platforms.
