### ISSUE TITLE
PTRACE_O_TRACESYSGOOD flag is interpreted as part of a signal

### ISSUE THREAD

**Issue by chaosagent** [nix-rust/nix#550]
In sys::wait, if waitpid returns a status originating from ptrace and PTRACE_O_TRACESYSGOOD is set, the seventh (0x80) bit of the status will be flipped. This causes status parsing to fail.

The flag technically isn't a ptrace event either, but I feel like that would be the best place to put it. Alternatively, a TRACESYSGOOD-status could be its own unique kind of status, or a boolean entry could be added in WaitStatus::Stopped to mark it.

I've opened a pull request simply ignoring the bit for now (#549)

**Comment by kamalmarhubi** [comment]
@chaosagent thanks for the report. What's the platform / architecture this happens on?

**Comment by chaosagent** [comment]
This only happens on Linux, and I can confirm it happens on x86_64, but the Linux man page says that it might not work on all platforms.

The name of the flag is PTRACE_O_TRACESYSGOOD btw; I'll changethe issue title to reflect.
