### ISSUE TITLE
nix's Cargo.toml refers to the git head version of libc

### ISSUE THREAD

**Issue by raphaelcohn** [nix-rust/nix#557]
The 0.8.0 release of nix refers to the git head version of libc, rather than a version (eg "0.2.x"). I my builds, this makes nix's reexport of libc incompatible with other creates I'm using...

**Comment by fiveop** [comment]
We failed to update that line, when making the release. I guess a simple 0.8.1 release with the correct libc version, should fix this.

**Comment by kamalmarhubi** [comment]
Ah this was my fault as I made the release. I actually got it right in the tagged version; I must have failed at the publish step. I'll take a look tomorrow or Monday if nobody else has by then. Sorry about this!

**Comment by raphaelcohn** [comment]
That's OK. I did a fork and tried out a change to a specific libc version, and it seems to fix the issue I was experiencing.

**Comment by kamalmarhubi** [comment]
@raphaelcohn I don't actually see this in the package on crates.io. Can you verify in a new project, and check that you don't have any overrides in `.cargo/config`?

**Comment by raphaelcohn** [comment]
Which package on crates.io? I'm a bit befuddled.

**Comment by kamalmarhubi** [comment]
@raphaelcohn https://crates.io/crates/nix

Please do let us know if there's any issue with the latest released version.

**Comment by Susurrus** [comment]
This shouldn't actually be possible, to release a crate that doesn't have a version declared for all dependencies. Git versions and local paths aren't allowed for released crates. @raphaelcohn Are you using the current git or are you pulling from crates.io.

**Comment by kamalmarhubi** [comment]
In that case, I'm closing this. Please reopen if you see something though!
