### ISSUE TITLE
Additional examples for ioctl

### ISSUE THREAD

**Issue by beamspease** [nix-rust/nix#573]
Some additional examples for ioctl would be very helpful. It's taken me a bit to figure out how I'm supposed to do BLKSZGET. Thanks.

**Comment by Susurrus** [comment]
Since you've already figured out how to use ioctl for `BLKSZGET` and have code for it, would you be willing to submit something as an example?

**Comment by Susurrus** [comment]
@beamspease Just wanted to ping you on this. Would love to get your examples into our documentation.

**Comment by roblabla** [comment]
I'm not sure what `BLKSZGET` is, but for `BLKBSZGET`, here's how it goes.

You can see [here](https://github.com/torvalds/linux/blob/c6b1e36c8fa04a6680c44fe0321d0370400e90b6/include/uapi/linux/fs.h#L213) that it's a *read* ioctl. Meaning the ioctl will return stuff to us.

From this, we know the ioctl should be written like so :

```rust
/// Get block device soft block size
ioctl!(read blkbszget with 0x12; 112; size_t)
```

**Comment by Susurrus** [comment]
I'd love to get this written up as a proper example. Something like.
```
/// To use the `ioctl!` macro, you'll need to reference existing documentation. Many macros are defined 
/// using the `IO()`, `IOR()`, and `IOW()` macros. This is handled by the `ioctl!` macro in `nix`, but the
/// arguments to it need to be passed in to `ioctl!`.
///
/// As an example, the BLKBSZGET ioctl is defined as `#define BLKBSZGET _IOR(0x12,112,size_t)`.
/// Because it uses the `IOR()` macro, we can tell it's a `read` ioctl. So to write this using `ioctl!` it would
/// look like `ioctl!(read blkbszget with 0x12; 112; size_t)`. This macro would generate a function that
/// looks like: `pub unsafe fn blkbszget(fd: nix::sys::ioctl::libc::c_int, val: *mut size_t) ->
/// nix::Result<nix::sys::ioctl::libc::c_int>`. Therefore this ioctl will write data into the given `size_t`
/// variable.

**Comment by Susurrus** [comment]
@beamspease Could you check out #670 and let me know if that would be in line with what you'd like in the docs for `ioctl!`?
