### ISSUE TITLE
how do i use ISR with nix?

### ISSUE THREAD

**Issue by sailfish009** [nix-rust/nix#574]
Can i use Interrupt Service Routine with nix?
without using #naked functions.

**Comment by asomers** [comment]
You mean in kernel level code?  It's really cool that you're doing that, but I don't think that nix is for you.  Nix's purpose is to wrap common Unix (userland) APIs in a Rust-friendly way.  I don't think you'll find much here that's of use within the kernel.  Or did you have some specific component in mind?

**Comment by sailfish009** [comment]
take look at this question:
https://stackoverflow.com/questions/43389196/rust-compiler-support-for-interrupts

**Comment by asomers** [comment]
signals and interrupts are not the same thing.  Signals happen in userland.  Interrupts happen in the kernel, if there is a kernel.  Which are you actually trying to use?

**Comment by sailfish009** [comment]
i don't use, i want to know how to accesss ISR with nix.

**Comment by asomers** [comment]
The answer is that you can't.  Nix has no features that help with writing ISRs.
