### ISSUE TITLE
Ability to add custom socket options

### ISSUE THREAD

**Issue by code-ape** [nix-rust/nix#577]
I was looking to do the following code except using nix instead of libc:

```rust
use libc::{c_ushort, c_int, c_void, socklen_t, SOL_SOCKET, setsockopt};

const SO_ATTACH_FILTER: c_int = 26;

pub fn attach_filter(fd: RawFd, prog: Prog) -> Result<(), Error> {
    match unsafe {
              setsockopt(fd as c_int,
                         SOL_SOCKET,
                         SO_ATTACH_FILTER,
                         &prog as *const _ as *const c_void,
                         size_of_val(&prog) as socklen_t)
          } {
        0 => Ok(()),
        _ => Err(Error::last_os_error()),
    }
}
```

However nix currently doesn't support this, which is fine. However, nix doesn't expose an easy way to use it's internal macros to construct the SO_ATTACH_FILTER command. I wanted to file an issue to suggest exposing this. I'll also look into contributing my use case to nix so it's added t the library for future users.

Code source: [https://github.com/jedisct1/rust-bpf/blob/0122d0a95e6012abab0475b14cef20dbfa481704/src/bpf_linux.rs#L58](https://github.com/jedisct1/rust-bpf/blob/0122d0a95e6012abab0475b14cef20dbfa481704/src/bpf_linux.rs#L58)

**Comment by Susurrus** [comment]
I don't quite understand the issue here as I'm not familiar with `setsockopt`. Do you have a proposal for how we might integrate this code example that would fit in with the rest of `nix`? Would exposing `sockopt_impl!` be enough for you?

**Comment by mexus** [comment]
Sorry for bringing up an old issue, but it happened so I need the same feature :)

Basically the issue is that the macro `sockopt_impl!` is not exposed, which will help a lot.
But it's not the only thing.

For example, for `SO_ATTACH_FILTER` we need to pass an object of a special type, which obviously does not implement [Set](https://docs.rs/nix/0.9.0/src/nix/sys/socket/sockopt.rs.html#193). But the `Set` trait is not exposed as well :)

So I guess exposing `sockopt_impl!` macro and `Set` and `Get` traits will help a lot.

**Comment by Susurrus** [comment]
Is there a reason we can't provide a `sockopt_impl!` within `nix` that exposes `SO_ATTACH_FILTER`? This has been the need for both you and @code-ape, so I'd suggest we start going down this route. We'd welcome a PR for it.

If we were to expose `sockopt_impl!` and those other traits, we'd need them all documented much more extensively. If you'd like to help with this effort, we welcome all PRs!

**Comment by mexus** [comment]
That's great, thanks! 👍 

I'll try to make it happen by the beginning of next week.

**Comment by mexus** [comment]
(I went for the second option)
