### ISSUE TITLE
New maintainers can't approve PRs

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#580]
[Noted by @Susurrus](https://github.com/nix-rust/nix/pull/536#issuecomment-294316385).

I'm considering attempting to move us to [bors-ng](https://github.com/bors-ng/bors-ng) which has some additional features on top of bors / homu:
- it's actively maintained
- it can batch PRs to merge multiple with one CI run

**Comment by kamalmarhubi** [comment]
@Susurrus 
> @kamalmarhubi There's a `synchronize` button on the homu website and it asked for permissions to my account and nix-rust on GitHub. Do I need to do that so that I recognizes me or something?

Maybe! Give it a shot, unless the permissions are not to your liking.

**Comment by posborne** [comment]
👍 on moving to Bors!

**Comment by kamalmarhubi** [comment]
@nix-rust/nix-maintainers FYI @homu is no more. The new way to approve PRs is `bors r+`, or `bors r=username`.
