### ISSUE TITLE
nix path when installed from source for non-root

### ISSUE THREAD

**Issue by sandeep-gh** [nix-rust/nix#619]
Probably I missed something basic but when installing from source (non-root) the nix-channel still looks for /nix. 
After installing from source, I sourced the nix environment as follows
```
source ~/opensource_projects/nix/etc/profile.d/nix.sh
```

**Comment by Susurrus** [comment]
I think you have the wrong project here. This repo is for `nix`, a Rust library providing a safe wrapper around POSIX functionality.

**Comment by sandeep-gh** [comment]
Sorry, will remove my post.
