### ISSUE TITLE
Use newtype pattern

### ISSUE THREAD

**Issue by Kixunil** [nix-rust/nix#627]
I was looking into this library and noticed it doesn't use newtype pattern. This makes it easily possible to accidentally swap `uid_t`, `gid_t`, `pid_t` and I suppose other s too.

I've experienced such bugs in practice. I'd suggest using newtypes like `Uid`, `Gid`, `Pid` in all interfaces and provide conversion functions (`impl From<Uid> for uid_t`) Such change would minimise chance of someone accidentally swapping those (and potentially creating security vulnerability).

I'd also suggest `const ROOT: Uid = Uid(0);`.

**Comment by asomers** [comment]
Yep.  Newer additions always use Newtype, but the older code hasn't all been converted.  Patches welcome!  Please open a pull request for any module you'd like to change.
