### ISSUE TITLE
Cross fails with error: `"rustup" "target" "list"` failed with exit code: Some(1)

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#634]
On about 25-June, all of our Travis builds started to fail with the error message:

> error: `"rustup" "target" "list"` failed with exit code: Some(1)

I don't know why it started on 25-June.  It's probably either a change to Travis (they updated their builders, but they claim it was done by 21-June), or Rustup, or Cross.  We should also report this bug upstream to japaric/cross
https://travis-ci.org/nix-rust/nix/builds/246718360

**Comment by asomers** [comment]
Turns out that Travis was cacheing our .cargo and target directories (because we told it to).  When rustup 1.5.0 came out on 24-June, that broke the build.  Something in our .cargo didn't like it, I guess.  Through the Travis control panel, I cleared our caches, and the problem is resolved.

**Comment by casey** [comment]
My nightly builds started failing, and clearing the cache was the solution.

Thanks for posting this issue, along with how to fix it!
