### ISSUE TITLE
Missing killpg

### ISSUE THREAD

**Issue by mmstick** [nix-rust/nix#644]
Needed by Ion to send signals to all members of a process group.

**Comment by Susurrus** [comment]
@mmstick Would you be willing to file a PR adding this to `nix`? I'd be happy to mentor you through the process if you would. Always looking for new contributors!

**Comment by mmstick** [comment]
Sure. Where can I start?

**Comment by Susurrus** [comment]
The first step is actually to get `killpg` and all related constants into the https://github.com/rust-lang/libc repo for all appropriate targets (see the supported list of targets for `nix` in the README).

Once that's done, you can file a PR here adding `killpg` after `kill` in `src/sys/signal.rs`. Be sure to add doc comments and ideally a test if you could (spawn a new process group of something and try to kill it, which should work without `sudo` privileges I would think so it can be safely run in CI).

**Comment by SanchayanMaity** [comment]
@Susurrus killpg has two signatures.

```
int killpg(int pgrp, int sig);
int killpg(pid_t pgrp, int sig);
```
How to handle this? Or should the pid_t signature alone be sufficient? Do I understand correctly that the below change in rust libc alone is sufficient to carry this forward?.

```
diff --git a/src/unix/mod.rs b/src/unix/mod.rs
index 35a7f448..2e65b43c 100644
--- a/src/unix/mod.rs
+++ b/src/unix/mod.rs
@@ -562,6 +562,7 @@ extern {
     #[cfg_attr(all(target_os = "macos", target_arch = "x86"),
                    link_name = "kill$UNIX2003")]
     pub fn kill(pid: pid_t, sig: ::c_int) -> ::c_int;
+    pub fn killpg(pgrp: pid_t, sig: ::c_int) -> ::c_int;
 
     pub fn mlock(addr: *const ::c_void, len: ::size_t) -> ::c_int;
     pub fn munlock(addr: *const ::c_void, len: ::size_t) -> ::c_int;
```

**Comment by asomers** [comment]
AFAIK `pid_t` is equal to `int` everywhere.  But POSIX says that the first argument should be `pid_t.`.  Your suggested patch looks correct to me.

**Comment by SanchayanMaity** [comment]
killpg in rust-lang/libc#879 is now merged.

**Comment by Susurrus** [comment]
@mmstick @SanchayanMaity With `killpg` in libc, please feel free to fille a PR adding this to all relevant platforms.

**Comment by stratact** [comment]
I too need `killpkg` for my project to kill all processes associated by group id since `std::process::Child::kill()` is not good enough for what I'm doing. It would be useful to have instead of relying on the `libc` crate.
