### ISSUE TITLE
missing getifaddrs

### ISSUE THREAD

**Issue by mwanner** [nix-rust/nix#650]
I implemented a trivial wrapper around `getifaddrs`, which I'd like to polish and get into the nix crate, if that's appropriate. Any specific requirements regarding the interface? Otherwise I'd prepare something based on an `Iterator` over the entries returned.

**Comment by Susurrus** [comment]
Thanks for volunteering your work! I'm sure that interface you find usable will be fine. It can also be modified later if it's hard to use in a specific use case. We do like to have good documentation and tests, so please spend some time on that so that it's easy to use.
