### ISSUE TITLE
buildbot screws up pull requests from a "master" branch

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#652]
Buildbot is mostly building stuff fine.  But if the source branch of a pull request is named "master", then buildbot will try to build the master branch of the nix repo instead of the source repo.  But it can't find the revision in question, so the build fails.  For example, PR #651, from mmstick/nix:master, led to this broken build: https://alan.ci/buildbot/#/builders/5/builds/229 .

**Comment by Susurrus** [comment]
Is this fixed or is there something more to do here?

**Comment by asomers** [comment]
My buildbot config change seems to have fixed it.
