### ISSUE TITLE
`pub extern crate libc` can probably be used now.

### ISSUE THREAD

**Issue by marmistrz** [nix-rust/nix#655]
https://github.com/nix-rust/nix/blob/master/src/lib.rs#L26
```
// In rust 1.8+ this should be `pub extern crate libc` but prior
// to https://github.com/rust-lang/rust/issues/26775 being resolved
// it is necessary to get a little creative.
pub mod libc {
    extern crate libc;
    pub use self::libc::*;
}
```

https://github.com/rust-lang/rust/issues/26775 has already been closed.

**Comment by Susurrus** [comment]
Actually, it can't. See [here](https://github.com/posborne/nix-rust/commit/99d6a00994183c96b96180907f072d2d0ceb8cbc) for the original issue. And the release notes for Rust 1.4 suggest this is still the case.

I believe the solution is to do:
```
extern crate libc;
pub use libc
```

**Comment by jonas-schievink** [comment]
Nah this should work fine by now
