### ISSUE TITLE
Errnos are available through multiple paths in nix

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#664]
The current problem is the errnos (like `EAGAIN`) are exposed at `nix::Errno::EAGAIN` and `nix::errno::EAGAIN`. We should choose one "right" path and only expose these constants there. I'd probably keep `Errno` at `nix::errno::Errno` instead of re-exporting it in the root.

**Comment by jonas-schievink** [comment]
AFAIK reexporting enum variants is considered bad style (they're scoped for a reason)

**Comment by Susurrus** [comment]
Indeed. Would you be interested in taking this on and filing a PR to get this all cleaned up? I started working on this but the `errno` module needs more work than I realized.

**Comment by jonas-schievink** [comment]
I'm currently taking a look at #586, but after that's finished I can check this one out.
