### ISSUE TITLE
TravisCI is too slow

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#669]
We have 34 builds in Travis, and it takes over an hour for all of them to finish.  It's causing Bors to timeout.  At a minimum, we need to increase bors's timeout.  Other ways to speed up the builds include:

1. Move i686-unknown-freebsd into BuildBot
2. remove `sudo: required`.  It causes Travis to use a full VM instead of a container, and I don't think we need it.
3. Only test beta and nightly builds on one architecture.
4. Enable parallel tests.  This will likely have minimal benefit, because setting up the environment is slower than running tests.
5. Use a custom Docker image so we won't have to download the QEMU stuff all the time
6. Set Travis's Auto Cancel Pull Requests feature

Any other ideas?

**Comment by Susurrus** [comment]
I agree with 1, 2, 3, and 6. For 3, I'd suggest we just drop nightly, as there's little benefit to us testing on it. I like that these are all pretty low-hanging fruit. We can deal with a custom docker image later if this continues to be problematic.

**Comment by Susurrus** [comment]
I've already handled 6 and turned on auto cancel for pull requests. I left it on for branches as it isn't necessary there.

**Comment by Susurrus** [comment]
With #674 closed, we've knocked out 2 & 3. What do you say @asomers about doing 1? I think it'd be nice to get Buildbot doing a bit more since it runs so quickly!

**Comment by asomers** [comment]
FreeBSD 11.1 is scheduled to be released on July 26.  I'm going to wait until then so I can kill 2 birds with one stone.

**Comment by Susurrus** [comment]
Sounds good. Also, do you want to turn this issue's numbered list into checkboxes so we can check off ones that are done?

**Comment by Susurrus** [comment]
BTW: Good work on #674. An 18% reduction in CI build times is nothing to sneeze at!

**Comment by asomers** [comment]
Progress report:

- [ ] Move i686-unknown-freebsd into BuildBot (waiting for 11.1-RELEASE)
- [x] remove sudo: required. It causes Travis to use a full VM instead of a container, and I don't think we need it.
- [x] Only test beta and nightly builds on one architecture.
- [ ] Enable parallel tests. This will likely have minimal benefit, because setting up the environment is slower than running tests.
- [ ] Use a custom Docker image so we won't have to download the QEMU stuff all the time
- [x] Set Travis's Auto Cancel Pull Requests feature

**Comment by Susurrus** [comment]
There's a high variability in the time it takes the Mac builds to run. I think having them all grouped together in the middle is bad for our total processing time. I'd suggest we intersperse the mac/ios builds across the rest of them so we're never stuck if Macs are slow to build (often happens during the day with Travis). Travis CI will only process 5 builds simultaneously, so we should keep to every 3rd or 4th are mac/ios builds and I think we'll see a more consistent processing time.

**Comment by Susurrus** [comment]
One of the biggest issues is the long queue times for mac builders on Travis. I think it'd be good if we condensed all `ios` testing onto a single machine that ran them all in parallel. This would reduce our requirement for mac CI jobs from 7 to 3.
