### ISSUE TITLE
Upgrade FreeBSD buildbot images

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#675]
The FreeBSD Docker image used by BuildBot could use an upgrade.  Specifically, we should
- [x] Upgrade to 11.1-RELEASE (scheduled for release on 26-July)
- [x] Add an i686 image
- [x] Use Rust 1.13.0 instead of stable
- [x] For extra speed, pre-download dependent crates when constructing the image

**Comment by Susurrus** [comment]
And [11.1 is released](https://www.freebsd.org/news/newsflash.html#event20170726:01).

**Comment by asomers** [comment]
First build on 11.1: https://alan.ci/buildbot/#/builders/5/builds/555

**Comment by asomers** [comment]
Pre downloading dependent crates looks like it saves about 20s on the FreeBSD build.

**Comment by asomers** [comment]
PR #713 fixed the final item.  I wasn't able to use Rust 1.13.0 on i386, though, because i686-unknown-freebsd is not supported by Rustup.  So that platform uses FreeBSD's Rust package, which is currently 1.19.0.
