### ISSUE TITLE
Add execvpe support

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#682]
This was removed in #681 because it was broken. Re-adding it is basically undoing fcc22f22a680233dbeb82d230e35fd54cb6de176 (without the feature support and instead conditionally including it on supported platforms). `libc` has `execvpe` included for `haiku`, `linux`, and `openbsd` platforms. If you are a new contributor, go ahead and read `CONTRIBUTING.md`, assign this to yourself, and file a PR when you've gotten somewhere (start the title with `WIP` if it's not ready to merge, and include "closes #682" in the text of the PR).

**Comment by panzertime** [comment]
I'd like to be assigned this issue

**Comment by Susurrus** [comment]
Awesome! Thanks for offering to contribute to `nix`!

I wasn't expecting someone to pick this up so quickly, so this is actually missing a crucial detail that you'll want to make a first commit that changes the `libc` dependency back to git (making that one change as a single commit means it can be easily removed later). And since you got here so quick I also wanted to ask how did you find out about this issue or nix?

Just post here if you have any issues and I'll be sure to address them ASAP!

**Comment by panzertime** [comment]
Basically, I stumbled across `nix` while searching for a way to practice my Rust, and when I looked at the issues I was lucky enough to find a fresh beginner issue

**Comment by Susurrus** [comment]
Awesome, well I'm glad I keep a few of these around! There's plenty of easy work to do around here (see #254 and #264 for more).

**Comment by F1rst-Unicorn** [comment]
Hi guys,
I have ported the code from the old pull request and adapted the missing parts. Will be glad to see this
merged soon.
