### ISSUE TITLE
`cargo test foo` runs tests for mount and ptymaster_drop too

### ISSUE THREAD

**Issue by geofft** [nix-rust/nix#702]
If I run, say, `cargo test ptrace` to run only tests with "ptrace" in their names, it also runs all the test_mount and test_ptymaster_drop tests. I suppose this is because they define their own `main()` and don't look at `args().nth(1)` to see if it should only run a subset of tests, or something?

(They run fast so this isn't really a problem, it's just confusing.)

**Comment by asomers** [comment]
Yep.  That's how cargo works.  It runs every test program with the argument "ptrace".  If you only want to run the integration tests,  and you want to pass a filter to them, you can use the confusing command line `cargo test --test test ptrace`
