### ISSUE TITLE
nix 0.9.0 

### ISSUE THREAD

**Issue by aep** [nix-rust/nix#703]
more a question: is 0.9.0 backwards compatible with 0.8.1? 
either quite a few things changed or i'm misinterpreting the errors from 
https://github.com/oracle/railcar/issues/24

for example a major one:
```
   |                 ^^^^ Could not find `poll` in `nix`
```

**Comment by asomers** [comment]
Nope.  There are API changes going from 0.8.1 to 0.9.0.  In general, you can expect API changes from any crate when it changes minor versions prior to 1.0.0.  All changes should all be mentioned in the CHANGELOG.  If not, please tell us, because that's a bug.
