### ISSUE TITLE
The Future of ioctls

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#707]
With my recent PR cleaning up the `ioctl` module I saw some references to [cmr/ioctl](https://github.com/cmr/ioctl) and how the `ioctl` module was based on that work. That crate is now deprecated, but I wanted to bring up what we see as the future of nice bindings to `ioctl`s. There is the dcuddeback's `ioctl-rs` crate, but that appears unmaintained as well.

I know that [rust-spidev](https://github.com/rust-embedded/rust-spidev) and [serialport-rs](https://gitlab.com/susurrus/serialport-rs) both have their own custom implementation of `ioctl`s and it's a little cumbersome. They, among others, would likely benefit from a central location of ioctl bindings.

i was thinking of bringing the `cmr/ioctl` repository under the `nix-rust` organization as a new repo & crate. We'd then provide unsafe bindings around `ioctl`s, ideally with a significant amount of type safety thrown on top of them. We'd need at least one person willing to oversee this crate and move it forward, maybe @cmr if you're willing? As I don't think we have any left-over developer time with the existing nix maintainers.

**Comment by cmr** [comment]
I'm willing, but I might not have the time :) We'll see! I might come back to it.

**Comment by asomers** [comment]
What sort of benefits do you think we could get from a centralized ioctl repo?  Ioctls are extremely variable; aside from our `ioctl!` macros I don't think there's much common functionality we could provide.  I have a lot of experience writing Ruby bindings for ioctl-heavy APIs, and I've never come across a single one that I've wanted to reuse elsewhere.  Leaving the bindings in separate domain-specific gems has worked out well for me.

**Comment by cmr** [comment]
Wait, `rust-spidev` uses `ioctl!`. I'm not sure it's a good idea to have all the wrapper code for every ioctl in a single crate. https://github.com/cmr/evdev, the reason I made the original ioctl crate at all, just uses `nix` instead.

**Comment by Susurrus** [comment]
@asomers That's a fair point. The common functionality between `ioctl`s is mostly handled by `nix`, so other crates would need to create nice APIs that would be pretty specific to the given ioctl. It just seemed more appropriate to have one large crate than a ton of small specifc crates. If we have multiple people using the ioctl crate they might find bugs even if they're using different ioctls that wouldn't otherwise be found if people were using separate ioctl crates. There's a decent amount of overhead on the maintenance side of things when having very small crates, so we could reduce that by having CI framework and issue tracker etc all shared across those crates. Could even feature-gate it so people didn't even need to build ioctls they didn't want.
