### ISSUE TITLE
Doc tests fail for me on Rust 1.19 due to linking errors

### ISSUE THREAD

**Issue by marmistrz** [nix-rust/nix#708]
https://gist.github.com/marmistrz/a6e503a5491df80a493030e0a0e702d2

Using Arch Linux, Rust 1.19 from repositories. It looks like Rust stdlib for some reason has some C++ symbols but is linked using a C compiler. Should I report it against my distro package?

**Comment by asomers** [comment]
It looks like you have stdlib installed by your distro.  That might interfere with what cargo downloads.  What happens if you simply remove /usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1cca08df8b8463bb.so and try building again?

**Comment by marmistrz** [comment]
@asomers `rustc` won't find the stdlib as it links dynamically against libstd.

**Comment by asomers** [comment]
@marmistrz are you using rustc as installed by Arch, or as installed by rustup?  If you're using rustup's rustc, then it shouldn't use any rust libraries in /usr/lib64.

**Comment by marmistrz** [comment]
I'm using my distro's rustc.

**Comment by marmistrz** [comment]
Reported this against my distro: https://bugs.archlinux.org/task/54933

**Comment by kyrias** [comment]
Apparently the build is broken in a weird way if you're using the system jemalloc rather than letting rust build its own.  I'm currently rebuilding rustc and will push a new package in around a few hours.  This issue can be closed.  (Though I need to remember to open an issue on the rust repo.)

**Comment by kyrias** [comment]
I've pushed 1.19.0-2 to community now, so should be able to close this now.

**Comment by Susurrus** [comment]
@kyrias Thanks for tackling this, glad it's resolved.
