### ISSUE TITLE
Enable setresuid and setresgid for more platforms

### ISSUE THREAD

**Issue by wezm** [nix-rust/nix#717]
`unistd::setresuid` and `unistd::setresgid` are currently wrapped in a module that only is only included on Linux and Android. The functions appear to be present on other systems as well:

- [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=setresuid&apropos=0&sektion=0&manpath=FreeBSD+11.1-RELEASE+and+Ports&arch=default&format=html)
- [OpenBSD](http://man.openbsd.org/setresuid)

NetBSD and macOS don't appear to have them.

**Comment by Susurrus** [comment]
Would you be will in to file a PR enabling them on those platforms? You'll need the check that they're all defined in libc beforehand so everything will pass CI.

**Comment by wezm** [comment]
Yep definitely. Will aim to do it this week.

**Comment by Susurrus** [comment]
@wezm Excellent, thanks for being willing to contribute! In the future, feel free to just file a PR instead of both an issue and a PR, unless you're uncertain if we'd accept the feature. It generates slightly less noise for us maintainers :-)

**Comment by wezm** [comment]
Ok, no problem, will do. Turns out neither of these functions are in the libc crate (for FreeBSD and OpenBSD). So I'll have to do the dance of getting them added there first.

**Comment by Susurrus** [comment]
@wezm Excellent, thanks. If you could add it for all supported platforms also, so we can offer pretty complete support here in `nix`, it'd be much appreciated. When you create an issue, please link it to this one so I can track progress.

**Comment by jlgerber** [comment]
What about OS X?
