### ISSUE TITLE
calling nix from libraries that return io:Error

### ISSUE THREAD

**Issue by oconnor663** [nix-rust/nix#723]
Version 0.9 switched to a new error type, and also removed the conversion impl to io::Error. Downstream we're thinking about adding our own conversion (https://github.com/oconnor663/os_pipe.rs/pull/10) to keep our existing `io::Result` interfaces, but I wanted to check in and see if that's what you expected downstream libraries to do.

**Comment by Susurrus** [comment]
Yes, you'll want to define your own error types. See #613 for some discussion. So I'm going to close this, but if that discussion doesn't make the reasoning clear, feel free to post again here.
