### ISSUE TITLE
nix::unistd::write should take a signed integer

### ISSUE THREAD

**Issue by n3f4s** [nix-rust/nix#767]
Hi,

Currently, `nix::unistd::write` take, as second parameter, a `u8`:
```rust
pub fn write(fd: RawFd, buf: &[u8]) -> Result<usize>
```
but the unix API specify that it should take a void pointer (from `man 3 write`):
```C
ssize_t write(int fildes, const void *buf, size_t nbyte);
```

The main difference between those two prototypes is that the C version allow to give to `write` a negative integer. With the rust version, we can't give a negative integer to `write` which mean that we can't write, for example, `EOF`.

For example, if you write to the standard input of a REPL, you might want to send `EOF` to the REPL when quitting:
```C
signed char eof = EOF;
write(repl_stdin_fd, &eof, 1);
```
Currently it is not possible since `libc::EOF` is an i32 and `nix::unistd::write` takes an `&[u8]`.

Hence, `nix::unistd::write` should take an `&[i8]` and `nix` should define a a 'new' `EOF` of type `i8`:
```rust
pub fn write(fd: RawFd, buf: &[i8]) -> Result<usize>
```
 or `nix::unistd::write` should take an `&[i32]` so that we can use `libc::EOF`:
```rust
pub fn write(fd: RawFd, buf: &[i32]) -> Result<usize>
```

**Comment by Susurrus** [comment]
I don't believe this is actually correct behavior actually. `write()` writes bytes, it doesn't write integers. Now a byte is canonically a `u8`. As soon as you get to more complex types (even i32) you have to manage serialization details (big- versus little-endian for example). And the difference between an `i8` and a `u8` is really semantics, it just specifies what the bit patterns mean. I'm of the opinion that a `u8` is the canonical byte representation as the concept of a "negative byte" doesn't make much sense.

So I believe the solution is to actually modify EOF in `libc` or to just specify 255. That being said, you can cast it using as:

```rust
extern crate libc;

fn main() {
    println!("{}", libc::EOF as u8);
}
```

which prints 255, which has the same bit pattern as `-1i8`.

**Comment by asomers** [comment]
@Susurrus is right.  Closing this issue as a user misunderstanding.
