### ISSUE TITLE
Update Rust to 1.15 in the buildbots

### ISSUE THREAD

**Issue by marmistrz** [nix-rust/nix#769]
(can't assign anyone from mobile)
This is needed by #666

**Comment by marmistrz** [comment]
@asomers I can't assign it to you (permissions, probably)

**Comment by asomers** [comment]
It should be working now, but we have to wait until somebody updates a PR to be 100% sure.

**Comment by Susurrus** [comment]
Is this resolved? We've had PRs happen since this.

**Comment by marmistrz** [comment]
I wanted to add the trait which was dropped from #666 but I'm really busy in October, so I didn't have time to do it.

**Comment by Susurrus** [comment]
@marmistrz But this issue is just about updating the BuildBots to 1.15. @asomers is that done so this issue can be closed?

**Comment by asomers** [comment]
Yeah, it's done.
