### ISSUE TITLE
Resolve CI failures for beta-x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by Susurrus** [nix-rust/nix#793]
I've just run `cargo test` using both the `beta` and `nightly` toolchains, and neither failed. I'm guessing this is a CI failure caused by caching. With beta failing, it's not doing us any good because we always ignore it. I suggest we work to resolve this failure and change our CI tests so that failures running the beta toolchain will fail the whole build.

**Comment by asomers** [comment]
It passes for me, too.  But I just cleared Travis's caches and restarted a recent build, and it failed again :( .  Any other ideas?

**Comment by Susurrus** [comment]
I'm wondering if it's reusing a cache from a previous Travis build from the same run, not one across runs. Though I don't really get why the caching causes problems in the first place either.

**Comment by Susurrus** [comment]
For example, I wonder if running tests only on that platform would work.

**Comment by Susurrus** [comment]
Resolved with #805.
