### ISSUE TITLE
Add support for BSD's copyfile?

### ISSUE THREAD

**Issue by mre** [nix-rust/nix#803]
The [`copyfile`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/copyfile.3.html) syscall is similar to Linux' `splice` command. It is supported on Darwin other BSDs.
It would be nice to integrate that into nix.

Is there an interest in supporting the command? If so, I could give it a shot and try a PR.

**Comment by Susurrus** [comment]
I think that's a reasonable addition to `nix` and we would appreciate a PR! Note that `copyfile` doesn't appear in `libc` and your first step here will be to add `copyfile` to [`libc`](https://github.com/rust-lang/libc) first.

**Comment by mre** [comment]
So I created [this pull request in libc](https://github.com/rust-lang/libc/pull/886), but it's currently failing. I know, it's not the same project, but maybe you have an idea on how I could fix it?

**Comment by asomers** [comment]
Closing this issue, because the poster closed the upstream libc issue as well.
