### ISSUE TITLE
Remove return value from `pause`

### ISSUE THREAD

**Issue by Thomasdezeeuw** [nix-rust/nix#827]
Currently `nix::unistd::pause` returns an `nix::Error`, however it can only return `EINTR` as an error, which is the point of pause. It pauses until a signal is received. So I suggest to remove the return value completely and document that `pause` only returns if the process receives a signal.

If you want to be really safe maybe an assert can be added to check if the error is really `EINTR`, but then the OS/libc is vialting the spec.

Man page: http://pubs.opengroup.org/onlinepubs/9699919799/functions/pause.html.

**Comment by Susurrus** [comment]
Yes, that seems like a nice ergonomics improvement! Care to submit a PR for it?

**Comment by Thomasdezeeuw** [comment]
Closed by #836.
