### ISSUE TITLE
Trouble with nix::unistd::isatty function

### ISSUE THREAD

**Issue by sevagh** [nix-rust/nix#858]
Hello,

I want to check if stdin and stdout are TTYs in my code.

I replaced libc's unsafe check with nix's safe check:

```
-        if unsafe { libc::isatty(libc::STDIN_FILENO) != 0 } {
-            panic!("pq expects input to be piped from stdin");
-        }
+        match nix::unistd::isatty(libc::STDIN_FILENO) {
+            Ok(stdin_is_tty) => {
+                if !stdin_is_tty {
+                    panic!("pq expects input to be piped from stdin");
+                }
+            }
+            Err(e) => panic!("Error checking if stdin is tty: {}", e),
+        }
 ```

However, it doesn't work the same as libc did. Am I using the Nix function wrong?

I only tested this on Linux. The code is here: https://github.com/sevagh/pq

**Comment by asomers** [comment]
What do you mean "doesn't work the same?"  What did you expect `nix::unistd::isatty` to return, and what did it actually return?

**Comment by sevagh** [comment]
Libc thinks that stdin/stdout are TTYs in a situation where they are TTYs, but Nix doesn't.

Nix:

```sevagh:pq $ ./target/debug/pq --fdsetfile ./tests/fdsets/dog.fdset --msgtype com.example.dog.Dog <./tests/samples/dog | jq
thread 'main' panicked at 'pq expects input to be piped from stdin', src/commands.rs:58:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Libc:

```
sevagh:pq $ ./target/debug/pq --fdsetfile ./tests/fdsets/dog.fdset --msgtype com.example.dog.Dog <./tests/samples/dog | jq
{
  "age": 3,
  "breed": "gsd",
  "temperament": "excited"
}
```

**Comment by sevagh** [comment]
My terminal is Alacritty and this is running within Tmux (if any of those make a difference).

**Comment by asomers** [comment]
Try using either a debugger or `println!` to show the return value and errno of `libc::isatty` from within `nix::unistd::isatty`.

**Comment by sevagh** [comment]
Totally my mistake. In my head I inverted the true/false cases of `isatty`.
