### ISSUE TITLE
`getpwnam` is missing

### ISSUE THREAD

**Issue by ctrlcctrlv** [nix-rust/nix#862]

**Comment by Susurrus** [comment]
Is this a request to add that functionality or are you planning on adding it?

**Comment by ctrlcctrlv** [comment]
Hi,

I was planning on implementing it. There are a few related functions that are also missing, e.g. `getgrnam`.

I haven't implemented the others yet, but I have finished this one. (Tested only on FreeBSD.)

```
use libc::time_t;
#[derive(Debug, Default)]
pub struct Passwd {
    pub name: CString,
    pub passwd: CString,
    pub uid: uid_t,
    pub gid: gid_t,
    pub change: time_t,
    pub class: CString,
    pub gecos: CString,
    pub dir: CString,
    pub shell: CString,
    pub expire: time_t
}

pub fn getpwnam<S: Into<Vec<u8>>>(name: S) -> Result<Option<Passwd>> {
    let pw = unsafe { libc::getpwnam(CString::new(name).unwrap().as_ptr()).as_ref() };

    unsafe {
        match pw {
            None => {return Ok(None)},
            Some(pw) =>
                Ok( Some( Passwd {
                    name: CString::new(CStr::from_ptr(pw.pw_name).to_bytes()).unwrap(),
                    passwd: CString::new(CStr::from_ptr(pw.pw_passwd).to_bytes()).unwrap(),
                    class: CString::new(CStr::from_ptr(pw.pw_class).to_bytes()).unwrap(),
                    gecos: CString::new(CStr::from_ptr(pw.pw_gecos).to_bytes()).unwrap(),
                    dir: CString::new(CStr::from_ptr(pw.pw_dir).to_bytes()).unwrap(),
                    shell: CString::new(CStr::from_ptr(pw.pw_shell).to_bytes()).unwrap(),
                    uid: pw.pw_uid,
                    gid: pw.pw_gid,
                    change: pw.pw_change,
                    expire: pw.pw_expire
                } ) )
        }
    }
}
```

**Comment by ctrlcctrlv** [comment]
@Susurrus I notice my PR #864 has been ignored while later PR #865 has received many comments. Have I done something seriously wrong? Is my code that bad that there are so many errors no one wants to review it? :-(

**Comment by kristate** [comment]
@ctrlcctrlv Thanks for your hard work!
I did an informal review on your code.
I would appreciate if you could look over it.

**Comment by Susurrus** [comment]
@ctrlcctrlv To address your question directed to me, there isn't a real order to how we triage PRs or even code. Sometimes older things come to the top of my queue because I'm more familiar with the API it's implementing or even because it was the most recent email. So pinging is definitely the right idea.

@kristate Thanks for reviewing their code! We heavily rely on the community to help us. I see myself more of a project manager than a coder when it comes to `nix`, so having people help doing the code reviews and writing code is essential and much appreciated!

**Comment by sanxiyn** [comment]
You can use [pwd](https://crates.io/crates/pwd) crate if you need this NOW.

**Comment by 0xpr03** [comment]
Note that if you search for things like `getgrnam`, there is also [users](https://crates.io/crates/users).

**Comment by ctrlcctrlv** [comment]
Oh yeah, it sure can be. I had given up on this ever happening, but @otavio had far more patience than me. (Cf. #864.)
