### ISSUE TITLE
No Debug trait for PollFd

### ISSUE THREAD

**Issue by kccqzy** [nix-rust/nix#885]
I was trying to debug my program that uses poll(2) and discovered that it would be more convenient if nix supported Debug trait for PollFd.

The error message is

    `nix::poll::PollFd` cannot be formatted using `:?` because it doesn't implement `std::fmt::Debug`

Is there any reason we don't want this trait? It seems like to me, every struct should have the Debug trait to ease printf-debugging and logging.

**Comment by asomers** [comment]
libc has a policy of not deriving Debug for any struct.  That in turn prevents Nix from deriving Debug.  So Nix's Debug impls usually have to be hand-written.  That's the case for `PollFd`.  It would be pretty easy to add one, though.  If you submit a PR, I'll accept it.

**Comment by kccqzy** [comment]
Thanks! I've written a PR.

**Comment by kccqzy** [comment]
Thanks! I'm closing this issue because it's been resolved.
