### ISSUE TITLE
IPV6_RECVPKTINFO and IP_PKTINFO support

### ISSUE THREAD

**Issue by mcginty** [nix-rust/nix#890]
This feature would include both new SockOpts and new ControlMessages to be used with `sendmsg` and `recvmsg`.

I have an unclean patch here: https://github.com/nix-rust/nix/compare/master...mcginty:ipv6-pktinfo, and will be happy to turn this into a nicer PR if the devs think it could get merged.

The only really gross part is that `libc` doesn't have the constants for `IPV6_RECVPKTINFO` or `IP_PKTINFO`, so I had to grab them out of the header files for macOS and Linux (the two platforms I tested on).

**Comment by asomers** [comment]
You really shouldn't be afraid to update libc.  It's quite easy to get patches accepted there.  Once you do that and fix portability issues, I think this would be a fine feature to add.

**Comment by mcginty** [comment]
@asomers sounds good. I'll keep this issue open since it's still a feature request for `nix`, and will work on a libc PR.

**Comment by mcginty** [comment]
pending merge of https://github.com/rust-lang/libc/pull/980

**Comment by pusateri** [comment]
Merged in #990. Can be closed.
