### ISSUE TITLE
Missing bindings for `fchown`, `lchown`, and the `chmod` family

### ISSUE THREAD

**Issue by SolraBizna** [nix-rust/nix#903]
There are occasional situations where `fchown` is preferable to `chown`. The usefulness of `chmod` and its siblings is more self-evident.

Implementing `fchown` and `lchown` at least should be pretty easy, since nearly all the logic would be the same as for `chown`.

Edit: When documenting `fchown`/`fchmod`, it ought to be mentioned that they can't be used to portably change the permissions on a UNIX domain socket. (A lot of people make the mistake of assuming they can, including me ten minutes ago.)

**Comment by asomers** [comment]
Do you want to submit a PR for this?  It sounds useful to me.

**Comment by jbaublitz** [comment]
I see this is still open. I do in fact need this functionality and am happy to put together a PR if this hasn't been done yet. It looks like the PR referenced at the bottom of the issue here was never merged.

**Comment by SteveLauC** [comment]
* fchown is added
* lchown is not because you can use fchownat
* chmod is added
* fchmodat is added and thus we don't need lchmod

Close this issue as it is complete
