### ISSUE TITLE
Can't use sys::statfs::statfs without unsafe

### ISSUE THREAD

**Issue by alesharik** [nix-rust/nix#926]
Current implementation of `statfs` requires mutable reference of result variable, but I can't pass it to `statfs` without initialization. For example this code
 ```rust
let mut statf: libc::statfs;
sys::statfs::statfs(Path::new(&String::from("/")), &mut statf).unwrap();
```
 gives me this error: 
```rust
error[E0381]: use of possibly uninitialized variable: `statf`
sys::statfs::statfs(Path::new(&String::from("/")), &mut statf).unwrap();
                                                        ^^^^^ use of possibly uninitialized `statf`
```
So I need to somehow initialize the variable:
 ```rust
let mut statf: libc::statfs = unsafe { mem::uninitialized() };
sys::statfs::statfs(Path::new(&String::from("/")), &mut statf).unwrap();
```
Maybe it will be better to return result with `libc::statfs` struct instead of empty result?

**Comment by Susurrus** [comment]
Yes, that seems like the correct change. Additionally we should use a newtype wrapper around `libc::statfs` so we don't export `libc` types directly (this prevents `libc` breaking changes to become major-release breaking changes in nix).

The only open question here is whether reusing a `statfs` struct is ever necessary in practice. If so, we'd probably want two versions of each function, one returning the struct the other filling it in-place. I'd bet this functionality isn't necessary, but a look at production code would be useful here.

@alesharik Would you be willing to file a PR to fix this? It's unlikely to get fixed anytime soon if you aren't.
