### ISSUE TITLE
request_code_write_int! on BSD systems uses VOID "direction" instead of IN

### ISSUE THREAD

**Issue by glebpom** [nix-rust/nix#934]
Hi, 

there is a bug, which leads to the generation of wrong ioctl codes on BSD systems:
https://github.com/nix-rust/nix/blob/master/src/sys/ioctl/bsd.rs#L60

**Comment by asomers** [comment]
Do you have an example of an ioctl that demonstrates the problem?

**Comment by Susurrus** [comment]
This was added explicitly to fix a bug on BSDs. See commit 1a815f11473c1eb91a5613f8fe67d5e97975b3fc. There were tests added in that commit as well.

Also, which BSD are you on? We're missing tests for OpenBSD and NetBSD.

**Comment by glebpom** [comment]
Ok, I see the problem. `_IOWINT` has this bug, but there are certain `ioctl`'s which accept the `int` parameter defined in  `_IOW`. e.g. https://github.com/freebsd/freebsd/blob/master/sys/sys/filio.h#L49
There is no good API in nix for it. I had to use a workaround through the `_ptr` variant.

**Comment by glebpom** [comment]
BTW, I have found [very few usages of `_IOWINT` in FreeBSD](https://github.com/freebsd/freebsd/search?q=_IOWINT&unscoped_q=_IOWINT).  Much less than `_IOW` with `int` param

**Comment by glebpom** [comment]
There is no _IOWINT in [OpenBSD](https://github.com/openbsd/src/blob/master/sys/sys/ioccom.h) and [NetBSD](https://github.com/IIJ-NetBSD/netbsd-src/blob/master/sys/sys/ioccom.h). There are only [3 usages in FragonFly](https://github.com/DragonFlyBSD/DragonFlyBSD/search?q=_IOWINT&type=Code) and [14 in FreeBSD](https://github.com/freebsd/freebsd/search?q=_IOWINT&unscoped_q=_IOWINT)

**Comment by glebpom** [comment]
I was trying to use 

```
#define	TUNSIFHEAD	_IOW('t', 96, int)
``` 

from https://github.com/freebsd/freebsd/blob/master/sys/net/if_tun.h#L45

To enable the headers in packets received from TUN interface, one should send the non-zero value to this `ioctl` as `int` argument. The reasonable nix ioctl function definition would be:
```
ioctl_write_int!(tun_enable_header, b't', 96);
```
But, because for BSD systems this macro represents the behavior if `_IOWINT`, it generates incorrect code (`0x20047460` instead of `0x80047460`).

I had to use the workaround, and define it like
```
ioctl_write_ptr!(tun_enable_header, b't', 96, c_int);
```
and pass any non-null pointer.

It seems like there is no better option for now.

Considering the fact, that there are very few ioctl's, which rely on `_IOWINT`, I think it makes sense to define the separate macro for this particular case, e.g.:
```
// #define KDSKBMODE 	_IOWINT('K', 7)
ioctl_write_int_as_void!(b'K', 7)
```
and revert the change in `ioctl_write_int!`

**Comment by glebpom** [comment]
Ok, I was wrong. _IOW expect the pointer to `int`, not `int` itself. So it's correct to use `ioctl_write_ptr` in this case. Closing

**Comment by Susurrus** [comment]
Is there some way we could improve the docs to reduce this confusion. Ive been working hard to make our ioctl docs decent because all of this is so confusing and am always looking to further improve them. Any feedback here from you would be most appreciated.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
