### ISSUE TITLE
issues with ioctl_read_buf + lack of example

### ISSUE THREAD

**Issue by jleni** [nix-rust/nix#937]
I noticed that there is an open TODO looking for an example of ioctl_read_buf. Maybe once I solve my problem I can provide that example.

https://github.com/nix-rust/nix/blob/70cce1a384ec21c6ba0ef38d64d2f67333e4b7d7/src/sys/ioctl/mod.rs#L692

I am trying to use this macro but I have not been successful. Maybe this when fixed could be used as an example.

```c
#define HID_MAX_DESCRIPTOR_SIZE     4096
#define HIDIOCGRDESCSIZE	_IOR('H', 0x01, int)
#define HIDIOCGRDESC        _IOR('H', 0x02, struct hidraw_report_descriptor)

struct hidraw_report_descriptor {
    __u32 size;
    __u8 value[HID_MAX_DESCRIPTOR_SIZE];
};
```

In the first call I get how much valid data will be returned. In the second, I read that data.

```rust
let mut desc_size: u32 = 0;
let err = unsafe { hid_read_descr_size(file.as_raw_fd(), &mut desc_size); };

let mut desc_raw = [0xFFu8; 4 + 4096];
let err = unsafe { hid_read_descr(file.as_raw_fd(), &mut desc_raw); };

```

In the second call I initialize `dest_raw` with `0xFF` to see what changes. After the call, there are no changes in the buffer. My expectation is that at least the first 4 bytes should be matching `desc_size`

Am I using the macro incorrectly?

**Comment by jleni** [comment]
The alternative, does not seem to work either

```rust
ioctl_read!(hid_read_descr2, b'H', 0x02, [u8; 4+4096]);
...
let mut desc_raw = [0xFFu8; 4 + 4096];
let err = unsafe { hid_read_descr2(file.as_raw_fd(), &mut desc_raw); };

```

**Comment by Susurrus** [comment]
I just did some searching for examples and [found this](https://github.com/atomic-penguin/linux/blob/master/samples/hidraw/hid-example.c). I'd suggest running that example and using `strace` to view the raw system calls. Then you can compare how they do it in C with your example and confirm what's going on.

**Comment by posborne** [comment]
@jleni I believe the size you read needs to be populated in the struct as it is passed to the kernel when you make the HIDIOCGRDESC call.

See https://elixir.bootlin.com/linux/v3.18.119/source/drivers/hid/hidraw.c#L397.  You are just passing a pointer as the arg to the kernel and it is reading that pointer as a u32 for the length portion as the length is the first part of the structure as defined here: https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/hidraw.h#L22

**Comment by Susurrus** [comment]
@jleni Did you get the problem sorted? I think what @posborne said is correct? I'd love to know that you have it working and also get our documentation updated with this as an example.

**Comment by Susurrus** [comment]
This still uses the array format, correct? Would you be willing to write up an example we can add for that?

**Comment by Susurrus** [comment]
We already have examples for that, so I think we can just close this now.
