### ISSUE TITLE
Implement copy_file_range() system call for Linux

### ISSUE THREAD

**Issue by ArniDagur** [nix-rust/nix#941]
[copy_file_range()](http://man7.org/linux/man-pages/man2/copy_file_range.2.html) has yet to be implemented.

**Comment by asomers** [comment]
If you're interested, feel free to submit a patch.  Nix works 99% on user contributions.

**Comment by ArniDagur** [comment]
How I should handle the `flags` argument of `copy_file_range`? The man page says that "the flags argument is provided to allow for future extensions and currently must be to 0".

Here's what I've got at the moment (haven't tested it yet but it compiles):
```rust
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn copy_file_range(fd_in: RawFd, off_in: Option<&mut libc::loff_t>,
          fd_out: RawFd, off_out: Option<&mut libc::loff_t>,
          len: usize) -> Result<usize> {
    let off_in = off_in.map(|offset| offset as *mut _).unwrap_or(ptr::null_mut());
    let off_out = off_out.map(|offset| offset as *mut _).unwrap_or(ptr::null_mut());

    let ret = unsafe {
        libc::syscall(libc::SYS_copy_file_range, fd_in, off_in, fd_out, off_out, len, 0 )
    };
    Errno::result(ret).map(|r| r as usize)
}
```

**Comment by asomers** [comment]
There are two choices:
1) Leave out the flags argument as you did.
2) Create a `CopyFileRangeFlags` enum with a single `None` variant.

**Comment by ArniDagur** [comment]
I've been struggling with the testing, so I'm wondering if you could lend a hand.

This code (using explicit file names `/tmp/test.txt` and `/tmp/test2.txt` for debugging purposes) works:

```rust
        let mut reader = File::open("/tmp/test.txt").unwrap();
        let mut writer = OpenOptions::new().read(true).write(true).truncate(true)
                            .open("/tmp/test2.txt").unwrap();

        let res = copy_file_range(reader.as_raw_fd(), None,
                                  writer.as_raw_fd(), None,
                                  2, CopyFileRangeFlags::empty())
                                  .unwrap();
        assert_eq!(2, res);
```

As seen here:
```
[arni@arni-pc][~/OpenSource/nix]% cat /tmp/test.txt
hello world
[arni@arni-pc][~/OpenSource/nix]% cat /tmp/test2.txt
he%      
```

But when trying to read the contents of `/tmp/test2.txt` after the copy, no bytes seem to be returned. I tried various methods.
