### ISSUE TITLE
Provide mechanism to access raw user/group IDs

### ISSUE THREAD

**Issue by jmmv** [nix-rust/nix#943]
I am implementing a FUSE file system using the Rust `fuse` library. As part of this, I have to supply the kernel with UID and GID values for file attributes in the form of `u32` values. At the moment, I'm doing something like:

```
            uid: unsafe { libc::getuid() },
            gid: unsafe { libc::getgid() },
```

It'd be nice if I could replace these with nix's reimplementation of `getuid` and `getgid` to avoid the unsafe blocks. However, I haven't found a way to do so because there doesn't seem to be a way to extract the raw identifiers from `Uid` and `Gid` objects.

What would be the best way to do this?

Thanks.

**Comment by asomers** [comment]
How about [`nix::unistd::Uid::as_raw`](https://github.com/nix-rust/nix/blob/d302e8d278bcd5b10ab7a30a467b5d8e21139ff2/src/unistd.rs#L53)?  It was added recently, and isn't in a released version yet.

**Comment by jmmv** [comment]
Oh, that will work. Didn't see it because I was looking at the documentation for the last release.

One question though: I'm guessing the size of `uid_t` and `gid_t` will vary on a platform basis, right? How is the caller supposed to deal with that? I will have to make sure the size of the returned values fits within the `u32` that FUSE exposes, but that seems fragile from a portability perspective and thus for the API of `nix`.

**Comment by asomers** [comment]
libc defines `uid_t` to be `u32` on all unix platforms.  Only redox is different, and Nix doesn't support redox.  So in your code, you can just do something like:
```rust
let x = uid.as_raw();
some_fuse_func(u32::from(x))
```
https://github.com/rust-lang/libc/blob/master/src/unix/mod.rs#L9

**Comment by jmmv** [comment]
I see. Thanks. I've encountered other cases where the size changes for other types, but I guess they were unrelated to this. Will wait until the next nix release comes out.
