### ISSUE TITLE
Add sync / syncfs

### ISSUE THREAD

**Issue by r-darwish** [nix-rust/nix#959]

**Comment by asomers** [comment]
Sure.  Would you mind opening a PR for that?

**Comment by r-darwish** [comment]
Sure. No problem

**Comment by r-darwish** [comment]
It seems that `syncfs` is Linux specific, and isn't available in `libc`, so I opened a pull request containing only `sync`.

**Comment by asomers** [comment]
Closing this completed issue.  In the future, if you put "fixes # <issue number>" on its own line in the commit message, then Github will automatically close the issue once the PR is merged.
