### ISSUE TITLE
Make aio an optional feature

### ISSUE THREAD

**Issue by njaard** [nix-rust/nix#976]
I use nix in a shared library and nix requires aio and aio lives in -laio as opposed to stdlibc. That results in my binaries having an additional dependency on aio even though I don't actually use aio.

**Comment by asomers** [comment]
Nix uses POSIX aio, not libaio.  POSIX aio merely needs librt.  libaio is a separate beast.  Something else in your application must be pulling it in.

**Comment by njaard** [comment]
Definitely not, I established a minimal pair with nix. Removing nix fixed the problem.

Many errors of this form:

```
... .a(nix-d2f66c26b23178b3.nix.e8pnq1ld-cgu.2.rcgu.o):nix.e8pnq1ld-cgu.2:function nix::mqueue::mq_open: error: undefined reference to 'mq_open'

... .a(nix-d2f66c26b23178b3.nix.e8pnq1ld-cgu.7.rcgu.o):nix.e8pnq1ld-cgu.7:function nix::sys::aio::LioCb::error: error: undefined reference to 'aio_error'
```

**Comment by asomers** [comment]
`mq_open` and `aio_error` are both part of librt, not libaio.

**Comment by njaard** [comment]
Then shouldn't those two be optional features so that my library which used to not need librt still doesn't?

**Comment by asomers** [comment]
There would be no point, because event Rust's standard library depends on librt.  You could try building with lto, which might remove it.  For that matter, those libraries should get linked automatically.  Are you building without Cargo or something?

**Comment by njaard** [comment]
I'm building into a static library which then gets linked into a C++ program. None of my program depends on librt so my C++ program shouldn't need to either.

**Comment by Susurrus** [comment]
What's the actual issue here? Is librt not available on your target platform? Do you care about the extra time to load an additional library? Do you care about the space?

**Comment by asomers** [comment]
Try building with LTO.  I think that will strip the offending symbols, if they're unused.
