### ISSUE TITLE
CmsgSpace::new unsafely creates uninitialized, arbitrary types

### ISSUE THREAD

**Issue by goffrie** [nix-rust/nix#994]
Even though the uninitialized field is private, it still gets dropped. For example `nix::sys::socket::CmsgSpace::<String>::new();` easily causes a segfault.

The field should probably be `ManuallyDrop<T>`, or there should be a `T: Copy` bound.

**Comment by asomers** [comment]
Good catch.  Unfortunately, we can't require `Copy`.  If we did, our own tests wouldn't compile!  That's because libc structs aren't `Copy`.  Would you like to submit a PR that implements the `ManuallyDrop` solution?

**Comment by asomers** [comment]
Nevermind.  I'm going to eliminate CmsgSpace instead.
