### ISSUE TITLE
Switch FreeBSD CI from buildbot to Cirrus

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#996]
Cirrus-ci.com recently introduced a new FreeBSD build service.  It's free for FOSS and seems to work pretty well from my experience.  Switching Nix from Buildbot to Cirrus would increase our bus factor, make builds more maintainable (since the build script would live in the repo), and save @asomers $$$.  If everybody agrees, then @kamalmarhubi needs to follow the instructions at https://cirrus-ci.org/guide/quick-start/ up until the post-installation step.  Then I'll submit a PR to finish it.

**Comment by Susurrus** [comment]
Sounds good to me.

**Comment by asomers** [comment]
@kamalmarhubi could you please add the Cirrus-CI app to our repo?

**Comment by asomers** [comment]
ping @kamalmarhubi .
